import manifest from "@/generated/cardGalleryManifest.json";

export interface CardGalleryImage {
  /** Public-relative src, e.g. /sets/cards/2026-topps-disney-neon/2026-topps-disney-neon-1.jpg */
  src: string;
  /** The trailing integer parsed from the filename (used for alt text + sort). */
  n: number;
  /** Intrinsic pixel width — drives the gallery card's aspect ratio (no layout shift). */
  width: number;
  /** Intrinsic pixel height. */
  height: number;
}

/** Shape of each entry in the build-time manifest (src/generated/cardGalleryManifest.json). */
interface ManifestImage {
  file: string;
  width: number;
  height: number;
}

const GALLERY: Record<string, ManifestImage[]> = manifest as Record<string, ManifestImage[]>;

// Trailing integer of a {slug}-{n}.{ext} filename. The manifest is already
// deduped + sorted ascending by this value at build time (see
// scripts/generate-card-gallery-manifest.ts), so we only need to surface `n`.
const N_FROM_FILE = /-(\d+)\.(?:jpe?g|png|webp)$/i;

/**
 * Card-gallery images for a set, read from the static build-time manifest.
 *
 * The manifest is generated by scripts/generate-card-gallery-manifest.ts, wired
 * into `npm run build`/`dev` via the prebuild/predev lifecycle scripts, so this
 * runtime path never touches the filesystem, sharp, or process.cwd(). That is
 * what keeps @vercel/nft from tracing public/sets/cards/** into the sets/[id]
 * serverless function (Vercel's 250MB limit).
 *
 * Returns [] when the set has no gallery folder (the common case for the ~800
 * folderless sets), so the gallery section simply does not render. Async
 * signature retained so existing `await` call sites are unchanged.
 */
export async function getCardGalleryImages(
  slug: string | null | undefined
): Promise<CardGalleryImage[]> {
  if (!slug) return [];
  const list = GALLERY[slug];
  if (!list) return [];

  return list.map(({ file, width, height }) => {
    const m = file.match(N_FROM_FILE);
    return { src: `/sets/cards/${slug}/${file}`, n: m ? parseInt(m[1], 10) : 0, width, height };
  });
}
