#!/usr/bin/env python3
"""Parser for 2025-26 Bowman Basketball."""
import json

# ---------------------------------------------------------------------------
# Parallel definitions (none specified for this set — add later via script)
# ---------------------------------------------------------------------------
NO_PARALLELS = []

# ---------------------------------------------------------------------------
# Raw section data
# ---------------------------------------------------------------------------

BASE_SET_RAW = [
    ("1",   "Cooper Flagg",              "Dallas Mavericks",          True),
    ("2",   "Dylan Harper",              "San Antonio Spurs",         True),
    ("3",   "VJ Edgecombe",              "Philadelphia 76ers",        True),
    ("4",   "Kon Knueppel",              "Charlotte Hornets",         True),
    ("5",   "Ace Bailey",                "Utah Jazz",                 True),
    ("6",   "Tre Johnson III",           "Washington Wizards",        True),
    ("7",   "Jeremiah Fears",            "New Orleans Pelicans",      True),
    ("8",   "Egor Dëmin",                "Brooklyn Nets",             True),
    ("9",   "Collin Murray-Boyles",      "Toronto Raptors",           True),
    ("10",  "Khaman Maluach",            "Phoenix Suns",              True),
    ("11",  "Cedric Coward",             "Memphis Grizzlies",         True),
    ("12",  "Noa Essengue",              "Chicago Bulls",             True),
    ("13",  "Derik Queen",               "New Orleans Pelicans",      True),
    ("14",  "Carter Bryant",             "San Antonio Spurs",         True),
    ("15",  "Thomas Sorber",             "Oklahoma City Thunder",     True),
    ("16",  "Yang Hansen",               "Portland Trail Blazers",    True),
    ("17",  "Joan Beringer",             "Minnesota Timberwolves",    True),
    ("18",  "Walter Clayton Jr.",        "Utah Jazz",                 True),
    ("19",  "Nolan Traore",              "Brooklyn Nets",             True),
    ("20",  "Kasparas Jakučionis",       "Miami Heat",                True),
    ("21",  "Will Riley",                "Washington Wizards",        True),
    ("22",  "Drake Powell",              "Brooklyn Nets",             True),
    ("23",  "Asa Newell",                "Atlanta Hawks",             True),
    ("24",  "Nique Clifford",            "Sacramento Kings",          True),
    ("25",  "Jase Richardson",           "Orlando Magic",             True),
    ("26",  "Ben Saraf",                 "Brooklyn Nets",             True),
    ("27",  "Danny Wolf",                "Brooklyn Nets",             True),
    ("28",  "Hugo González",             "Boston Celtics",            True),
    ("29",  "Liam McNeeley",             "Charlotte Hornets",         True),
    ("30",  "Yanic Konan-Niederhäuser",  "Los Angeles Clippers",      True),
    ("31",  "Rasheer Fleming",           "Phoenix Suns",              True),
    ("32",  "Noah Penda",                "Orlando Magic",             True),
    ("33",  "Sion James",                "Charlotte Hornets",         True),
    ("34",  "Ryan Kalkbrenner",          "Charlotte Hornets",         True),
    ("35",  "Johni Broome",              "Philadelphia 76ers",        True),
    ("36",  "Adou Thiero",               "Los Angeles Lakers",        True),
    ("37",  "Buddy Hield",               "Golden State Warriors",     True),
    ("38",  "Chaz Lanier",               "Detroit Pistons",           True),
    ("39",  "Kam Jones",                 "Indiana Pacers",            True),
    ("40",  "Alijah Martin",             "Toronto Raptors",           True),
    ("41",  "Micah Peavy",               "New Orleans Pelicans",      True),
    ("42",  "Koby Brea",                 "Phoenix Suns",              True),
    ("43",  "Maxime Raynaud",            "Sacramento Kings",          True),
    ("44",  "Jamir Watkins",             "Washington Wizards",        True),
    ("45",  "Brooks Barnhizer",          "Oklahoma City Thunder",     True),
    ("46",  "Javon Small",               "Memphis Grizzlies",         True),
    ("47",  "Kobe Sanders",              "Los Angeles Clippers",      True),
    ("48",  "Alex Toohey",               "Golden State Warriors",     True),
    ("49",  "John Tonje",                "Utah Jazz",                 True),
    ("50",  "Taelon Peter",              "Indiana Pacers",            True),
    ("51",  "Lachlan Olbrich",           "Chicago Bulls",             True),
    ("52",  "Will Richard",              "Golden State Warriors",     True),
    ("53",  "Max Shulga",                "Boston Celtics",            True),
    ("54",  "Jahmai Mashack",            "Memphis Grizzlies",         True),
    ("55",  "Tyrese Proctor",            "Cleveland Cavaliers",       True),
    ("56",  "Jayson Tatum",              "Boston Celtics",            False),
    ("57",  "Jaylen Brown",              "Boston Celtics",            False),
    ("58",  "Derrick White",             "Boston Celtics",            False),
    ("59",  "Cam Thomas",                "Brooklyn Nets",             False),
    ("60",  "Jalen Wilson",              "Brooklyn Nets",             False),
    ("61",  "Cameron Johnson",           "Brooklyn Nets",             False),
    ("62",  "Jalen Brunson",             "New York Knicks",           False),
    ("63",  "OG Anunoby",                "New York Knicks",           False),
    ("64",  "Karl-Anthony Towns",        "New York Knicks",           False),
    ("65",  "Jared McCain",              "Philadelphia 76ers",        False),
    ("66",  "Tyrese Maxey",              "Philadelphia 76ers",        False),
    ("67",  "Joel Embiid",               "Philadelphia 76ers",        False),
    ("68",  "Scottie Barnes",            "Toronto Raptors",           False),
    ("69",  "Immanuel Quickley",         "Toronto Raptors",           False),
    ("70",  "Gradey Dick",               "Toronto Raptors",           False),
    ("71",  "Coby White",                "Chicago Bulls",             False),
    ("72",  "Josh Giddey",               "Chicago Bulls",             False),
    ("73",  "Matas Buzelis",             "Chicago Bulls",             False),
    ("74",  "Cade Cunningham",           "Detroit Pistons",           False),
    ("75",  "Jalen Duren",               "Detroit Pistons",           False),
    ("76",  "Ausar Thompson",            "Detroit Pistons",           False),
    ("77",  "Tyrese Haliburton",         "Indiana Pacers",            False),
    ("78",  "Bennedict Mathurin",        "Indiana Pacers",            False),
    ("79",  "Pascal Siakam",             "Indiana Pacers",            False),
    ("80",  "Giannis Antetokounmpo",     "Milwaukee Bucks",           False),
    ("81",  "Damian Lillard",            "Milwaukee Bucks",           False),
    ("82",  "Kyle Kuzma",                "Milwaukee Bucks",           False),
    ("83",  "Trae Young",                "Atlanta Hawks",             False),
    ("84",  "Zaccharie Risacher",        "Atlanta Hawks",             False),
    ("85",  "Jalen Johnson",             "Atlanta Hawks",             False),
    ("86",  "LaMelo Ball",               "Charlotte Hornets",         False),
    ("87",  "Brandon Miller",            "Charlotte Hornets",         False),
    ("88",  "Tyler Herro",               "Miami Heat",                False),
    ("89",  "Bam Adebayo",               "Miami Heat",                False),
    ("90",  "Kel'el Ware",               "Miami Heat",                False),
    ("91",  "Donovan Mitchell",          "Cleveland Cavaliers",       False),
    ("92",  "Darius Garland",            "Cleveland Cavaliers",       False),
    ("93",  "Evan Mobley",               "Cleveland Cavaliers",       False),
    ("94",  "Paolo Banchero",            "Orlando Magic",             False),
    ("95",  "Franz Wagner",              "Orlando Magic",             False),
    ("96",  "Anthony Black",             "Orlando Magic",             False),
    ("97",  "Jordan Poole",              "Washington Wizards",        False),
    ("98",  "Bilal Coulibaly",           "Washington Wizards",        False),
    ("99",  "Alex Sarr",                 "Washington Wizards",        False),
    ("100", "Nikola Jokić",              "Denver Nuggets",            False),
    ("101", "Jamal Murray",              "Denver Nuggets",            False),
    ("102", "Russell Westbrook",         "Denver Nuggets",            False),
    ("103", "Anthony Edwards",           "Minnesota Timberwolves",    False),
    ("104", "Naz Reid",                  "Minnesota Timberwolves",    False),
    ("105", "Terrence Shannon Jr.",      "Minnesota Timberwolves",    False),
    ("106", "Shai Gilgeous-Alexander",   "Oklahoma City Thunder",     False),
    ("107", "Jalen Williams",            "Oklahoma City Thunder",     False),
    ("108", "Chet Holmgren",             "Oklahoma City Thunder",     False),
    ("109", "Scoot Henderson",           "Portland Trail Blazers",    False),
    ("110", "Shaedon Sharpe",            "Portland Trail Blazers",    False),
    ("111", "Toumani Camara",            "Portland Trail Blazers",    False),
    ("112", "Lauri Markkanen",           "Utah Jazz",                 False),
    ("113", "Kyle Filipowski",           "Utah Jazz",                 False),
    ("114", "Isaiah Collier",            "Utah Jazz",                 False),
    ("115", "Stephen Curry",             "Golden State Warriors",     False),
    ("116", "Jimmy Butler III",          "Golden State Warriors",     False),
    ("117", "Draymond Green",            "Golden State Warriors",     False),
    ("118", "Kawhi Leonard",             "Los Angeles Clippers",      False),
    ("119", "James Harden",              "Los Angeles Clippers",      False),
    ("120", "Ivica Zubac",               "Los Angeles Clippers",      False),
    ("121", "LeBron James",              "Los Angeles Lakers",        False),
    ("122", "Bronny James Jr.",          "Los Angeles Lakers",        False),
    ("123", "Luka Dončić",               "Los Angeles Lakers",        False),
    ("124", "Devin Booker",              "Phoenix Suns",              False),
    ("125", "Kevin Durant",              "Houston Rockets",           False),
    ("126", "Bradley Beal",              "Phoenix Suns",              False),
    ("127", "DeMar DeRozan",             "Sacramento Kings",          False),
    ("128", "Zach LaVine",               "Sacramento Kings",          False),
    ("129", "Domantas Sabonis",          "Sacramento Kings",          False),
    ("130", "Kyrie Irving",              "Dallas Mavericks",          False),
    ("131", "Anthony Davis",             "Dallas Mavericks",          False),
    ("132", "Klay Thompson",             "Dallas Mavericks",          False),
    ("133", "Alperen Sengun",            "Houston Rockets",           False),
    ("134", "Amen Thompson",             "Houston Rockets",           False),
    ("135", "Reed Sheppard",             "Houston Rockets",           False),
    ("136", "Ja Morant",                 "Memphis Grizzlies",         False),
    ("137", "Jaren Jackson Jr.",         "Memphis Grizzlies",         False),
    ("138", "Desmond Bane",              "Memphis Grizzlies",         False),
    ("139", "Zach Edey",                 "Memphis Grizzlies",         False),
    ("140", "Herbert Jones",             "New Orleans Pelicans",      False),
    ("141", "Trey Murphy III",           "New Orleans Pelicans",      False),
    ("142", "Dejounte Murray",           "New Orleans Pelicans",      False),
    ("143", "Victor Wembanyama",         "San Antonio Spurs",         False),
    ("144", "De'Aaron Fox",              "San Antonio Spurs",         False),
    ("145", "Stephon Castle",            "San Antonio Spurs",         False),
    ("146", "Chris Paul",                "San Antonio Spurs",         False),
    ("147", "Jeremy Sochan",             "San Antonio Spurs",         False),
    ("148", "Kristaps Porzingis",        "Boston Celtics",            False),
    ("149", "Payton Pritchard",          "Boston Celtics",            False),
    ("150", "Nic Claxton",               "Brooklyn Nets",             False),
    ("151", "Noah Clowney",              "Brooklyn Nets",             False),
    ("152", "Mikal Bridges",             "New York Knicks",           False),
    ("153", "Josh Hart",                 "New York Knicks",           False),
    ("154", "Paul George",               "Philadelphia 76ers",        False),
    ("155", "Guerschon Yabusele",        "Philadelphia 76ers",        False),
    ("156", "RJ Barrett",                "Toronto Raptors",           False),
    ("157", "Nikola Vučević",            "Chicago Bulls",             False),
    ("158", "Patrick Williams",          "Chicago Bulls",             False),
    ("159", "Jaden Ivey",                "Detroit Pistons",           False),
    ("160", "Ron Holland II",            "Detroit Pistons",           False),
    ("161", "Myles Turner",              "Indiana Pacers",            False),
    ("162", "Obi Toppin",                "Indiana Pacers",            False),
    ("163", "Andrew Nembhard",           "Indiana Pacers",            False),
    ("164", "AJ Green",                  "Milwaukee Bucks",           False),
    ("165", "Gary Trent Jr.",            "Milwaukee Bucks",           False),
    ("166", "Dyson Daniels",             "Atlanta Hawks",             False),
    ("167", "Onyeka Okongwu",            "Atlanta Hawks",             False),
    ("168", "Mark Williams",             "Charlotte Hornets",         False),
    ("169", "Tidjane Salaün",            "Charlotte Hornets",         False),
    ("170", "Andrew Wiggins",            "Miami Heat",                False),
    ("171", "Jaime Jaquez Jr.",          "Miami Heat",                False),
    ("172", "Jarrett Allen",             "Cleveland Cavaliers",       False),
    ("173", "Jaylon Tyson",              "Cleveland Cavaliers",       False),
    ("174", "Jalen Suggs",               "Orlando Magic",             False),
    ("175", "Tristan da Silva",          "Orlando Magic",             False),
    ("176", "Bub Carrington",            "Washington Wizards",        False),
    ("177", "Kyshawn George",            "Washington Wizards",        False),
    ("178", "AJ Johnson",                "Washington Wizards",        False),
    ("179", "Michael Porter Jr.",        "Denver Nuggets",            False),
    ("180", "Peyton Watson",             "Denver Nuggets",            False),
    ("181", "Christian Braun",           "Denver Nuggets",            False),
    ("182", "Rob Dillingham",            "Minnesota Timberwolves",    False),
    ("183", "Julius Randle",             "Minnesota Timberwolves",    False),
    ("184", "Luguentz Dort",             "Oklahoma City Thunder",     False),
    ("185", "Cason Wallace",             "Oklahoma City Thunder",     False),
    ("186", "Aaron Wiggins",             "Oklahoma City Thunder",     False),
    ("187", "Deni Avdija",               "Portland Trail Blazers",    False),
    ("188", "Donovan Clingan",           "Portland Trail Blazers",    False),
    ("189", "Keyonte George",            "Utah Jazz",                 False),
    ("190", "Jordan Clarkson",           "Utah Jazz",                 False),
    ("191", "Jonathan Kuminga",          "Golden State Warriors",     False),
    ("192", "Norman Powell",             "Los Angeles Clippers",      False),
    ("193", "Austin Reaves",             "Los Angeles Lakers",        False),
    ("194", "Dalton Knecht",             "Los Angeles Lakers",        False),
    ("195", "Ryan Dunn",                 "Phoenix Suns",              False),
    ("196", "Oso Ighodaro",              "Phoenix Suns",              False),
    ("197", "Devin Carter",              "Sacramento Kings",          False),
    ("198", "Dereck Lively II",          "Dallas Mavericks",          False),
    ("199", "Jalen Green",               "Houston Rockets",           False),
    ("200", "Santi Aldama",              "Memphis Grizzlies",         False),
]

RED_ROOKIE_VARIATIONS_RAW = [
    ("BRR-1",  "Cooper Flagg",             "Dallas Mavericks"),
    ("BRR-2",  "Dylan Harper",             "San Antonio Spurs"),
    ("BRR-3",  "VJ Edgecombe",             "Philadelphia 76ers"),
    ("BRR-4",  "Kon Knueppel",             "Charlotte Hornets"),
    ("BRR-5",  "Ace Bailey",               "Utah Jazz"),
    ("BRR-6",  "Tre Johnson III",          "Washington Wizards"),
    ("BRR-7",  "Jeremiah Fears",           "New Orleans Pelicans"),
    ("BRR-8",  "Egor Dëmin",               "Brooklyn Nets"),
    ("BRR-9",  "Collin Murray-Boyles",     "Toronto Raptors"),
    ("BRR-10", "Khaman Maluach",           "Phoenix Suns"),
    ("BRR-11", "Cedric Coward",            "Memphis Grizzlies"),
    ("BRR-12", "Noa Essengue",             "Chicago Bulls"),
    ("BRR-13", "Derik Queen",              "New Orleans Pelicans"),
    ("BRR-14", "Carter Bryant",            "San Antonio Spurs"),
    ("BRR-15", "Thomas Sorber",            "Oklahoma City Thunder"),
    ("BRR-16", "Yang Hansen",              "Portland Trail Blazers"),
    ("BRR-17", "Joan Beringer",            "Minnesota Timberwolves"),
    ("BRR-18", "Walter Clayton Jr.",       "Utah Jazz"),
    ("BRR-19", "Nolan Traore",             "Brooklyn Nets"),
    ("BRR-20", "Kasparas Jakučionis",      "Miami Heat"),
    ("BRR-21", "Will Riley",               "Washington Wizards"),
    ("BRR-22", "Drake Powell",             "Brooklyn Nets"),
    ("BRR-23", "Asa Newell",               "Atlanta Hawks"),
    ("BRR-24", "Nique Clifford",           "Sacramento Kings"),
    ("BRR-25", "Jase Richardson",          "Orlando Magic"),
    ("BRR-26", "Ben Saraf",                "Brooklyn Nets"),
    ("BRR-27", "Danny Wolf",               "Brooklyn Nets"),
    ("BRR-28", "Hugo González",            "Boston Celtics"),
    ("BRR-29", "Liam McNeeley",            "Charlotte Hornets"),
    ("BRR-30", "Yanic Konan-Niederhäuser", "Los Angeles Clippers"),
    ("BRR-31", "Rasheer Fleming",          "Phoenix Suns"),
    ("BRR-32", "Noah Penda",               "Orlando Magic"),
    ("BRR-33", "Sion James",               "Charlotte Hornets"),
    ("BRR-34", "Ryan Kalkbrenner",         "Charlotte Hornets"),
    ("BRR-35", "Johni Broome",             "Philadelphia 76ers"),
    ("BRR-36", "Adou Thiero",              "Los Angeles Lakers"),
    ("BRR-37", "Will Richard",             "Golden State Warriors"),
    ("BRR-38", "Chaz Lanier",              "Detroit Pistons"),
    ("BRR-39", "Kam Jones",                "Indiana Pacers"),
    ("BRR-40", "Alijah Martin",            "Toronto Raptors"),
    ("BRR-41", "Micah Peavy",              "New Orleans Pelicans"),
    ("BRR-42", "Koby Brea",                "Phoenix Suns"),
    ("BRR-43", "Maxime Raynaud",           "Sacramento Kings"),
    ("BRR-44", "Jamir Watkins",            "Washington Wizards"),
    ("BRR-45", "Brooks Barnhizer",         "Oklahoma City Thunder"),
    ("BRR-46", "Javon Small",              "Memphis Grizzlies"),
    ("BRR-47", "Kobe Sanders",             "Los Angeles Clippers"),
    ("BRR-48", "Alex Toohey",              "Golden State Warriors"),
    ("BRR-49", "John Tonje",               "Utah Jazz"),
    ("BRR-50", "Taelon Peter",             "Indiana Pacers"),
]

ETCHED_IN_GLASS_RAW = [
    ("NBE-1",  "Cooper Flagg",           "Dallas Mavericks",        True),
    ("NBE-2",  "Dylan Harper",           "San Antonio Spurs",       True),
    ("NBE-3",  "VJ Edgecombe",           "Philadelphia 76ers",      True),
    ("NBE-4",  "Kon Knueppel",           "Charlotte Hornets",       True),
    ("NBE-5",  "Ace Bailey",             "Utah Jazz",               True),
    ("NBE-6",  "Tre Johnson III",        "Washington Wizards",      True),
    ("NBE-7",  "Jeremiah Fears",         "New Orleans Pelicans",    True),
    ("NBE-8",  "Stephen Curry",          "Golden State Warriors",   False),
    ("NBE-9",  "Shai Gilgeous-Alexander","Oklahoma City Thunder",   False),
    ("NBE-10", "Luka Dončić",            "Los Angeles Lakers",      False),
]

RETROFRACTOR_VARIATIONS_RAW = [
    ("RV-BR", "Bill Russell",    "San Francisco", False),
    ("RV-SA", "Shaquille O'Neal","LSU",           False),
]

BASE_PROSPECTS_RAW = [
    ("BPP-1",   "AJ Dybantsa",           "BYU"),
    ("BPP-2",   "Darryn Peterson",       "Kansas"),
    ("BPP-3",   "Koa Peat",              "Arizona"),
    ("BPP-4",   "Kiyan Anthony",         "Syracuse"),
    ("BPP-5",   "Nate Ament",            "Tennessee"),
    ("BPP-6",   "Jasper Johnson",        "Kentucky"),
    ("BPP-7",   "Isiah Harwell",         "Houston"),
    ("BPP-8",   "Bryson Tiller",         "Kansas"),
    ("BPP-9",   "Obi Agbim",             "Baylor"),
    ("BPP-10",  "Shelton Henderson",     "Miami"),
    ("BPP-11",  "Tounde Yessoufou",      "Baylor"),
    ("BPP-12",  "Mikel Brown Jr.",       "Louisville"),
    ("BPP-13",  "Sienna Betts",          "UCLA"),
    ("BPP-14",  "Acaden Lewis",          "Villanova"),
    ("BPP-15",  "Madison Booker",        "Texas"),
    ("BPP-16",  "Jason Edwards",         "Providence"),
    ("BPP-17",  "Josh Dix",              "Creighton"),
    ("BPP-18",  "Niko Bundalo",          "Ole Miss"),
    ("BPP-19",  "Shon Abaev",            "Cincinnati"),
    ("BPP-20",  "Silas Demary Jr.",      "UConn"),
    ("BPP-21",  "Trey Kaufman-Renn",     "Purdue"),
    ("BPP-22",  "Zuby Ejiofor",          "St. John's"),
    ("BPP-23",  "Jaland Lowe",           "Kentucky"),
    ("BPP-24",  "Joe Grahovac",          "St. Bonaventure"),
    ("BPP-25",  "Kiyomi McMiller",       "Penn State"),
    ("BPP-26",  "Michael Rataj",         "Baylor"),
    ("BPP-27",  "Reed Bailey",           "Indiana"),
    ("BPP-28",  "Xaivian Lee",           "Florida"),
    ("BPP-29",  "Braeden Shrewsberry",   "Notre Dame"),
    ("BPP-30",  "Cotie McMahon",         "Ole Miss"),
    ("BPP-31",  "Serah Williams",        "UConn"),
    ("BPP-32",  "Owen Freeman",          "Creighton"),
    ("BPP-33",  "Aaliyah Crump",         "Texas"),
    ("BPP-34",  "Agot Makeer",           "University Of South Carolina"),
    ("BPP-35",  "Coen Carr",             "Michigan State"),
    ("BPP-36",  "Darrion Williams",      "NC State"),
    ("BPP-37",  "Derek Dixon",           "UNC"),
    ("BPP-38",  "Hailee Swain",          "Stanford"),
    ("BPP-39",  "Kaylene Smikle",        "Maryland"),
    ("BPP-40",  "Milos Uzan",            "Houston"),
    ("BPP-41",  "Sadiq White",           "Syracuse"),
    ("BPP-42",  "Tarris Reed Jr.",       "UConn"),
    ("BPP-43",  "Wesley Yates III",      "Washington"),
    ("BPP-44",  "Lara Somfai",           "Stanford"),
    ("BPP-45",  "Christian Anderson",    "Texas Tech"),
    ("BPP-46",  "Davion Hannah",         "Alabama"),
    ("BPP-47",  "Davis Fogle",           "Gonzaga"),
    ("BPP-48",  "Grace Knox",            "LSU"),
    ("BPP-49",  "Isaiah Denis",          "UNC"),
    ("BPP-50",  "Addison Deal",          "Iowa"),
    ("BPP-51",  "Brayden Burries",       "Arizona"),
    ("BPP-52",  "Bryce Lindsay",         "Villanova"),
    ("BPP-53",  "Cam Ward",              "Michigan State"),
    ("BPP-54",  "Chase Ross",            "Marquette"),
    ("BPP-55",  "Deniya Prawl",          "Tennessee"),
    ("BPP-56",  "Devin McGlockton",      "Vanderbilt"),
    ("BPP-57",  "Donald Hand Jr.",       "Boston College"),
    ("BPP-58",  "Ja'Kobi Gillespie",     "Tennessee"),
    ("BPP-59",  "Jamier Jones",          "Providence"),
    ("BPP-60",  "Keyshawn Hall",         "Auburn"),
    ("BPP-61",  "Leah Macy",             "Notre Dame"),
    ("BPP-62",  "Nick Martinelli",       "Northwestern"),
    ("BPP-63",  "Nyla Brooks",           "UNC"),
    ("BPP-64",  "Pharrel Payne",         "Maryland"),
    ("BPP-65",  "Raegan Beers",          "The University of Oklahoma"),
    ("BPP-66",  "Richie Saunders",       "BYU"),
    ("BPP-67",  "Winters Grady",         "Michigan"),
    ("BPP-68",  "Yarden Garzon",         "Maryland"),
    ("BPP-69",  "Darianna Alexander",    "Cincinnati"),
    ("BPP-70",  "Jeremiah Wilkinson",    "Georgia"),
    ("BPP-71",  "Kara Dunn",             "USC"),
    ("BPP-72",  "Boopie Miller",         "SMU"),
    ("BPP-73",  "ZaKiyah Johnson",       "LSU"),
    ("BPP-74",  "Jaida Civil",           "Tennessee"),
    ("BPP-75",  "Alexandra Eschmeyer",   "Stanford"),
    ("BPP-76",  "Aliyahna Morris",       "California"),
    ("BPP-77",  "CJ Ingram",             "Florida"),
    ("BPP-78",  "John Blackwell",        "Wisconsin"),
    ("BPP-79",  "Tobe Awaka",            "Arizona"),
    ("BPP-80",  "Sarah Strong",          "UConn"),
    ("BPP-81",  "Tre Holloman",          "NC State"),
    ("BPP-82",  "Kaelyn Carroll",        "Kentucky"),
    ("BPP-83",  "Caleb Wilson",          "UNC"),
    ("BPP-84",  "Ayla McDowell",         "University Of South Carolina"),
    ("BPP-85",  "Emilee Skinner",        "Duke"),
    ("BPP-86",  "Ta'Niya Latson",        "University Of South Carolina"),
    ("BPP-87",  "Oziyah Sellers",        "St. John's"),
    ("BPP-88",  "Nate Bittle",           "Oregon"),
    ("BPP-89",  "Kelis Fisher",          "UConn"),
    ("BPP-90",  "Bennett Stirtz",        "Iowa"),
    ("BPP-91",  "Ace Flagg",             "Maine"),
    ("BPP-92",  "Nate Calmese",          "Wake Forest"),
    ("BPP-93",  "JT Toppin",             "Texas Tech"),
    ("BPP-94",  "Braden Smith",          "Purdue"),
    ("BPP-95",  "Kohl Rosario",          "Kansas"),
    ("BPP-96",  "Juju Watkins",          "USC"),
    ("BPP-97",  "Brandon Garrison",      "Kentucky"),
    ("BPP-98",  "Otega Oweh",            "Kentucky"),
    ("BPP-99",  "Sebastian Wilkins",     "Duke"),
    ("BPP-100", "Caleb Foster",          "Duke"),
]

CHROME_PROSPECTS_EIG_RAW = [
    ("CPE-1", "AJ Dybantsa",    "BYU"),
    ("CPE-2", "Darryn Peterson","Kansas"),
    ("CPE-3", "Madison Booker", "Texas"),
    ("CPE-4", "Juju Watkins",   "USC"),
    ("CPE-5", "Koa Peat",       "Arizona"),
]

CHROME_PROSPECT_AUTOS_RAW = [
    ("CPA-AC",  "Aaliyah Crump",       "Texas"),
    ("CPA-AD",  "AJ Dybantsa",         "BYU"),
    ("CPA-AE",  "Addison Deal",        "Iowa"),
    ("CPA-AF",  "Ace Flagg",           "Maine"),
    ("CPA-AL",  "Acaden Lewis",        "Villanova"),
    ("CPA-AM",  "Agot Makeer",         "University Of South Carolina"),
    ("CPA-AO",  "Aliyahna Morris",     "California"),
    ("CPA-AS",  "Alexandra Eschmeyer", "Stanford"),
    ("CPA-AW",  "Ayla McDowell",       "University Of South Carolina"),
    ("CPA-BB",  "Brayden Burries",     "Arizona"),
    ("CPA-BG",  "Brandon Garrison",    "Kentucky"),
    ("CPA-BI",  "Bennett Stirtz",      "Iowa"),
    ("CPA-BL",  "Bryce Lindsay",       "Villanova"),
    ("CPA-BM",  "Braden Smith",        "Purdue"),
    ("CPA-BR",  "Boopie Miller",       "SMU"),
    ("CPA-BS",  "Braeden Shrewsberry", "Notre Dame"),
    ("CPA-BT",  "Bryson Tiller",       "Kansas"),
    ("CPA-CA",  "Christian Anderson",  "Texas Tech"),
    ("CPA-CC",  "Coen Carr",           "Michigan State"),
    ("CPA-CF",  "Caleb Foster",        "Duke"),
    ("CPA-CI",  "CJ Ingram",           "Florida"),
    ("CPA-CL",  "Caleb Wilson",        "UNC"),
    ("CPA-CM",  "Cotie McMahon",       "Ole Miss"),
    ("CPA-CR",  "Chase Ross",          "Marquette"),
    ("CPA-CW",  "Cam Ward",            "Michigan State"),
    ("CPA-DD",  "Derek Dixon",         "UNC"),
    ("CPA-DF",  "Davis Fogle",         "Gonzaga"),
    ("CPA-DH",  "Davion Hannah",       "Alabama"),
    ("CPA-DL",  "Darianna Alexander",  "Cincinnati"),
    ("CPA-DM",  "Devin McGlockton",    "Vanderbilt"),
    ("CPA-DN",  "Donald Hand Jr.",     "Boston College"),
    ("CPA-DP",  "Darryn Peterson",     "Kansas"),
    ("CPA-DR",  "Deniya Prawl",        "Tennessee"),
    ("CPA-DW",  "Darrion Williams",    "NC State"),
    ("CPA-ES",  "Emilee Skinner",      "Duke"),
    ("CPA-GK",  "Grace Knox",          "LSU"),
    ("CPA-HS",  "Hailee Swain",        "Stanford"),
    ("CPA-ID",  "Isaiah Denis",        "UNC"),
    ("CPA-IH",  "Isiah Harwell",       "Houston"),
    ("CPA-JA",  "Juju Watkins",        "USC"),
    ("CPA-JB",  "John Blackwell",      "Wisconsin"),
    ("CPA-JC",  "Jaida Civil",         "Tennessee"),
    ("CPA-JD",  "Josh Dix",            "Creighton"),
    ("CPA-JE",  "Jason Edwards",       "Providence"),
    ("CPA-JG",  "Joe Grahovac",        "St. Bonaventure"),
    ("CPA-JI",  "Ja'Kobi Gillespie",   "Tennessee"),
    ("CPA-JJ",  "Jasper Johnson",      "Kentucky"),
    ("CPA-JL",  "Jaland Lowe",         "Kentucky"),
    ("CPA-JO",  "Jamier Jones",        "Providence"),
    ("CPA-JT",  "JT Toppin",           "Texas Tech"),
    ("CPA-JW",  "Jeremiah Wilkinson",  "Georgia"),
    ("CPA-KA",  "Kiyan Anthony",       "Syracuse"),
    ("CPA-KC",  "Kaelyn Carroll",      "Kentucky"),
    ("CPA-KD",  "Kara Dunn",           "USC"),
    ("CPA-KF",  "Kelis Fisher",        "UConn"),
    ("CPA-KH",  "Keyshawn Hall",       "Auburn"),
    ("CPA-KM",  "Kiyomi McMiller",     "Penn State"),
    ("CPA-KP",  "Koa Peat",            "Arizona"),
    ("CPA-KR",  "Kohl Rosario",        "Kansas"),
    ("CPA-KS",  "Kaylene Smikle",      "Maryland"),
    ("CPA-LM",  "Leah Macy",           "Notre Dame"),
    ("CPA-LS",  "Lara Somfai",         "Stanford"),
    ("CPA-MB",  "Madison Booker",      "Texas"),
    ("CPA-MBJ", "Mikel Brown Jr.",     "Louisville"),
    ("CPA-MR",  "Michael Rataj",       "Baylor"),
    ("CPA-MU",  "Milos Uzan",          "Houston"),
    ("CPA-NA",  "Nate Ament",          "Tennessee"),
    ("CPA-NB",  "Niko Bundalo",        "Ole Miss"),
    ("CPA-NC",  "Nate Calmese",        "Wake Forest"),
    ("CPA-NI",  "Nate Bittle",         "Oregon"),
    ("CPA-NM",  "Nick Martinelli",     "Northwestern"),
    ("CPA-NR",  "Nyla Brooks",         "UNC"),
    ("CPA-OA",  "Obi Agbim",           "Baylor"),
    ("CPA-OF",  "Owen Freeman",        "Creighton"),
    ("CPA-OO",  "Otega Oweh",          "Kentucky"),
    ("CPA-OS",  "Oziyah Sellers",      "St. John's"),
    ("CPA-PP",  "Pharrel Payne",       "Maryland"),
    ("CPA-RB",  "Reed Bailey",         "Indiana"),
    ("CPA-RE",  "Raegan Beers",        "The University of Oklahoma"),
    ("CPA-RS",  "Richie Saunders",     "BYU"),
    ("CPA-SA",  "Shon Abaev",          "Cincinnati"),
    ("CPA-SB",  "Sienna Betts",        "UCLA"),
    ("CPA-SD",  "Silas Demary Jr.",    "UConn"),
    ("CPA-SH",  "Shelton Henderson",   "Miami"),
    ("CPA-SI",  "Sebastian Wilkins",   "Duke"),
    ("CPA-SS",  "Sarah Strong",        "UConn"),
    ("CPA-SW",  "Serah Williams",      "UConn"),
    ("CPA-SWH", "Sadiq White",         "Syracuse"),
    ("CPA-TA",  "Tobe Awaka",          "Arizona"),
    ("CPA-TK",  "Trey Kaufman-Renn",   "Purdue"),
    ("CPA-TL",  "Ta'Niya Latson",      "University Of South Carolina"),
    ("CPA-TR",  "Tarris Reed Jr.",     "UConn"),
    ("CPA-TY",  "Tounde Yessoufou",    "Baylor"),
    ("CPA-WG",  "Winters Grady",       "Michigan"),
    ("CPA-WY",  "Wesley Yates III",    "Washington"),
    ("CPA-XL",  "Xaivian Lee",         "Florida"),
    ("CPA-YG",  "Yarden Garzon",       "Maryland"),
    ("CPA-ZE",  "Zuby Ejiofor",        "St. John's"),
    ("CPA-ZJ",  "ZaKiyah Johnson",     "LSU"),
]

CHROME_AUTOS_RAW = [
    ("BCA-AA",  "Aaron Nesmith",           "Indiana Pacers",            False),
    ("BCA-AB",  "Ace Bailey",              "Utah Jazz",                 True),
    ("BCA-AE",  "Anthony Edwards",         "Minnesota Timberwolves",    False),
    ("BCA-AL",  "Ajay Mitchell",           "Oklahoma City Thunder",     False),
    ("BCA-AM",  "Alijah Martin",           "Toronto Raptors",           True),
    ("BCA-AN",  "Asa Newell",              "Atlanta Hawks",             True),
    ("BCA-AO",  "Alex Toohey",             "Golden State Warriors",     True),
    ("BCA-AR",  "Anthony Black",           "Orlando Magic",             False),
    ("BCA-AS",  "Alex Sarr",               "Washington Wizards",        False),
    ("BCA-AT",  "Adou Thiero",             "Los Angeles Lakers",        True),
    ("BCA-BA",  "Ben Saraf",               "Brooklyn Nets",             True),
    ("BCA-BB",  "Brooks Barnhizer",        "Oklahoma City Thunder",     True),
    ("BCA-BM",  "Brandon Miller",          "Charlotte Hornets",         False),
    ("BCA-BR",  "Bronny James Jr.",        "Los Angeles Lakers",        False),
    ("BCA-CC",  "Cedric Coward",           "Memphis Grizzlies",         True),
    ("BCA-CF",  "Cooper Flagg",            "Dallas Mavericks",          True),
    ("BCA-CL",  "Chaz Lanier",             "Detroit Pistons",           True),
    ("BCA-CMB", "Collin Murray-Boyles",    "Toronto Raptors",           True),
    ("BCA-CW",  "Cam Whitmore",            "Houston Rockets",           False),
    ("BCA-DA",  "Deandre Ayton",           "Portland Trail Blazers",    False),
    ("BCA-DC",  "Devin Carter",            "Sacramento Kings",          False),
    ("BCA-DFS", "Dorian Finney-Smith",     "Los Angeles Lakers",        False),
    ("BCA-DH",  "Dylan Harper",            "San Antonio Spurs",         True),
    ("BCA-DI",  "Derrick White",           "Boston Celtics",            False),
    ("BCA-DJ",  "Dillon Jones",            "Oklahoma City Thunder",     False),
    ("BCA-DP",  "Drake Powell",            "Brooklyn Nets",             True),
    ("BCA-DQ",  "Derik Queen",             "New Orleans Pelicans",      True),
    ("BCA-DV",  "Devin Vassell",           "San Antonio Spurs",         False),
    ("BCA-DW",  "Danny Wolf",              "Brooklyn Nets",             True),
    ("BCA-ED",  "Egor Dëmin",              "Brooklyn Nets",             True),
    ("BCA-EF",  "Enrique Freeman",         "Indiana Pacers",            False),
    ("BCA-FW",  "Franz Wagner",            "Orlando Magic",             False),
    ("BCA-GA",  "Giannis Antetokounmpo",   "Milwaukee Bucks",           False),
    ("BCA-GD",  "Gradey Dick",             "Toronto Raptors",           False),
    ("BCA-IC",  "Isaiah Collier",          "Utah Jazz",                 False),
    ("BCA-IZ",  "Ivica Zubac",             "Los Angeles Clippers",      False),
    ("BCA-JA",  "Jordan Hawkins",          "New Orleans Pelicans",      False),
    ("BCA-JB",  "Joan Beringer",           "Minnesota Timberwolves",    True),
    ("BCA-JC",  "Jordan Clarkson",         "Utah Jazz",                 False),
    ("BCA-JE",  "John Tonje",              "Utah Jazz",                 True),
    ("BCA-JI",  "Jaylin Williams",         "Oklahoma City Thunder",     False),
    ("BCA-JK",  "Jarace Walker",           "Indiana Pacers",            False),
    ("BCA-JL",  "Jalen Williams",          "Oklahoma City Thunder",     False),
    ("BCA-JM",  "Jahmai Mashack",          "Memphis Grizzlies",         True),
    ("BCA-JN",  "Jaylon Tyson",            "Cleveland Cavaliers",       False),
    ("BCA-JO",  "Johni Broome",            "Philadelphia 76ers",        True),
    ("BCA-JR",  "Jase Richardson",         "Orlando Magic",             True),
    ("BCA-JS",  "Javon Small",             "Memphis Grizzlies",         True),
    ("BCA-JT",  "Jayson Tatum",            "Boston Celtics",            False),
    ("BCA-JU",  "Jalen Brunson",           "New York Knicks",           False),
    ("BCA-JW",  "Jamir Watkins",           "Washington Wizards",        True),
    ("BCA-JY",  "Jamal Murray",            "Denver Nuggets",            False),
    ("BCA-KB",  "Koby Brea",               "Phoenix Suns",              True),
    ("BCA-KD",  "Kevin Durant",            "Houston Rockets",           False),
    ("BCA-KF",  "Kyle Filipowski",         "Utah Jazz",                 False),
    ("BCA-KJ",  "Kasparas Jakučionis",     "Miami Heat",                True),
    ("BCA-KK",  "Kon Knueppel",            "Charlotte Hornets",         True),
    ("BCA-KM",  "Khaman Maluach",          "Phoenix Suns",              True),
    ("BCA-KO",  "Kam Jones",               "Indiana Pacers",            True),
    ("BCA-KS",  "Kobe Sanders",            "Los Angeles Clippers",      True),
    ("BCA-KW",  "Kel'el Ware",             "Miami Heat",                False),
    ("BCA-LBJ", "LeBron James",            "Los Angeles Lakers",        False),
    ("BCA-LM",  "Liam McNeeley",           "Charlotte Hornets",         True),
    ("BCA-LO",  "Lachlan Olbrich",         "Chicago Bulls",             True),
    ("BCA-MP",  "Micah Peavy",             "New Orleans Pelicans",      True),
    ("BCA-MR",  "Maxime Raynaud",          "Sacramento Kings",          True),
    ("BCA-MS",  "Max Shulga",              "Boston Celtics",            True),
    ("BCA-MT",  "Myles Turner",            "Indiana Pacers",            False),
    ("BCA-NC",  "Nique Clifford",          "Sacramento Kings",          True),
    ("BCA-NE",  "Noa Essengue",            "Chicago Bulls",             True),
    ("BCA-NJ",  "Nikola Jokić",            "Denver Nuggets",            False),
    ("BCA-NO",  "Nikola Topić",            "Oklahoma City Thunder",     False),
    ("BCA-NP",  "Noah Penda",              "Orlando Magic",             True),
    ("BCA-NT",  "Nolan Traore",            "Brooklyn Nets",             True),
    ("BCA-PB",  "Paolo Banchero",          "Orlando Magic",             False),
    ("BCA-QP",  "Quinten Post",            "Golden State Warriors",     False),
    ("BCA-RD",  "Rob Dillingham",          "Minnesota Timberwolves",    False),
    ("BCA-RF",  "Rasheer Fleming",         "Phoenix Suns",              True),
    ("BCA-RH",  "Ron Holland II",          "Detroit Pistons",           False),
    ("BCA-RK",  "Ryan Kalkbrenner",        "Charlotte Hornets",         True),
    ("BCA-RU",  "Ryan Dunn",               "Phoenix Suns",              False),
    ("BCA-SC",  "Stephon Castle",          "San Antonio Spurs",         False),
    ("BCA-SGA", "Shai Gilgeous-Alexander", "Oklahoma City Thunder",     False),
    ("BCA-SH",  "Scoot Henderson",         "Portland Trail Blazers",    False),
    ("BCA-SJ",  "Sion James",              "Charlotte Hornets",         True),
    ("BCA-SU",  "Stephen Curry",           "Golden State Warriors",     False),
    ("BCA-TE",  "Taelon Peter",            "Indiana Pacers",            True),
    ("BCA-TP",  "Tyrese Proctor",          "Cleveland Cavaliers",       True),
    ("BCA-TS",  "Thomas Sorber",           "Oklahoma City Thunder",     True),
    ("BCA-TSJ", "Terrence Shannon Jr.",    "Minnesota Timberwolves",    False),
    ("BCA-VW",  "Victor Wembanyama",       "San Antonio Spurs",         False),
    ("BCA-WC",  "Walter Clayton Jr.",      "Utah Jazz",                 True),
    ("BCA-WI",  "Will Richard",            "Golden State Warriors",     True),
    ("BCA-WR",  "Will Riley",              "Washington Wizards",        True),
    ("BCA-YH",  "Yang Hansen",             "Portland Trail Blazers",    True),
    ("BCA-YK",  "Yanic Konan-Niederhäuser","Los Angeles Clippers",      True),
    ("BCA-ZE",  "Zach Edey",               "Memphis Grizzlies",         False),
    ("BCA-ZR",  "Zaccharie Risacher",      "Atlanta Hawks",             False),
]

RETROFRACTOR_AUTOS_RAW = [
    ("RAV-SO", "Shaquille O'Neal", "LSU", False),
]

FUTURE_SCRIPT_AUTOS_RAW = [
    ("FS-AD",  "AJ Dybantsa",      "BYU"),
    ("FS-AL",  "Acaden Lewis",     "Villanova"),
    ("FS-BC",  "Brynn McGaughy",   "Washington"),
    ("FS-BM",  "Boopie Miller",    "SMU"),
    ("FS-BT",  "Bryson Tiller",    "Kansas"),
    ("FS-CW",  "Caleb Wilson",     "UNC"),
    ("FS-DP",  "Darryn Peterson",  "Kansas"),
    ("FS-IH",  "Isiah Harwell",    "Houston"),
    ("FS-JD",  "Josh Dix",         "Creighton"),
    ("FS-JE",  "Jason Edwards",    "Providence"),
    ("FS-JJ",  "Jasper Johnson",   "Kentucky"),
    ("FS-KA",  "Kiyan Anthony",    "Syracuse"),
    ("FS-KC",  "Kaelyn Carroll",   "Kentucky"),
    ("FS-KP",  "Koa Peat",         "Arizona"),
    ("FS-MB",  "Madison Booker",   "Texas"),
    ("FS-MBJ", "Mikel Brown Jr.",  "Louisville"),
    ("FS-MU",  "Milos Uzan",       "Houston"),
    ("FS-NA",  "Nate Ament",       "Tennessee"),
    ("FS-NB",  "Niko Bundalo",     "Ole Miss"),
    ("FS-OA",  "Obi Agbim",        "Baylor"),
    ("FS-RC",  "Ryan Conwell",     "Louisville"),
    ("FS-SA",  "Shon Abaev",       "Cincinnati"),
    ("FS-SB",  "Sienna Betts",     "UCLA"),
    ("FS-SH",  "Shelton Henderson","Miami"),
    ("FS-TY",  "Tounde Yessoufou", "Baylor"),
]

BUZZ_FACTOR_AUTOS_RAW = [
    ("BZA-AC",  "Aaliyah Crump",       "Texas"),
    ("BZA-AM",  "Agot Makeer",         "University Of South Carolina"),
    ("BZA-BS",  "Braeden Shrewsberry", "Notre Dame"),
    ("BZA-CC",  "Coen Carr",           "Michigan State"),
    ("BZA-CM",  "Cotie McMahon",       "Ole Miss"),
    ("BZA-DA",  "Dwayne Aristode",     "Arizona"),
    ("BZA-DD",  "Derek Dixon",         "UNC"),
    ("BZA-DW",  "Darrion Williams",    "NC State"),
    ("BZA-HS",  "Hailee Swain",        "Stanford"),
    ("BZA-JL",  "Jaland Lowe",         "Kentucky"),
    ("BZA-KM",  "Kiyomi McMiller",     "Penn State"),
    ("BZA-KR",  "Kohl Rosario",        "Kansas"),
    ("BZA-KW",  "Kam Williams",        "Kentucky"),
    ("BZA-MA",  "Michael Rataj",       "Baylor"),
    ("BZA-MR",  "Malik Reneau",        "Miami"),
    ("BZA-OO",  "Otega Oweh",          "Kentucky"),
    ("BZA-RB",  "Reed Bailey",         "Indiana"),
    ("BZA-SD",  "Silas Demary Jr.",    "UConn"),
    ("BZA-SS",  "Sarah Strong",        "UConn"),
    ("BZA-SW",  "Serah Williams",      "UConn"),
    ("BZA-TD",  "Tre Donaldson",       "Miami"),
    ("BZA-TJ",  "Tylis Jordan",        "Ole Miss"),
    ("BZA-TK",  "Trey Kaufman-Renn",   "Purdue"),
    ("BZA-XL",  "Xaivian Lee",         "Florida"),
    ("BZA-ZE",  "Zuby Ejiofor",        "St. John's"),
]

OPENING_STATEMENT_SIGS_RAW = [
    ("OS-AB",  "Ace Bailey",           "Utah Jazz"),
    ("OS-AT",  "Alex Toohey",          "Golden State Warriors"),
    ("OS-BB",  "Brooks Barnhizer",     "Oklahoma City Thunder"),
    ("OS-CC",  "Cedric Coward",        "Memphis Grizzlies"),
    ("OS-CF",  "Cooper Flagg",         "Dallas Mavericks"),
    ("OS-CMB", "Collin Murray-Boyles", "Toronto Raptors"),
    ("OS-DH",  "Dylan Harper",         "San Antonio Spurs"),
    ("OS-DQ",  "Derik Queen",          "New Orleans Pelicans"),
    ("OS-ED",  "Egor Dëmin",           "Brooklyn Nets"),
    ("OS-JM",  "Jahmai Mashack",       "Memphis Grizzlies"),
    ("OS-JS",  "Javon Small",          "Memphis Grizzlies"),
    ("OS-JT",  "John Tonje",           "Utah Jazz"),
    ("OS-JW",  "Jamir Watkins",        "Washington Wizards"),
    ("OS-KK",  "Kon Knueppel",         "Charlotte Hornets"),
    ("OS-KM",  "Khaman Maluach",       "Phoenix Suns"),
    ("OS-KS",  "Kobe Sanders",         "Los Angeles Clippers"),
    ("OS-LO",  "Lachlan Olbrich",      "Chicago Bulls"),
    ("OS-MR",  "Maxime Raynaud",       "Sacramento Kings"),
    ("OS-MS",  "Max Shulga",           "Boston Celtics"),
    ("OS-NE",  "Noa Essengue",         "Chicago Bulls"),
    ("OS-NP",  "Noah Penda",           "Orlando Magic"),
    ("OS-TE",  "Taelon Peter",         "Indiana Pacers"),
    ("OS-TP",  "Tyrese Proctor",       "Cleveland Cavaliers"),
    ("OS-WR",  "Will Richard",         "Golden State Warriors"),
    ("OS-YH",  "Yang Hansen",          "Portland Trail Blazers"),
]

TIMELESS_TOUCH_SIGS_RAW = [
    ("TTA-AB", "Anthony Black",        "Orlando Magic",             False),
    ("TTA-AS", "Alex Sarr",            "Washington Wizards",        False),
    ("TTA-BM", "Brandon Miller",       "Charlotte Hornets",         False),
    ("TTA-CC", "Cade Cunningham",      "Detroit Pistons",           False),
    ("TTA-CH", "Cam Whitmore",         "Houston Rockets",           False),
    ("TTA-CL", "Cason Wallace",        "Oklahoma City Thunder",     False),
    ("TTA-CW", "Cody Williams",        "Utah Jazz",                 False),
    ("TTA-DC", "Moses Moody",          "Golden State Warriors",     False),
    ("TTA-DD", "Dyson Daniels",        "Atlanta Hawks",             False),
    ("TTA-DT", "Dalen Terry",          "Chicago Bulls",             False),
    ("TTA-GD", "Gradey Dick",          "Toronto Raptors",           False),
    ("TTA-HT", "Tyrese Haliburton",    "Indiana Pacers",            False),
    ("TTA-IH", "Isaiah Hartenstein",   "Oklahoma City Thunder",     False),
    ("TTA-JH", "Jordan Hawkins",       "New Orleans Pelicans",      False),
    ("TTA-JI", "Jalen Williams",       "Oklahoma City Thunder",     False),
    ("TTA-JW", "Jarace Walker",        "Indiana Pacers",            False),
    ("TTA-OI", "Oso Ighodaro",         "Phoenix Suns",              False),
    ("TTA-RD", "Ryan Dunn",            "Phoenix Suns",              False),
    ("TTA-RG", "Rudy Gobert",          "Minnesota Timberwolves",    False),
    ("TTA-SH", "Scoot Henderson",      "Portland Trail Blazers",    False),
    ("TTA-TH", "Taylor Hendricks",     "Utah Jazz",                 False),
    ("TTA-TS", "Tyler Smith",          "Milwaukee Bucks",           False),
    ("TTA-VW", "Victor Wembanyama",    "San Antonio Spurs",         False),
    ("TTA-ZE", "Zach Edey",            "Memphis Grizzlies",         False),
    ("TTA-ZR", "Zaccharie Risacher",   "Atlanta Hawks",             False),
]

PAPER_PROSPECT_RETAIL_AUTOS_RAW = [
    ("PA-AC",  "Aaliyah Crump",       "Texas"),
    ("PA-AD",  "Addison Deal",        "Iowa"),
    ("PA-AE",  "Alexandra Eschmeyer", "Stanford"),
    ("PA-AF",  "Ace Flagg",           "Maine"),
    ("PA-AL",  "Acaden Lewis",        "Villanova"),
    ("PA-AM",  "Aliyahna Morris",     "California"),
    ("PA-AW",  "Ayla McDowell",       "University Of South Carolina"),
    ("PA-AY",  "AJ Dybantsa",         "BYU"),
    ("PA-BB",  "Brayden Burries",     "Arizona"),
    ("PA-BG",  "Brandon Garrison",    "Kentucky"),
    ("PA-BI",  "Boopie Miller",       "SMU"),
    ("PA-BL",  "Bryce Lindsay",       "Villanova"),
    ("PA-BM",  "Brynn McGaughy",      "Washington"),
    ("PA-BR",  "Braden Smith",        "Purdue"),
    ("PA-BS",  "Braeden Shrewsberry", "Notre Dame"),
    ("PA-BT",  "Bennett Stirtz",      "Iowa"),
    ("PA-CA",  "Christian Anderson",  "Texas Tech"),
    ("PA-CC",  "Coen Carr",           "Michigan State"),
    ("PA-CF",  "Caleb Foster",        "Duke"),
    ("PA-CI",  "CJ Ingram",           "Florida"),
    ("PA-CL",  "Caleb Wilson",        "UNC"),
    ("PA-CM",  "Cotie McMahon",       "Ole Miss"),
    ("PA-CR",  "Chase Ross",          "Marquette"),
    ("PA-CW",  "Cam Ward",            "Michigan State"),
    ("PA-DA",  "Darianna Alexander",  "Cincinnati"),
    ("PA-DD",  "Derek Dixon",         "UNC"),
    ("PA-DE",  "Darryn Peterson",     "Kansas"),
    ("PA-DF",  "Davis Fogle",         "Gonzaga"),
    ("PA-DH",  "Davion Hannah",       "Alabama"),
    ("PA-DHJ", "Donald Hand Jr.",     "Boston College"),
    ("PA-DM",  "Devin McGlockton",    "Vanderbilt"),
    ("PA-DP",  "Deniya Prawl",        "Tennessee"),
    ("PA-DW",  "Darrion Williams",    "NC State"),
    ("PA-ES",  "Emilee Skinner",      "Duke"),
    ("PA-GK",  "Grace Knox",          "LSU"),
    ("PA-HS",  "Hailee Swain",        "Stanford"),
    ("PA-ID",  "Isaiah Denis",        "UNC"),
    ("PA-JB",  "John Blackwell",      "Wisconsin"),
    ("PA-JC",  "Jaida Civil",         "Tennessee"),
    ("PA-JD",  "Josh Dix",            "Creighton"),
    ("PA-JE",  "Jason Edwards",       "Providence"),
    ("PA-JG",  "Joe Grahovac",        "St. Bonaventure"),
    ("PA-JJ",  "Jamier Jones",        "Providence"),
    ("PA-JK",  "Ja'Kobi Gillespie",   "Tennessee"),
    ("PA-JL",  "Jaland Lowe",         "Kentucky"),
    ("PA-JT",  "JT Toppin",           "Texas Tech"),
    ("PA-JU",  "Juju Watkins",        "USC"),
    ("PA-JW",  "Jeremiah Wilkinson",  "Georgia"),
    ("PA-KC",  "Kaelyn Carroll",      "Kentucky"),
    ("PA-KD",  "Kara Dunn",           "USC"),
    ("PA-KF",  "Kelis Fisher",        "UConn"),
    ("PA-KH",  "Keyshawn Hall",       "Auburn"),
    ("PA-KM",  "Kiyomi McMiller",     "Penn State"),
    ("PA-KR",  "Kohl Rosario",        "Kansas"),
    ("PA-KS",  "Kaylene Smikle",      "Maryland"),
    ("PA-LM",  "Leah Macy",           "Notre Dame"),
    ("PA-LS",  "Lara Somfai",         "Stanford"),
    ("PA-MA",  "Michael Rataj",       "Baylor"),
    ("PA-MB",  "Madison Booker",      "Texas"),
    ("PA-MBJ", "Mikel Brown Jr.",     "Louisville"),
    ("PA-MK",  "Agot Makeer",         "University Of South Carolina"),
    ("PA-MR",  "Kam Williams",        "Kentucky"),
    ("PA-MU",  "Milos Uzan",          "Houston"),
    ("PA-NB",  "Niko Bundalo",        "Ole Miss"),
    ("PA-NC",  "Nate Calmese",        "Wake Forest"),
    ("PA-NI",  "Nate Bittle",         "Oregon"),
    ("PA-NM",  "Nick Martinelli",     "Northwestern"),
    ("PA-NR",  "Nyla Brooks",         "UNC"),
    ("PA-OA",  "Obi Agbim",           "Baylor"),
    ("PA-OO",  "Otega Oweh",          "Kentucky"),
    ("PA-OR",  "Owen Freeman",        "Creighton"),
    ("PA-OS",  "Oziyah Sellers",      "St. John's"),
    ("PA-PP",  "Pharrel Payne",       "Maryland"),
    ("PA-RB",  "Reed Bailey",         "Indiana"),
    ("PA-RC",  "Ryan Conwell",        "Louisville"),
    ("PA-RE",  "Raegan Beers",        "The University of Oklahoma"),
    ("PA-RM",  "Tre Donaldson",       "Miami"),
    ("PA-RS",  "Richie Saunders",     "BYU"),
    ("PA-SA",  "Shon Abaev",          "Cincinnati"),
    ("PA-SB",  "Sienna Betts",        "UCLA"),
    ("PA-SD",  "Silas Demary Jr.",    "UConn"),
    ("PA-SH",  "Sadiq White",         "Syracuse"),
    ("PA-SI",  "Sebastian Wilkins",   "Duke"),
    ("PA-SS",  "Sarah Strong",        "UConn"),
    ("PA-SW",  "Serah Williams",      "UConn"),
    ("PA-TA",  "Tobe Awaka",          "Arizona"),
    ("PA-TD",  "Malik Reneau",        "Miami"),
    ("PA-TH",  "Tre Holloman",        "NC State"),
    ("PA-TJ",  "Robert McCray V",     "Florida State"),
    ("PA-TKR", "Trey Kaufman-Renn",   "Purdue"),
    ("PA-TL",  "Ta'Niya Latson",      "University Of South Carolina"),
    ("PA-TO",  "Tylis Jordan",        "Ole Miss"),
    ("PA-TR",  "Tarris Reed Jr.",     "UConn"),
    ("PA-TY",  "Tounde Yessoufou",    "Baylor"),
    ("PA-WG",  "Winters Grady",       "Michigan"),
    ("PA-WY",  "Wesley Yates III",    "Washington"),
    ("PA-XL",  "Xaivian Lee",         "Florida"),
    ("PA-YG",  "Yarden Garzon",       "Maryland"),
    ("PA-ZE",  "Zuby Ejiofor",        "St. John's"),
    ("PA-ZJ",  "ZaKiyah Johnson",     "LSU"),
]

PAPER_RV_RETAIL_AUTOS_RAW = [
    ("RVA-AB",  "Ace Bailey",              "Utah Jazz",                 True),
    ("RVA-AH",  "Al Horford",              "Boston Celtics",            False),
    ("RVA-AL",  "Anthony Black",           "Orlando Magic",             False),
    ("RVA-AM",  "Alijah Martin",           "Toronto Raptors",           True),
    ("RVA-AN",  "Asa Newell",              "Atlanta Hawks",             True),
    ("RVA-AO",  "Alex Toohey",             "Golden State Warriors",     True),
    ("RVA-AT",  "Adou Thiero",             "Los Angeles Lakers",        True),
    ("RVA-BB",  "Brooks Barnhizer",        "Oklahoma City Thunder",     True),
    ("RVA-BC",  "Brandon Clarke",          "Memphis Grizzlies",         False),
    ("RVA-BS",  "Ben Saraf",               "Brooklyn Nets",             True),
    ("RVA-BSC", "Baylor Scheierman",       "Boston Celtics",            False),
    ("RVA-CC",  "Cedric Coward",           "Memphis Grizzlies",         True),
    ("RVA-CF",  "Cooper Flagg",            "Dallas Mavericks",          True),
    ("RVA-CH",  "Chet Holmgren",           "Oklahoma City Thunder",     False),
    ("RVA-CL",  "Chaz Lanier",             "Detroit Pistons",           True),
    ("RVA-CMB", "Collin Murray-Boyles",    "Toronto Raptors",           True),
    ("RVA-CW",  "Cody Williams",           "Utah Jazz",                 False),
    ("RVA-CWA", "Cason Wallace",           "Oklahoma City Thunder",     False),
    ("RVA-CWH", "Cam Whitmore",            "Houston Rockets",           False),
    ("RVA-DA",  "Deandre Ayton",           "Portland Trail Blazers",    False),
    ("RVA-DC",  "Devin Carter",            "Sacramento Kings",          False),
    ("RVA-DH",  "Dylan Harper",            "San Antonio Spurs",         True),
    ("RVA-DJ",  "Dillon Jones",            "Oklahoma City Thunder",     False),
    ("RVA-DP",  "Drake Powell",            "Brooklyn Nets",             True),
    ("RVA-DQ",  "Derik Queen",             "New Orleans Pelicans",      True),
    ("RVA-DT",  "Derrick White",           "Boston Celtics",            False),
    ("RVA-DW",  "Danny Wolf",              "Brooklyn Nets",             True),
    ("RVA-ED",  "Egor Dëmin",              "Brooklyn Nets",             True),
    ("RVA-FW",  "Franz Wagner",            "Orlando Magic",             False),
    ("RVA-GD",  "Gradey Dick",             "Toronto Raptors",           False),
    ("RVA-IC",  "Isaiah Collier",          "Utah Jazz",                 False),
    ("RVA-JA",  "Jarrett Allen",           "Cleveland Cavaliers",       False),
    ("RVA-JB",  "Johni Broome",            "Philadelphia 76ers",        True),
    ("RVA-JBE", "Joan Beringer",           "Minnesota Timberwolves",    True),
    ("RVA-JBR", "Jalen Brunson",           "New York Knicks",           False),
    ("RVA-JC",  "Jeremy Sochan",           "San Antonio Spurs",         False),
    ("RVA-JD",  "Jett Howard",             "Orlando Magic",             False),
    ("RVA-JF",  "Johnny Furphy",           "Indiana Pacers",            False),
    ("RVA-JH",  "Jrue Holiday",            "Boston Celtics",            False),
    ("RVA-JHS", "Jaime Jaquez Jr.",        "Miami Heat",                False),
    ("RVA-JI",  "Jalen Williams",          "Oklahoma City Thunder",     False),
    ("RVA-JK",  "Jarace Walker",           "Indiana Pacers",            False),
    ("RVA-JL",  "Jaylin Williams",         "Oklahoma City Thunder",     False),
    ("RVA-JM",  "Jahmai Mashack",          "Memphis Grizzlies",         True),
    ("RVA-JN",  "James Harden",            "Los Angeles Clippers",      False),
    ("RVA-JR",  "Jase Richardson",         "Orlando Magic",             True),
    ("RVA-JS",  "Javon Small",             "Memphis Grizzlies",         True),
    ("RVA-JT",  "John Tonje",              "Utah Jazz",                 True),
    ("RVA-JU",  "Jamal Murray",            "Denver Nuggets",            False),
    ("RVA-JW",  "Jamir Watkins",           "Washington Wizards",        True),
    ("RVA-KB",  "Koby Brea",               "Phoenix Suns",              True),
    ("RVA-KF",  "Kyle Filipowski",         "Utah Jazz",                 False),
    ("RVA-KJ",  "Kasparas Jakučionis",     "Miami Heat",                True),
    ("RVA-KK",  "Kon Knueppel",            "Charlotte Hornets",         True),
    ("RVA-KM",  "Khaman Maluach",          "Phoenix Suns",              True),
    ("RVA-KO",  "Kam Jones",               "Indiana Pacers",            True),
    ("RVA-KS",  "Kobe Sanders",            "Los Angeles Clippers",      True),
    ("RVA-KW",  "Kel'el Ware",             "Miami Heat",                False),
    ("RVA-LM",  "Liam McNeeley",           "Charlotte Hornets",         True),
    ("RVA-LO",  "Lachlan Olbrich",         "Chicago Bulls",             True),
    ("RVA-MM",  "Miles McBride",           "New York Knicks",           False),
    ("RVA-MP",  "Micah Peavy",             "New Orleans Pelicans",      True),
    ("RVA-MR",  "Maxime Raynaud",          "Sacramento Kings",          True),
    ("RVA-MS",  "Max Shulga",              "Boston Celtics",            True),
    ("RVA-NC",  "Nique Clifford",          "Sacramento Kings",          True),
    ("RVA-NE",  "Noa Essengue",            "Chicago Bulls",             True),
    ("RVA-NJ",  "Nikola Jović",            "Miami Heat",                False),
    ("RVA-NP",  "Noah Penda",              "Orlando Magic",             True),
    ("RVA-NT",  "Nolan Traore",            "Brooklyn Nets",             True),
    ("RVA-PB",  "Paolo Banchero",          "Orlando Magic",             False),
    ("RVA-PD",  "Pacôme Dadiet",           "New York Knicks",           False),
    ("RVA-QP",  "Quinten Post",            "Golden State Warriors",     False),
    ("RVA-RD",  "Ryan Dunn",               "Phoenix Suns",              False),
    ("RVA-RF",  "Rasheer Fleming",         "Phoenix Suns",              True),
    ("RVA-RH",  "Ron Holland II",          "Detroit Pistons",           False),
    ("RVA-RI",  "Rob Dillingham",          "Minnesota Timberwolves",    False),
    ("RVA-RK",  "Ryan Kalkbrenner",        "Charlotte Hornets",         True),
    ("RVA-RO",  "Royce O'Neale",           "Phoenix Suns",              False),
    ("RVA-SC",  "Stephon Castle",          "San Antonio Spurs",         False),
    ("RVA-SH",  "Scoot Henderson",         "Portland Trail Blazers",    False),
    ("RVA-SJ",  "Sion James",              "Charlotte Hornets",         True),
    ("RVA-TA",  "Tidjane Salaün",          "Charlotte Hornets",         False),
    ("RVA-TD",  "Tristan da Silva",        "Orlando Magic",             False),
    ("RVA-TE",  "Taelon Peter",            "Indiana Pacers",            True),
    ("RVA-TH",  "Taylor Hendricks",        "Utah Jazz",                 False),
    ("RVA-TI",  "Tyler Smith",             "Milwaukee Bucks",           False),
    ("RVA-TK",  "Tyler Kolek",             "New York Knicks",           False),
    ("RVA-TM",  "Terance Mann",            "Atlanta Hawks",             False),
    ("RVA-TP",  "Tyrese Proctor",          "Cleveland Cavaliers",       True),
    ("RVA-TS",  "Thomas Sorber",           "Oklahoma City Thunder",     True),
    ("RVA-WC",  "Walter Clayton Jr.",      "Utah Jazz",                 True),
    ("RVA-WI",  "Will Richard",            "Golden State Warriors",     True),
    ("RVA-WR",  "Will Riley",              "Washington Wizards",        True),
    ("RVA-XT",  "Xavier Tillman Sr.",      "Boston Celtics",            False),
    ("RVA-YH",  "Yang Hansen",             "Portland Trail Blazers",    True),
    ("RVA-YK",  "Yanic Konan-Niederhäuser","Los Angeles Clippers",      True),
    ("RVA-YM",  "Yves Missi",              "New Orleans Pelicans",      False),
    ("RVA-ZE",  "Zach Edey",               "Memphis Grizzlies",         False),
    ("RVA-ZR",  "Zaccharie Risacher",      "Atlanta Hawks",             False),
]

# Dual autographs: (card_number, player1, team1, player2, team2)
BOWMAN_DUAL_AUTOS_RAW = [
    ("BDA-AC",   "Grace Knox",     "LSU",                       "Aaliyah Crump",  "Texas"),
    ("BDA-AD",   "Darryn Peterson","Kansas",                    "AJ Dybantsa",    "BYU"),
    ("BDA-AY",   "AJ Dybantsa",    "BYU",                       "Sienna Betts",   "UCLA"),
    ("BDA-CW",   "Caleb Wilson",   "UNC",                       "AJ Dybantsa",    "BYU"),
    ("BDA-DP",   "Nate Ament",     "Tennessee",                 "Darryn Peterson","Kansas"),
    ("BDA-JD",   "Darryn Peterson","Kansas",                    "Juju Watkins",   "USC"),
    ("BDA-JW",   "Sienna Betts",   "UCLA",                      "Juju Watkins",   "USC"),
    ("BDA-KA",   "Kiyan Anthony",  "Syracuse",                  "Nate Ament",     "Tennessee"),
    ("BDA-SB",   "Emilee Skinner", "Duke",                      "Sienna Betts",   "UCLA"),
    ("BDPA-ST",  "Raegan Beers",   "The University of Oklahoma","Sarah Strong",   "UConn"),
]

TALENT_TRACKER_RAW = [
    ("TT-1",  "AJ Dybantsa",    "BYU"),
    ("TT-2",  "Darryn Peterson","Kansas"),
    ("TT-3",  "Koa Peat",       "Arizona"),
    ("TT-4",  "Emilee Skinner", "Duke"),
    ("TT-5",  "Sarah Strong",   "UConn"),
    ("TT-6",  "Sienna Betts",   "UCLA"),
    ("TT-7",  "Raegan Beers",   "The University of Oklahoma"),
    ("TT-8",  "Juju Watkins",   "USC"),
    ("TT-9",  "Caleb Wilson",   "UNC"),
    ("TT-10", "Nate Ament",     "Tennessee"),
    ("TT-11", "Mikel Brown Jr.","Louisville"),
    ("TT-12", "Aaliyah Crump",  "Texas"),
    ("TT-13", "Hailee Swain",   "Stanford"),
    ("TT-14", "Bennett Stirtz", "Iowa"),
    ("TT-15", "Otega Oweh",     "Kentucky"),
    ("TT-16", "Caleb Foster",   "Duke"),
    ("TT-17", "ZaKiyah Johnson","LSU"),
    ("TT-18", "Leah Macy",      "Notre Dame"),
    ("TT-19", "Richie Saunders","BYU"),
    ("TT-20", "Kohl Rosario",   "Kansas"),
    ("TT-21", "JT Toppin",      "Texas Tech"),
    ("TT-22", "Braden Smith",   "Purdue"),
    ("TT-23", "Jaida Civil",    "Tennessee"),
    ("TT-24", "Addison Deal",   "Iowa"),
    ("TT-25", "Milos Uzan",     "Houston"),
]

GEN_NEXT_RAW = [
    ("GN-1",  "AJ Dybantsa",       "BYU"),
    ("GN-2",  "Darryn Peterson",   "Kansas"),
    ("GN-3",  "Koa Peat",          "Arizona"),
    ("GN-4",  "Emilee Skinner",    "Duke"),
    ("GN-5",  "Sarah Strong",      "UConn"),
    ("GN-6",  "Sienna Betts",      "UCLA"),
    ("GN-7",  "Raegan Beers",      "The University of Oklahoma"),
    ("GN-8",  "Juju Watkins",      "USC"),
    ("GN-9",  "Caleb Wilson",      "UNC"),
    ("GN-10", "Nate Ament",        "Tennessee"),
    ("GN-11", "Mikel Brown Jr.",   "Louisville"),
    ("GN-12", "Aaliyah Crump",     "Texas"),
    ("GN-13", "Sebastian Wilkins", "Duke"),
    ("GN-14", "JT Toppin",         "Texas Tech"),
    ("GN-15", "Braden Smith",      "Purdue"),
    ("GN-16", "Ta'Niya Latson",    "University Of South Carolina"),
    ("GN-17", "Zuby Ejiofor",      "St. John's"),
    ("GN-18", "Davis Fogle",       "Gonzaga"),
    ("GN-19", "Grace Knox",        "LSU"),
    ("GN-20", "Madison Booker",    "Texas"),
    ("GN-21", "Nate Calmese",      "Wake Forest"),
    ("GN-22", "Tobe Awaka",        "Arizona"),
    ("GN-23", "Richie Saunders",   "BYU"),
    ("GN-24", "Winters Grady",     "Michigan"),
    ("GN-25", "Deniya Prawl",      "Tennessee"),
]

VIP_RAW = [
    ("VIP-1",  "AJ Dybantsa",         "BYU"),
    ("VIP-2",  "Darryn Peterson",     "Kansas"),
    ("VIP-3",  "Koa Peat",            "Arizona"),
    ("VIP-4",  "Emilee Skinner",      "Duke"),
    ("VIP-5",  "Sarah Strong",        "UConn"),
    ("VIP-6",  "Sienna Betts",        "UCLA"),
    ("VIP-7",  "Raegan Beers",        "The University of Oklahoma"),
    ("VIP-8",  "Juju Watkins",        "USC"),
    ("VIP-9",  "Caleb Wilson",        "UNC"),
    ("VIP-10", "Nate Ament",          "Tennessee"),
    ("VIP-11", "Mikel Brown Jr.",     "Louisville"),
    ("VIP-12", "Aaliyah Crump",       "Texas"),
    ("VIP-13", "Kara Dunn",           "USC"),
    ("VIP-14", "Boopie Miller",       "SMU"),
    ("VIP-15", "ZaKiyah Johnson",     "LSU"),
    ("VIP-16", "Jaida Civil",         "Tennessee"),
    ("VIP-17", "Alexandra Eschmeyer", "Stanford"),
    ("VIP-18", "Aliyahna Morris",     "California"),
    ("VIP-19", "Tounde Yessoufou",    "Baylor"),
    ("VIP-20", "Brynn McGaughy",      "Washington"),
    ("VIP-21", "Obi Agbim",           "Baylor"),
    ("VIP-22", "Ta'Niya Latson",      "University Of South Carolina"),
    ("VIP-23", "Trey Kaufman-Renn",   "Purdue"),
    ("VIP-24", "Zuby Ejiofor",        "St. John's"),
    ("VIP-25", "Joe Grahovac",        "St. Bonaventure"),
]

BOWMAN_VERIFIED_RAW = [
    ("BV-1",  "AJ Dybantsa",         "BYU"),
    ("BV-2",  "Darryn Peterson",     "Kansas"),
    ("BV-3",  "Koa Peat",            "Arizona"),
    ("BV-4",  "Emilee Skinner",      "Duke"),
    ("BV-5",  "Sarah Strong",        "UConn"),
    ("BV-6",  "Sienna Betts",        "UCLA"),
    ("BV-7",  "Raegan Beers",        "The University of Oklahoma"),
    ("BV-8",  "Juju Watkins",        "USC"),
    ("BV-9",  "Caleb Wilson",        "UNC"),
    ("BV-10", "Nate Ament",          "Tennessee"),
    ("BV-11", "Mikel Brown Jr.",     "Louisville"),
    ("BV-12", "Aaliyah Crump",       "Texas"),
    ("BV-13", "Ryan Conwell",        "Louisville"),
    ("BV-14", "Kam Williams",        "Kentucky"),
    ("BV-15", "JT Toppin",           "Texas Tech"),
    ("BV-16", "Braden Smith",        "Purdue"),
    ("BV-17", "Kohl Rosario",        "Kansas"),
    ("BV-18", "Ta'Niya Latson",      "University Of South Carolina"),
    ("BV-19", "Oziyah Sellers",      "St. John's"),
    ("BV-20", "Ayla McDowell",       "University Of South Carolina"),
    ("BV-21", "ZaKiyah Johnson",     "LSU"),
    ("BV-22", "Jaida Civil",         "Tennessee"),
    ("BV-23", "Alexandra Eschmeyer", "Stanford"),
    ("BV-24", "Bryce Lindsay",       "Villanova"),
    ("BV-25", "Cam Ward",            "Michigan State"),
]

ROY_FAVORITES_RAW = [
    ("RY-1",  "Cooper Flagg",          "Dallas Mavericks"),
    ("RY-2",  "Dylan Harper",          "San Antonio Spurs"),
    ("RY-3",  "VJ Edgecombe",          "Philadelphia 76ers"),
    ("RY-4",  "Kon Knueppel",          "Charlotte Hornets"),
    ("RY-5",  "Ace Bailey",            "Utah Jazz"),
    ("RY-6",  "Tre Johnson III",       "Washington Wizards"),
    ("RY-7",  "Jeremiah Fears",        "New Orleans Pelicans"),
    ("RY-8",  "Egor Dëmin",            "Brooklyn Nets"),
    ("RY-9",  "Collin Murray-Boyles",  "Toronto Raptors"),
    ("RY-10", "Khaman Maluach",        "Phoenix Suns"),
    ("RY-11", "Cedric Coward",         "Memphis Grizzlies"),
    ("RY-12", "Kasparas Jakučionis",   "Miami Heat"),
    ("RY-13", "Derik Queen",           "New Orleans Pelicans"),
    ("RY-14", "Carter Bryant",         "San Antonio Spurs"),
    ("RY-15", "Yang Hansen",           "Portland Trail Blazers"),
]

HOBBY_STARS_RAW = [
    ("HS-1",  "Paolo Banchero",        "Orlando Magic",          False),
    ("HS-2",  "Stephen Curry",         "Golden State Warriors",  False),
    ("HS-3",  "Cooper Flagg",          "Dallas Mavericks",       True),
    ("HS-4",  "Dylan Harper",          "San Antonio Spurs",      True),
    ("HS-5",  "Donovan Mitchell",      "Cleveland Cavaliers",    False),
    ("HS-6",  "Tyrese Haliburton",     "Indiana Pacers",         False),
    ("HS-7",  "Kon Knueppel",          "Charlotte Hornets",      True),
    ("HS-8",  "VJ Edgecombe",          "Philadelphia 76ers",     True),
    ("HS-9",  "Ace Bailey",            "Utah Jazz",              True),
    ("HS-10", "Jayson Tatum",          "Boston Celtics",         False),
    ("HS-11", "Jalen Brunson",         "New York Knicks",        False),
    ("HS-12", "Kevin Durant",          "Houston Rockets",        False),
    ("HS-13", "LeBron James",          "Los Angeles Lakers",     False),
    ("HS-14", "Anthony Edwards",       "Minnesota Timberwolves", False),
    ("HS-15", "Victor Wembanyama",     "San Antonio Spurs",      False),
]

YOUNG_KINGS_RAW = [
    ("YK-1",  "Shai Gilgeous-Alexander","Los Angeles Clippers",  False),
    ("YK-2",  "Luka Dončić",            "Dallas Mavericks",      False),
    ("YK-3",  "Tyrese Haliburton",      "Sacramento Kings",      False),
    ("YK-4",  "Stephen Curry",          "Golden State Warriors", False),
    ("YK-5",  "LeBron James",           "Cleveland Cavaliers",   False),
    ("YK-6",  "Nikola Jokić",           "Denver Nuggets",        False),
    ("YK-7",  "Ja Morant",              "Memphis Grizzlies",     False),
    ("YK-8",  "Victor Wembanyama",      "San Antonio Spurs",     False),
    ("YK-9",  "James Harden",           "Oklahoma City Thunder", False),
    ("YK-10", "Kawhi Leonard",          "San Antonio Spurs",     False),
    ("YK-11", "Jimmy Butler III",       "Chicago Bulls",         False),
    ("YK-12", "Cade Cunningham",        "Detroit Pistons",       False),
    ("YK-13", "Devin Booker",           "Phoenix Suns",          False),
    ("YK-14", "Kevin Durant",           "Oklahoma City Thunder", False),
    ("YK-15", "Donovan Mitchell",       "Utah Jazz",             False),
    ("YK-16", "Allen Iverson",          "Philadelphia 76ers",    False),
    ("YK-17", "Larry Bird",             "Boston Celtics",        False),
    ("YK-18", "Magic Johnson",          "Los Angeles Lakers",    False),
    ("YK-19", "Shaquille O'Neal",       "Los Angeles Lakers",    False),
    ("YK-20", "Dirk Nowitzki",          "Dallas Mavericks",      False),
    ("YK-21", "Kevin Garnett",          "Minnesota Timberwolves",False),
    ("YK-22", "Carmelo Anthony",        "Denver Nuggets",        False),
    ("YK-23", "Dwyane Wade",            "Miami Heat",            False),
    ("YK-24", "Tracy McGrady",          "Toronto Raptors",       False),
    ("YK-25", "Ray Allen",              "Seattle Supersonics",   False),
]

ROCKSTAR_ROOKIES_RAW = [
    ("RR-1",  "Cooper Flagg",         "Dallas Mavericks"),
    ("RR-2",  "Dylan Harper",         "San Antonio Spurs"),
    ("RR-3",  "VJ Edgecombe",         "Philadelphia 76ers"),
    ("RR-4",  "Kon Knueppel",         "Charlotte Hornets"),
    ("RR-5",  "Ace Bailey",           "Utah Jazz"),
    ("RR-6",  "Tre Johnson III",      "Washington Wizards"),
    ("RR-7",  "Jeremiah Fears",       "New Orleans Pelicans"),
    ("RR-8",  "Egor Dëmin",           "Brooklyn Nets"),
    ("RR-9",  "Collin Murray-Boyles", "Toronto Raptors"),
    ("RR-10", "Khaman Maluach",       "Phoenix Suns"),
    ("RR-11", "Cedric Coward",        "Memphis Grizzlies"),
    ("RR-12", "Noa Essengue",         "Chicago Bulls"),
    ("RR-13", "Derik Queen",          "New Orleans Pelicans"),
    ("RR-14", "Carter Bryant",        "San Antonio Spurs"),
    ("RR-15", "Thomas Sorber",        "Oklahoma City Thunder"),
    ("RR-16", "Yang Hansen",          "Portland Trail Blazers"),
    ("RR-17", "Joan Beringer",        "Minnesota Timberwolves"),
    ("RR-18", "Walter Clayton Jr.",   "Utah Jazz"),
    ("RR-19", "Nolan Traore",         "Brooklyn Nets"),
    ("RR-20", "Kasparas Jakučionis",  "Miami Heat"),
]

GREATNESS_LOADING_RAW = [
    ("GL-1",  "Cooper Flagg",         "Dallas Mavericks"),
    ("GL-2",  "Dylan Harper",         "San Antonio Spurs"),
    ("GL-3",  "VJ Edgecombe",         "Philadelphia 76ers"),
    ("GL-4",  "Kon Knueppel",         "Charlotte Hornets"),
    ("GL-5",  "Ace Bailey",           "Utah Jazz"),
    ("GL-6",  "Tre Johnson III",      "Washington Wizards"),
    ("GL-7",  "Jeremiah Fears",       "New Orleans Pelicans"),
    ("GL-8",  "Egor Dëmin",           "Brooklyn Nets"),
    ("GL-9",  "Collin Murray-Boyles", "Toronto Raptors"),
    ("GL-10", "Khaman Maluach",       "Phoenix Suns"),
    ("GL-11", "Cedric Coward",        "Memphis Grizzlies"),
    ("GL-12", "Noa Essengue",         "Chicago Bulls"),
    ("GL-13", "Derik Queen",          "New Orleans Pelicans"),
    ("GL-14", "Carter Bryant",        "San Antonio Spurs"),
    ("GL-15", "Thomas Sorber",        "Oklahoma City Thunder"),
    ("GL-16", "Yang Hansen",          "Portland Trail Blazers"),
    ("GL-17", "Joan Beringer",        "Minnesota Timberwolves"),
    ("GL-18", "Walter Clayton Jr.",   "Utah Jazz"),
    ("GL-19", "Nolan Traore",         "Brooklyn Nets"),
    ("GL-20", "Kasparas Jakučionis",  "Miami Heat"),
    ("GL-21", "Will Riley",           "Washington Wizards"),
    ("GL-22", "Drake Powell",         "Brooklyn Nets"),
    ("GL-23", "Asa Newell",           "Atlanta Hawks"),
    ("GL-24", "Nique Clifford",       "Sacramento Kings"),
    ("GL-25", "Jase Richardson",      "Orlando Magic"),
]

MEGA_ROOKIES_RAW = [
    ("MR-1",  "Cooper Flagg",         "Dallas Mavericks"),
    ("MR-2",  "Dylan Harper",         "San Antonio Spurs"),
    ("MR-3",  "VJ Edgecombe",         "Philadelphia 76ers"),
    ("MR-4",  "Kon Knueppel",         "Charlotte Hornets"),
    ("MR-5",  "Ace Bailey",           "Utah Jazz"),
    ("MR-6",  "Tre Johnson III",      "Washington Wizards"),
    ("MR-7",  "Jeremiah Fears",       "New Orleans Pelicans"),
    ("MR-8",  "Egor Dëmin",           "Brooklyn Nets"),
    ("MR-9",  "Collin Murray-Boyles", "Toronto Raptors"),
    ("MR-10", "Khaman Maluach",       "Phoenix Suns"),
    ("MR-11", "Cedric Coward",        "Memphis Grizzlies"),
    ("MR-12", "Noa Essengue",         "Chicago Bulls"),
    ("MR-13", "Derik Queen",          "New Orleans Pelicans"),
    ("MR-14", "Carter Bryant",        "San Antonio Spurs"),
    ("MR-15", "Thomas Sorber",        "Oklahoma City Thunder"),
    ("MR-16", "Yang Hansen",          "Portland Trail Blazers"),
    ("MR-17", "Joan Beringer",        "Minnesota Timberwolves"),
    ("MR-18", "Walter Clayton Jr.",   "Utah Jazz"),
    ("MR-19", "Nolan Traore",         "Brooklyn Nets"),
    ("MR-20", "Kasparas Jakučionis",  "Miami Heat"),
    ("MR-21", "Will Riley",           "Washington Wizards"),
    ("MR-22", "Drake Powell",         "Brooklyn Nets"),
    ("MR-23", "Asa Newell",           "Atlanta Hawks"),
    ("MR-24", "Nique Clifford",       "Sacramento Kings"),
    ("MR-25", "Danny Wolf",           "Brooklyn Nets"),
]

MEGA_PROSPECTS_RAW = [
    ("MP-1",  "AJ Dybantsa",       "BYU"),
    ("MP-2",  "Darryn Peterson",   "Kansas"),
    ("MP-3",  "Koa Peat",          "Arizona"),
    ("MP-4",  "Emilee Skinner",    "Duke"),
    ("MP-5",  "Sarah Strong",      "UConn"),
    ("MP-6",  "Sienna Betts",      "UCLA"),
    ("MP-7",  "Raegan Beers",      "The University of Oklahoma"),
    ("MP-8",  "Juju Watkins",      "USC"),
    ("MP-9",  "Caleb Wilson",      "UNC"),
    ("MP-10", "Nate Ament",        "Tennessee"),
    ("MP-11", "Otega Oweh",        "Kentucky"),
    ("MP-12", "Sebastian Wilkins", "Duke"),
    ("MP-13", "Hailee Swain",      "Stanford"),
    ("MP-14", "Kaylene Smikle",    "Maryland"),
    ("MP-15", "Milos Uzan",        "Houston"),
    ("MP-16", "Sadiq White",       "Syracuse"),
    ("MP-17", "Tarris Reed Jr.",   "UConn"),
    ("MP-18", "Wesley Yates III",  "Washington"),
    ("MP-19", "Lara Somfai",       "Stanford"),
    ("MP-20", "Christian Anderson","Texas Tech"),
    ("MP-21", "Davion Hannah",     "Alabama"),
    ("MP-22", "Davis Fogle",       "Gonzaga"),
    ("MP-23", "Grace Knox",        "LSU"),
    ("MP-24", "Isaiah Denis",      "UNC"),
    ("MP-25", "Addison Deal",      "Iowa"),
]

BOWMAN_SPOTLIGHTS_NBA_RAW = [
    ("BNB-1",  "Cooper Flagg",        "Dallas Mavericks",        True),
    ("BNB-2",  "Dylan Harper",        "San Antonio Spurs",       True),
    ("BNB-3",  "VJ Edgecombe",        "Philadelphia 76ers",      True),
    ("BNB-4",  "Kon Knueppel",        "Charlotte Hornets",       True),
    ("BNB-5",  "Ace Bailey",          "Utah Jazz",               True),
    ("BNB-6",  "Tre Johnson III",     "Washington Wizards",      True),
    ("BNB-7",  "LeBron James",        "Los Angeles Lakers",      False),
    ("BNB-8",  "Anthony Edwards",     "Minnesota Timberwolves",  False),
    ("BNB-9",  "Victor Wembanyama",   "San Antonio Spurs",       False),
    ("BNB-10", "Stephen Curry",       "Golden State Warriors",   False),
]

BOWMAN_SPOTLIGHTS_NIL_RAW = [
    ("BNS-1", "AJ Dybantsa",    "BYU"),
    ("BNS-2", "Darryn Peterson","Kansas"),
    ("BNS-3", "Madison Booker", "Texas"),
    ("BNS-4", "Juju Watkins",   "USC"),
    ("BNS-5", "Nate Ament",     "Tennessee"),
]

CRYSTALLIZED_NBA_RAW = [
    ("CNB-1",  "Cooper Flagg",        "Dallas Mavericks",        True),
    ("CNB-2",  "Dylan Harper",        "San Antonio Spurs",       True),
    ("CNB-3",  "VJ Edgecombe",        "Philadelphia 76ers",      True),
    ("CNB-4",  "Kon Knueppel",        "Charlotte Hornets",       True),
    ("CNB-5",  "Ace Bailey",          "Utah Jazz",               True),
    ("CNB-6",  "Jayson Tatum",        "Boston Celtics",          False),
    ("CNB-7",  "Stephen Curry",       "Golden State Warriors",   False),
    ("CNB-8",  "Giannis Antetokounmpo","Milwaukee Bucks",        False),
    ("CNB-9",  "Anthony Edwards",     "Minnesota Timberwolves",  False),
    ("CNB-10", "Victor Wembanyama",   "San Antonio Spurs",       False),
]

CRYSTALLIZED_NIL_RAW = [
    ("CNL-1", "AJ Dybantsa",    "BYU"),
    ("CNL-2", "Darryn Peterson","Kansas"),
    ("CNL-3", "Sienna Betts",   "UCLA"),
    ("CNL-4", "Juju Watkins",   "USC"),
    ("CNL-5", "Nate Ament",     "Tennessee"),
]

ANIME_NBA_RAW = [
    ("NBA-A1",  "Jayson Tatum",            "Boston Celtics",          False),
    ("NBA-A2",  "Jalen Brunson",           "New York Knicks",         False),
    ("NBA-A3",  "Tyrese Maxey",            "Philadelphia 76ers",      False),
    ("NBA-A4",  "Cade Cunningham",         "Detroit Pistons",         False),
    ("NBA-A5",  "Tyrese Haliburton",       "Indiana Pacers",          False),
    ("NBA-A6",  "Giannis Antetokounmpo",   "Milwaukee Bucks",         False),
    ("NBA-A7",  "LaMelo Ball",             "Charlotte Hornets",       False),
    ("NBA-A8",  "Donovan Mitchell",        "Cleveland Cavaliers",     False),
    ("NBA-A9",  "Paolo Banchero",          "Orlando Magic",           False),
    ("NBA-A10", "Nikola Jokić",            "Denver Nuggets",          False),
    ("NBA-A11", "Anthony Edwards",         "Minnesota Timberwolves",  False),
    ("NBA-A12", "Shai Gilgeous-Alexander", "Oklahoma City Thunder",   False),
    ("NBA-A13", "Stephen Curry",           "Golden State Warriors",   False),
    ("NBA-A14", "Luka Dončić",             "Los Angeles Lakers",      False),
    ("NBA-A15", "LeBron James",            "Los Angeles Lakers",      False),
    ("NBA-A16", "Amen Thompson",           "Houston Rockets",         False),
    ("NBA-A17", "Victor Wembanyama",       "San Antonio Spurs",       False),
    ("NBA-A18", "Devin Booker",            "Phoenix Suns",            False),
    ("NBA-A19", "Cooper Flagg",            "Dallas Mavericks",        True),
    ("NBA-A20", "Dylan Harper",            "San Antonio Spurs",       True),
    ("NBA-A21", "VJ Edgecombe",            "Philadelphia 76ers",      True),
    ("NBA-A22", "Ace Bailey",              "Utah Jazz",               True),
    ("NBA-A23", "Jeremiah Fears",          "New Orleans Pelicans",    True),
    ("NBA-A24", "Kon Knueppel",            "Charlotte Hornets",       True),
    ("NBA-A25", "Tre Johnson III",         "Washington Wizards",      True),
]

ANIME_NIL_RAW = [
    ("NIL-A1", "AJ Dybantsa",    "BYU"),
    ("NIL-A2", "Darryn Peterson","Kansas"),
    ("NIL-A3", "Juju Watkins",   "USC"),
    ("NIL-A4", "Sienna Betts",   "UCLA"),
    ("NIL-A5", "Koa Peat",       "Arizona"),
]

BOWMAN_GPK_NBA_RAW = [
    ("BGP-1", "Cooper Flagg",      "Dallas Mavericks",        True),
    ("BGP-2", "Ace Bailey",        "Utah Jazz",               True),
    ("BGP-3", "Dylan Harper",      "San Antonio Spurs",       True),
    ("BGP-4", "Kon Knueppel",      "Charlotte Hornets",       True),
    ("BGP-5", "Anthony Edwards",   "Minnesota Timberwolves",  False),
]

BOWMAN_GPK_NIL_RAW = [
    ("BNIL-1", "Sienna Betts",   "UCLA"),
    ("BNIL-2", "Sarah Strong",   "UConn"),
    ("BNIL-3", "AJ Dybantsa",    "BYU"),
    ("BNIL-4", "Darryn Peterson","Kansas"),
]

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

def build():
    players = {}   # name → {is_rookie, appearances: [...]}
    sections = {}  # insert_set name → {parallels, cards}

    def add_card(insert_set, card_number, player, team, is_rookie, subset=None, co_players=None):
        if player not in players:
            players[player] = {"is_rookie": False, "appearances": []}
        if is_rookie:
            players[player]["is_rookie"] = True
        app = {
            "insert_set": insert_set,
            "card_number": card_number,
            "team": team,
            "is_rookie": is_rookie,
            "subset": subset,
        }
        if co_players:
            app["co_players"] = co_players
        players[player]["appearances"].append(app)
        if insert_set not in sections:
            sections[insert_set] = {"parallels": NO_PARALLELS, "cards": []}
        sections[insert_set]["cards"].append({
            "card_number": card_number,
            "player": player,
            "team": team,
            "is_rookie": is_rookie,
            "subset": subset,
        })

    # Base Set
    for num, player, team, is_rookie in BASE_SET_RAW:
        add_card("Base Set", num, player, team, is_rookie)

    # Base Chrome Variation (same players, BCV- prefix)
    for i, (_, player, team, is_rookie) in enumerate(BASE_SET_RAW, 1):
        add_card("Base Chrome Variation", f"BCV-{i}", player, team, is_rookie)

    # Red Rookie Variations
    for num, player, team in RED_ROOKIE_VARIATIONS_RAW:
        add_card("Red Rookie Variations", num, player, team, True)

    # Etched In Glass Variations
    for num, player, team, is_rookie in ETCHED_IN_GLASS_RAW:
        add_card("Etched In Glass Variations", num, player, team, is_rookie)

    # Retrofractor Variations
    for num, player, team, is_rookie in RETROFRACTOR_VARIATIONS_RAW:
        add_card("Retrofractor Variations", num, player, team, is_rookie)

    # Base Prospects
    for num, player, team in BASE_PROSPECTS_RAW:
        add_card("Base Prospects", num, player, team, False)

    # Chrome Prospects (same players, BCP- prefix)
    for i, (_, player, team) in enumerate(BASE_PROSPECTS_RAW, 1):
        add_card("Chrome Prospects", f"BCP-{i}", player, team, False)

    # Chrome Prospects Etched In Glass Variations
    for num, player, team in CHROME_PROSPECTS_EIG_RAW:
        add_card("Chrome Prospects Etched In Glass Variations", num, player, team, False)

    # Chrome Prospect Autographs
    for num, player, team in CHROME_PROSPECT_AUTOS_RAW:
        add_card("Chrome Prospect Autographs", num, player, team, False)

    # Chrome Autographs
    for num, player, team, is_rookie in CHROME_AUTOS_RAW:
        add_card("Chrome Autographs", num, player, team, is_rookie)

    # Retrofractor Autographs
    for num, player, team, is_rookie in RETROFRACTOR_AUTOS_RAW:
        add_card("Retrofractor Autographs", num, player, team, is_rookie)

    # Future Script Autographs
    for num, player, team in FUTURE_SCRIPT_AUTOS_RAW:
        add_card("Future Script Autographs", num, player, team, False)

    # Buzz Factor Autographs
    for num, player, team in BUZZ_FACTOR_AUTOS_RAW:
        add_card("Buzz Factor Autographs", num, player, team, False)

    # Opening Statement Signatures
    for num, player, team in OPENING_STATEMENT_SIGS_RAW:
        add_card("Opening Statement Signatures", num, player, team, True)

    # Timeless Touch Signatures
    for num, player, team, is_rookie in TIMELESS_TOUCH_SIGS_RAW:
        add_card("Timeless Touch Signatures", num, player, team, is_rookie)

    # Paper Prospect Retail Autographs
    for num, player, team in PAPER_PROSPECT_RETAIL_AUTOS_RAW:
        add_card("Paper Prospect Retail Autographs", num, player, team, False)

    # Paper Rookie and Veterans Retail Autographs
    for num, player, team, is_rookie in PAPER_RV_RETAIL_AUTOS_RAW:
        add_card("Paper Rookie and Veterans Retail Autographs", num, player, team, is_rookie)

    # Bowman Dual Autographs
    for num, p1, t1, p2, t2 in BOWMAN_DUAL_AUTOS_RAW:
        add_card("Bowman Dual Autographs", num, p1, t1, False, co_players=[p2])
        add_card("Bowman Dual Autographs", num, p2, t2, False, co_players=[p1])

    # Non-auto insert sets
    for num, player, team in TALENT_TRACKER_RAW:
        add_card("Talent Tracker", num, player, team, False)
    for num, player, team in GEN_NEXT_RAW:
        add_card("Gen Next", num, player, team, False)
    for num, player, team in VIP_RAW:
        add_card("Very Important Prospects", num, player, team, False)
    for num, player, team in BOWMAN_VERIFIED_RAW:
        add_card("Bowman Verified", num, player, team, False)
    for num, player, team in ROY_FAVORITES_RAW:
        add_card("ROY Favorites", num, player, team, True)
    for num, player, team, is_rookie in HOBBY_STARS_RAW:
        add_card("Hobby Stars", num, player, team, is_rookie)
    for num, player, team, is_rookie in YOUNG_KINGS_RAW:
        add_card("Young Kings", num, player, team, is_rookie)
    for num, player, team in ROCKSTAR_ROOKIES_RAW:
        add_card("Rockstar Rookies", num, player, team, True)
    for num, player, team in GREATNESS_LOADING_RAW:
        add_card("Greatness Loading", num, player, team, True)
    for num, player, team in MEGA_ROOKIES_RAW:
        add_card("Mega Rookies", num, player, team, True)
    for num, player, team in MEGA_PROSPECTS_RAW:
        add_card("Mega Prospects", num, player, team, False)
    for num, player, team, is_rookie in BOWMAN_SPOTLIGHTS_NBA_RAW:
        add_card("Bowman Spotlights NBA", num, player, team, is_rookie)
    for num, player, team in BOWMAN_SPOTLIGHTS_NIL_RAW:
        add_card("Bowman Spotlights NIL", num, player, team, False)
    for num, player, team, is_rookie in CRYSTALLIZED_NBA_RAW:
        add_card("Crystallized NBA", num, player, team, is_rookie)
    for num, player, team in CRYSTALLIZED_NIL_RAW:
        add_card("Crystallized NIL", num, player, team, False)
    for num, player, team, is_rookie in ANIME_NBA_RAW:
        add_card("Anime NBA", num, player, team, is_rookie)
    for num, player, team in ANIME_NIL_RAW:
        add_card("Anime NIL", num, player, team, False)
    for num, player, team, is_rookie in BOWMAN_GPK_NBA_RAW:
        add_card("Bowman GPK NBA", num, player, team, is_rookie)
    for num, player, team in BOWMAN_GPK_NIL_RAW:
        add_card("Bowman GPK NIL", num, player, team, False)

    # Propagate is_rookie to all appearances
    rc_players = {p for p, d in players.items() if d["is_rookie"]}
    for p in rc_players:
        for app in players[p]["appearances"]:
            app["is_rookie"] = True
        for sec in sections.values():
            for card in sec["cards"]:
                if card["player"] == p:
                    card["is_rookie"] = True

    # Build sections list
    sections_list = []
    for insert_set, data in sections.items():
        sections_list.append({
            "insert_set": insert_set,
            "parallels": data["parallels"],
            "cards": data["cards"],
        })

    # Build players list with stats
    players_list = []
    for name, data in players.items():
        unique_cards = len(data["appearances"])
        players_list.append({
            "player": name,
            "appearances": data["appearances"],
            "stats": {
                "unique_cards": unique_cards,
                "total_print_run": 0,
                "one_of_ones": 0,
                "insert_sets": len({a["insert_set"] for a in data["appearances"]}),
            },
        })

    players_list.sort(key=lambda p: p["player"])

    output = {
        "set_name": "2025-26 Bowman Basketball",
        "sport": "Basketball",
        "season": "2025-26",
        "league": "NBA",
        "sections": sections_list,
        "players": players_list,
    }

    with open("bowman_basketball_2526_parsed.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    total_cards = sum(len(s["cards"]) for s in sections_list)
    print(f"Sections: {len(sections_list)}")
    print(f"Players:  {len(players_list)}")
    print(f"Cards:    {total_cards}")

if __name__ == "__main__":
    build()
