"""
Parser for 2025 Topps Museum Collection Baseball.

sport: Baseball, league: MLB, season: 2025, tier: Premium
No parallels in this checklist.
RC-tagged players: strip " RC" from name, set is_rookie=True.
Dual/Triple/Quad cards use co_players logic (same card_number in same insert_set).
"""

from __future__ import annotations
import json

SET_NAME = "2025 Topps Museum Collection Baseball"
SPORT = "Baseball"
SEASON = "2025"
LEAGUE = "MLB"

# ── Name normalization ────────────────────────────────────────────────────────

NAME_FIXES: dict[str, str] = {
    "elly de la cruz": "Elly De La Cruz",
}

TEAM_FIXES: dict[str, str] = {
    "Athletics™": "Oakland Athletics",
    "Athletics": "Oakland Athletics",
}


def fix_name(name: str) -> str:
    key = name.lower().strip()
    if key in NAME_FIXES:
        return NAME_FIXES[key]
    return name.strip()


def fix_team(team: str) -> str:
    t = team.strip()
    if t in TEAM_FIXES:
        return TEAM_FIXES[t]
    return t


def parse_rc(name: str) -> tuple[str, bool]:
    """Strip ' RC' suffix and return (clean_name, is_rookie)."""
    if name.endswith(" RC"):
        return name[:-3].strip(), True
    return name, False


# ── Card data ─────────────────────────────────────────────────────────────────

# Base Set (100 cards)
BASE_SET_RAW = [
    ("1", "Shohei Ohtani", "Los Angeles Dodgers"),
    ("2", "Nolan Ryan", "Texas Rangers"),
    ("3", "Luisangel Acuna", "New York Mets RC"),
    ("4", "Hank Aaron", "Atlanta Braves"),
    ("5", "Mike Schmidt", "Philadelphia Phillies"),
    ("6", "Randy Johnson", "Arizona Diamondbacks"),
    ("7", "Miguel Cabrera", "Detroit Tigers"),
    ("8", "Julio Rodriguez", "Seattle Mariners"),
    ("9", "Paul Skenes", "Pittsburgh Pirates"),
    ("10", "Will Clark", "San Francisco Giants"),
    ("11", "Pedro Martinez", "Boston Red Sox"),
    ("12", "Barry Bonds", "San Francisco Giants"),
    ("13", "Johnny Bench", "Cincinnati Reds"),
    ("14", "Vladimir Guerrero Jr.", "Toronto Blue Jays"),
    ("15", "Ryne Sandberg", "Chicago Cubs"),
    ("16", "Ted Williams", "Boston Red Sox"),
    ("17", "Mike Piazza", "New York Mets"),
    ("18", "Willie Mays", "San Francisco Giants"),
    ("19", "Greg Maddux", "Atlanta Braves"),
    ("20", "Tony Gwynn", "San Diego Padres"),
    ("21", "Kirby Puckett", "Minnesota Twins"),
    ("22", "Joe DiMaggio", "New York Yankees"),
    ("23", "Jose Altuve", "Houston Astros"),
    ("24", "Juan Soto", "New York Mets"),
    ("25", "Lawrence Butler", "Oakland Athletics"),
    ("26", "Ichiro", "Seattle Mariners"),
    ("27", "Bo Jackson", "Kansas City Royals"),
    ("28", "Bryce Harper", "Philadelphia Phillies"),
    ("29", "Stan Musial", "St. Louis Cardinals"),
    ("30", "Manny Machado", "San Diego Padres"),
    ("31", "Kevin Alcantara", "Chicago Cubs RC"),
    ("32", "Luke Keaschall", "Minnesota Twins RC"),
    ("33", "Ozzie Smith", "St. Louis Cardinals"),
    ("34", "Jose Ramirez", "Cleveland Guardians"),
    ("35", "Cam Smith", "Houston Astros RC"),
    ("36", "Sandy Koufax", "Los Angeles Dodgers"),
    ("37", "Fernando Tatis Jr.", "San Diego Padres"),
    ("38", "Elly De La Cruz", "Cincinnati Reds"),
    ("39", "Pete Alonso", "New York Mets"),
    ("40", "Cal Ripken Jr.", "Baltimore Orioles"),
    ("41", "Frank Thomas", "Chicago White Sox"),
    ("42", "Derek Jeter", "New York Yankees"),
    ("43", "Drake Baldwin", "Atlanta Braves RC"),
    ("44", "David Ortiz", "Boston Red Sox"),
    ("45", "Chipper Jones", "Atlanta Braves"),
    ("46", "Yadier Molina", "St. Louis Cardinals"),
    ("47", "Roberto Clemente", "Pittsburgh Pirates"),
    ("48", "Barry Larkin", "Cincinnati Reds"),
    ("49", "Rhett Lowder", "Cincinnati Reds RC"),
    ("50", "Kristian Campbell", "Boston Red Sox RC"),
    ("51", "Hideo Nomo", "Los Angeles Dodgers"),
    ("52", "Coby Mayo", "Baltimore Orioles RC"),
    ("53", "Yogi Berra", "New York Yankees"),
    ("54", "James Wood", "Washington Nationals RC"),
    ("55", "Ty Cobb", "Detroit Tigers"),
    ("56", "Robin Yount", "Milwaukee Brewers"),
    ("57", "Jackson Jobe", "Detroit Tigers RC"),
    ("58", "Brooks Lee", "Minnesota Twins RC"),
    ("59", "Clayton Kershaw", "Los Angeles Dodgers"),
    ("60", "Hyeseong Kim", "Los Angeles Dodgers RC"),
    ("61", "Roy Campanella", "Brooklyn Dodgers"),
    ("62", "Reggie Jackson", "Oakland Athletics"),
    ("63", "Mookie Betts", "Los Angeles Dodgers"),
    ("64", "Nick Kurtz", "Oakland Athletics RC"),
    ("65", "Bobby Witt Jr.", "Kansas City Royals"),
    ("66", "Freddie Freeman", "Los Angeles Dodgers"),
    ("67", "Dylan Crews", "Washington Nationals RC"),
    ("68", "Christian Yelich", "Milwaukee Brewers"),
    ("69", "Gunnar Henderson", "Baltimore Orioles"),
    ("70", "Rickey Henderson", "Oakland Athletics"),
    ("71", "Mickey Mantle", "New York Yankees"),
    ("72", "Babe Ruth", "New York Yankees"),
    ("73", "Joe Mauer", "Minnesota Twins"),
    ("74", "Corey Seager", "Texas Rangers"),
    ("75", "Roger Clemens", "Boston Red Sox"),
    ("76", "Sammy Sosa", "Chicago Cubs"),
    ("77", "Adrian Beltre", "Texas Rangers"),
    ("78", "Yordan Alvarez", "Houston Astros"),
    ("79", "Ronald Acuna Jr.", "Atlanta Braves"),
    ("80", "Pete Rose", "Cincinnati Reds"),
    ("81", "Jacob Wilson", "Oakland Athletics RC"),
    ("82", "Ernie Banks", "Chicago Cubs"),
    ("83", "Mark McGwire", "Oakland Athletics"),
    ("84", "Matt Shaw", "Chicago Cubs RC"),
    ("85", "Roger Maris", "New York Yankees"),
    ("86", "Buster Posey", "San Francisco Giants"),
    ("87", "Honus Wagner", "Pittsburgh Pirates"),
    ("88", "Roki Sasaki", "Los Angeles Dodgers RC"),
    ("89", "Dalton Rushing", "Los Angeles Dodgers RC"),
    ("90", "Lou Gehrig", "New York Yankees"),
    ("91", "Marcelo Mayer", "Boston Red Sox RC"),
    ("92", "Corbin Carroll", "Arizona Diamondbacks"),
    ("93", "Francisco Lindor", "New York Mets"),
    ("94", "Ken Griffey Jr.", "Seattle Mariners"),
    ("95", "Adley Rutschman", "Baltimore Orioles"),
    ("96", "Albert Pujols", "St. Louis Cardinals"),
    ("97", "Jackie Robinson", "Brooklyn Dodgers"),
    ("98", "George Brett", "Kansas City Royals"),
    ("99", "Aaron Judge", "New York Yankees"),
    ("100", "Mike Trout", "Angels"),
]

# Canvas Collection Original Player Autographs (49 cards)
CCOPA_RAW = [
    ("CCOPA-AR", "Adley Rutschman", "Baltimore Orioles"),
    ("CCOPA-AV", "Anthony Volpe", "New York Yankees"),
    ("CCOPA-BJ", "Bo Jackson", "Kansas City Royals"),
    ("CCOPA-BL", "Brooks Lee", "Minnesota Twins RC"),
    ("CCOPA-BW", "Bobby Witt Jr.", "Kansas City Royals"),
    ("CCOPA-CB", "Craig Biggio", "Houston Astros"),
    ("CCOPA-CC", "Corbin Carroll", "Arizona Diamondbacks"),
    ("CCOPA-CF", "Carlton Fisk", "Boston Red Sox"),
    ("CCOPA-CJ", "Chipper Jones", "Atlanta Braves"),
    ("CCOPA-CM", "Coby Mayo", "Baltimore Orioles RC"),
    ("CCOPA-CR", "Cal Ripken Jr.", "Baltimore Orioles"),
    ("CCOPA-DC", "Dylan Crews", "Washington Nationals RC"),
    ("CCOPA-DJ", "Derek Jeter", "New York Yankees"),
    ("CCOPA-DM", "Dale Murphy", "Atlanta Braves"),
    ("CCOPA-DMA", "Don Mattingly", "New York Yankees"),
    ("CCOPA-DW", "David Wright", "New York Mets"),
    ("CCOPA-FT", "Frank Thomas", "Chicago White Sox"),
    ("CCOPA-GB", "George Brett", "Kansas City Royals"),
    ("CCOPA-GH", "Gunnar Henderson", "Baltimore Orioles"),
    ("CCOPA-GM", "Greg Maddux", "Chicago Cubs"),
    ("CCOPA-JA", "Jose Altuve", "Houston Astros"),
    ("CCOPA-JM", "Jackson Merrill", "San Diego Padres"),
    ("CCOPA-JR", "Julio Rodriguez", "Seattle Mariners"),
    ("CCOPA-JS", "Juan Soto", "New York Mets"),
    ("CCOPA-JW", "James Wood", "Washington Nationals RC"),
    ("CCOPA-MC", "Matt Chapman", "San Francisco Giants"),
    ("CCOPA-MM", "Mark McGwire", "Oakland Athletics"),
    ("CCOPA-MMA", "Manny Machado", "San Diego Padres"),
    ("CCOPA-MO", "Matt Olson", "Atlanta Braves"),
    ("CCOPA-MR", "Mariano Rivera", "New York Yankees"),
    ("CCOPA-MS", "Mike Schmidt", "Philadelphia Phillies"),
    ("CCOPA-MT", "Mike Trout", "Angels"),
    ("CCOPA-NO", "Nolan Ryan", "Houston Astros"),
    ("CCOPA-NR", "Nolan Ryan", "California Angels"),
    ("CCOPA-NRY", "Nolan Ryan", "Texas Rangers"),
    ("CCOPA-OS", "Ozzie Smith", "St. Louis Cardinals"),
    ("CCOPA-PA", "Pete Alonso", "New York Mets"),
    ("CCOPA-PG", "Paul Goldschmidt", "New York Yankees"),
    ("CCOPA-PS", "Paul Skenes", "Pittsburgh Pirates"),
    ("CCOPA-RA", "Ronald Acuna Jr.", "Atlanta Braves"),
    ("CCOPA-RC", "Roger Clemens", "Boston Red Sox"),
    ("CCOPA-RS", "Ryne Sandberg", "Chicago Cubs"),
    ("CCOPA-RY", "Robin Yount", "Milwaukee Brewers"),
    ("CCOPA-SC", "Steve Carlton", "Philadelphia Phillies"),
    ("CCOPA-SI", "Shota Imanaga", "Chicago Cubs"),
    ("CCOPA-VG", "Vladimir Guerrero Jr.", "Toronto Blue Jays"),
    ("CCOPA-WB", "Wade Boggs", "Boston Red Sox"),
    ("CCOPA-WC", "Will Clark", "San Francisco Giants"),
    ("CCOPA-YY", "Yoshinobu Yamamoto", "Los Angeles Dodgers"),
]

# Archival Autographs (86 cards)
AA_RAW = [
    ("AA-AA", "Adael Amador", "Colorado Rockies RC"),
    ("AA-AD", "Adrian Del Castillo", "Arizona Diamondbacks RC"),
    ("AA-AM", "Angel Martinez", "Cleveland Guardians RC"),
    ("AA-AT", "Alan Trammell", "Detroit Tigers"),
    ("AA-BL", "Brooks Lee", "Minnesota Twins RC"),
    ("AA-BR", "Ben Rice", "New York Yankees RC"),
    ("AA-BS", "Bryson Stott", "Philadelphia Phillies"),
    ("AA-CAM", "Cam Smith", "Houston Astros RC"),
    ("AA-CD", "Caden Dana", "Angels RC"),
    ("AA-CM", "Coby Mayo", "Baltimore Orioles RC"),
    ("AA-CMC", "Chayce McDermott", "Baltimore Orioles RC"),
    ("AA-CN", "Connor Norby", "Miami Marlins RC"),
    ("AA-CP", "Cade Povich", "Baltimore Orioles RC"),
    ("AA-CS", "Chris Sale", "Atlanta Braves"),
    ("AA-DC", "Dylan Crews", "Washington Nationals RC"),
    ("AA-DE", "Dennis Eckersley", "Oakland Athletics"),
    ("AA-DF", "David Festa", "Minnesota Twins RC"),
    ("AA-DH", "DJ Herz", "Washington Nationals RC"),
    ("AA-DJ", "David Justice", "Atlanta Braves"),
    ("AA-DOL", "Chase Dollander", "Colorado Rockies RC"),
    ("AA-DRA", "Drake Baldwin", "Atlanta Braves RC"),
    ("AA-DT", "Drew Thorpe", "Chicago White Sox RC"),
    ("AA-DW", "David Wright", "New York Mets"),
    ("AA-GG", "Gordon Graceffo", "St. Louis Cardinals RC"),
    ("AA-GM", "Grant McCray", "San Francisco Giants RC"),
    ("AA-HW", "Hurston Waldrep", "Atlanta Braves RC"),
    ("AA-JC", "Jazz Chisholm Jr.", "New York Yankees"),
    ("AA-JCA", "Jose Canseco", "Oakland Athletics"),
    ("AA-JD", "Jarren Duran", "Boston Red Sox"),
    ("AA-JE", "Jim Edmonds", "St. Louis Cardinals"),
    ("AA-JH", "Jung Hoo Lee", "San Francisco Giants"),
    ("AA-JJU", "Jace Jung", "Detroit Tigers RC"),
    ("AA-JM", "Justyn-Henry Malloy", "Detroit Tigers RC"),
    ("AA-JN", "Jhonkensy Noel", "Cleveland Guardians RC"),
    ("AA-JS", "Johan Santana", "New York Mets"),
    ("AA-JV", "Jason Varitek", "Boston Red Sox"),
    ("AA-JW", "James Wood", "Washington Nationals RC"),
    ("AA-JWI", "Jacob Wilson", "Oakland Athletics RC"),
    ("AA-JWR", "Justin Wrobleski", "Los Angeles Dodgers RC"),
    ("AA-KA", "Kevin Alcantara", "Chicago Cubs RC"),
    ("AA-KCA", "Kristian Campbell", "Boston Red Sox RC"),
    ("AA-KR", "Kumar Rocker", "Texas Rangers RC"),
    ("AA-LA", "Luisangel Acuna", "New York Mets RC"),
    ("AA-MG", "Mark Grace", "Chicago Cubs"),
    ("AA-MHA", "Michael Harris II", "Atlanta Braves"),
    ("AA-MM", "Michael McGreevy", "St. Louis Cardinals RC"),
    ("AA-MMA", "Marcelo Mayer", "Boston Red Sox RC"),
    ("AA-MT", "Mike Trout", "Angels"),
    ("AA-MY", "Michael Young", "Texas Rangers"),
    ("AA-NK", "Nick Kurtz", "Oakland Athletics RC"),
    ("AA-NY", "Nick Yorke", "Pittsburgh Pirates RC"),
    ("AA-OM", "Orelvis Martinez", "Toronto Blue Jays RC"),
    ("AA-PL", "Pedro Leon", "Houston Astros RC"),
    ("AA-RA", "Ronald Acuna Jr.", "Atlanta Braves"),
    ("AA-RB", "Ryan Bliss", "Seattle Mariners RC"),
    ("AA-RH", "Ryan Howard", "Philadelphia Phillies"),
    ("AA-RHI", "Rece Hinds", "Cincinnati Reds RC"),
    ("AA-RL", "Rhett Lowder", "Cincinnati Reds RC"),
    ("AA-ROKI", "Roki Sasaki", "Los Angeles Dodgers RC"),
    ("AA-RUSH", "Dalton Rushing", "Los Angeles Dodgers RC"),
    ("AA-RZ", "Ryan Zimmerman", "Washington Nationals"),
    ("AA-SA", "Samuel Aldegheri", "Angels RC"),
    ("AA-SHA", "Matt Shaw", "Chicago Cubs RC"),
    ("AA-SK", "Steven Kwan", "Cleveland Guardians"),
    ("AA-SS", "Spencer Schwellenbach", "Atlanta Braves RC"),
    ("AA-SW", "Shay Whitcomb", "Houston Astros RC"),
    ("AA-TE", "Tommy Edman", "Los Angeles Dodgers"),
    ("AA-TL", "Tyler Locklear", "Seattle Mariners RC"),
    ("AA-TS", "Thomas Saggese", "St. Louis Cardinals RC"),
    ("AA-TSW", "Trey Sweeney", "Detroit Tigers RC"),
    ("AA-VG", "Vladimir Guerrero Jr.", "Toronto Blue Jays"),
    ("AA-WL", "Wyatt Langford", "Texas Rangers"),
    ("AA-WW", "Will Wagner", "Toronto Blue Jays RC"),
    ("AA-WWA", "Will Warren", "New York Yankees RC"),
    ("AA-YY", "Yoshinobu Yamamoto", "Los Angeles Dodgers"),
    ("AA-ZD", "Zach Dezenzo", "Houston Astros RC"),
    ("AA-ZM", "Zebby Matthews", "Minnesota Twins RC"),
]

# Atelier Autographed Book Cards (40 cards)
AABC_RAW = [
    ("AABC-ADR", "Gunnar Henderson", "Baltimore Orioles"),
    ("AABC-AJ", "Aaron Judge", "New York Yankees"),
    ("AABC-AP", "Albert Pujols", "St. Louis Cardinals"),
    ("AABC-BIG", "Craig Biggio", "Houston Astros"),
    ("AABC-BP", "Buster Posey", "San Francisco Giants"),
    ("AABC-BWJ", "Bobby Witt Jr.", "Kansas City Royals"),
    ("AABC-CAL", "Cal Ripken Jr.", "Baltimore Orioles"),
    ("AABC-CJ", "Chipper Jones", "Atlanta Braves"),
    ("AABC-CK", "Clayton Kershaw", "Los Angeles Dodgers"),
    ("AABC-CREWS", "Dylan Crews", "Washington Nationals RC"),
    ("AABC-DJ", "Derek Jeter", "New York Yankees"),
    ("AABC-DW", "David Wright", "New York Mets"),
    ("AABC-ELLY", "Elly De La Cruz", "Cincinnati Reds"),
    ("AABC-FTJ", "Fernando Tatis Jr.", "San Diego Padres"),
    ("AABC-GB", "George Brett", "Royals Stadium"),
    ("AABC-I", "Ichiro", "Seattle Mariners"),
    ("AABC-JA", "Jose Altuve", "Houston Astros"),
    ("AABC-JR", "Julio Rodriguez", "Seattle Mariners"),
    ("AABC-JS", "Juan Soto", "New York Mets"),
    ("AABC-JVO", "Joey Votto", "Cincinnati Reds"),
    ("AABC-MCG", "Mark McGwire", "Oakland Athletics"),
    ("AABC-MER", "Jackson Merrill", "San Diego Padres"),
    ("AABC-MM", "Manny Machado", "San Diego Padres"),
    ("AABC-MO", "Mariano Rivera", "New York Yankees"),
    ("AABC-MT", "Mike Trout", "Angels"),
    ("AABC-PA", "Pete Alonso", "New York Mets"),
    ("AABC-RAJ", "Ronald Acuna Jr.", "Atlanta Braves"),
    ("AABC-RS", "Ryne Sandberg", "Chicago Cubs"),
    ("AABC-SCH", "Kyle Schwarber", "Philadelphia Phillies"),
    ("AABC-SHOTA", "Shota Imanaga", "Chicago Cubs"),
    ("AABC-SKE", "Paul Skenes", "Pittsburgh Pirates"),
    ("AABC-SMO", "John Smoltz", "Atlanta Braves"),
    ("AABC-SOH", "Shohei Ohtani", "Los Angeles Dodgers"),
    ("AABC-SSO", "Sammy Sosa", "Chicago Cubs"),
    ("AABC-UTL", "Chase Utley", "Philadelphia Phillies"),
    ("AABC-VAR", "Jason Varitek", "Boston Red Sox"),
    ("AABC-VGJ", "Vladimir Guerrero Jr.", "Toronto Blue Jays"),
    ("AABC-WC", "Will Clark", "San Francisco Giants"),
    ("AABC-WOOD", "James Wood", "Washington Nationals RC"),
    ("AABC-YADI", "Yadier Molina", "St. Louis Cardinals"),
    ("AABC-YAMA", "Yoshinobu Yamamoto", "Los Angeles Dodgers"),
]

# Showpieces Autographs (80 cards)
SA_RAW = [
    ("SA-AP", "Albert Pujols", "St. Louis Cardinals"),
    ("SA-APE", "Andy Pettitte", "New York Yankees"),
    ("SA-AR", "Adley Rutschman", "Baltimore Orioles"),
    ("SA-B", "Barry Bonds", "San Francisco Giants"),
    ("SA-BL", "Barry Larkin", "Cincinnati Reds"),
    ("SA-BLE", "Brooks Lee", "Minnesota Twins RC"),
    ("SA-BP", "Buster Posey", "San Francisco Giants"),
    ("SA-BR", "Ben Rice", "New York Yankees RC"),
    ("SA-CBI", "Craig Biggio", "Houston Astros"),
    ("SA-CC", "Corbin Carroll", "Arizona Diamondbacks"),
    ("SA-CH", "Chan Ho Park", "Los Angeles Dodgers"),
    ("SA-CJ", "Chipper Jones", "Atlanta Braves"),
    ("SA-CM", "Coby Mayo", "Baltimore Orioles RC"),
    ("SA-CS", "Corey Seager", "Texas Rangers"),
    ("SA-CSA", "Chris Sale", "Atlanta Braves"),
    ("SA-CY", "Christian Yelich", "Milwaukee Brewers"),
    ("SA-DC", "Dylan Crews", "Washington Nationals RC"),
    ("SA-DJ", "Derek Jeter", "New York Yankees"),
    ("SA-DM", "Dale Murphy", "Atlanta Braves"),
    ("SA-DS", "Darryl Strawberry", "New York Mets"),
    ("SA-ED", "Elly De La Cruz", "Cincinnati Reds"),
    ("SA-EM", "Edgar Martinez", "Seattle Mariners"),
    ("SA-FH", "Felix Hernandez", "Seattle Mariners"),
    ("SA-FTH", "Frank Thomas", "Chicago White Sox"),
    ("SA-GH", "Gunnar Henderson", "Baltimore Orioles"),
    ("SA-HM", "Hideki Matsui", "New York Yankees"),
    ("SA-I", "Ichiro", "Seattle Mariners"),
    ("SA-IR", "Ivan Rodriguez", "Florida Marlins"),
    ("SA-JA", "Jose Altuve", "Houston Astros"),
    ("SA-JB", "Johnny Bench", "Cincinnati Reds"),
    ("SA-JG", "Juan Gonzalez", "Texas Rangers"),
    ("SA-JJ", "Jackson Jobe", "Detroit Tigers RC"),
    ("SA-JJU", "Jace Jung", "Detroit Tigers RC"),
    ("SA-JM", "Jackson Merrill", "San Diego Padres"),
    ("SA-JRE", "J.T. Realmuto", "Philadelphia Phillies"),
    ("SA-JRO", "Jimmy Rollins", "Philadelphia Phillies"),
    ("SA-JS", "Juan Soto", "New York Mets"),
    ("SA-JSA", "Johan Santana", "Minnesota Twins"),
    ("SA-JW", "James Wood", "Washington Nationals RC"),
    ("SA-JWI", "Jacob Wilson", "Oakland Athletics RC"),
    ("SA-KA", "Kevin Alcantara", "Chicago Cubs RC"),
    ("SA-KG", "Ken Griffey Jr.", "Seattle Mariners"),
    ("SA-KH", "Keith Hernandez", "New York Mets"),
    ("SA-KR", "Kumar Rocker", "Texas Rangers RC"),
    ("SA-KT", "Kyle Tucker", "Chicago Cubs"),
    ("SA-LA", "Luisangel Acuna", "New York Mets RC"),
    ("SA-MO", "Matt Olson", "Atlanta Braves"),
    ("SA-MP", "Mike Piazza", "New York Mets"),
    ("SA-MS", "Mike Schmidt", "Philadelphia Phillies"),
    ("SA-MT", "Mike Trout", "Angels"),
    ("SA-NA", "Nolan Arenado", "St. Louis Cardinals"),
    ("SA-NR", "Nolan Ryan", "California Angels"),
    ("SA-OA", "Ozzie Albies", "Atlanta Braves"),
    ("SA-PM", "Paul Molitor", "Milwaukee Brewers"),
    ("SA-PS", "Paul Skenes", "Pittsburgh Pirates"),
    ("SA-RA", "Ronald Acuna Jr.", "Atlanta Braves"),
    ("SA-RH", "Ryan Howard", "Philadelphia Phillies"),
    ("SA-RJ", "Reggie Jackson", "Oakland Athletics"),
    ("SA-SG", "Sonny Gray", "St. Louis Cardinals"),
    ("SA-SI", "Shota Imanaga", "Chicago Cubs"),
    ("SA-SO", "Shohei Ohtani", "Los Angeles Dodgers"),
    ("SA-SS", "Sammy Sosa", "Chicago Cubs"),
    ("SA-SST", "Spencer Strider", "Atlanta Braves"),
    ("SA-TT", "Trea Turner", "Philadelphia Phillies"),
    ("SA-VG", "Vladimir Guerrero Jr.", "Toronto Blue Jays"),
    ("SA-WB", "Wade Boggs", "New York Yankees"),
    ("SA-WC", "Will Clark", "San Francisco Giants"),
    ("SA-WL", "Wyatt Langford", "Texas Rangers"),
    ("SA-YY", "Yoshinobu Yamamoto", "Los Angeles Dodgers"),
]

# Dual On Card Autographs (10 cards) -- co_players
DA_RAW = [
    ("DA-BB", [("Craig Biggio", "Houston Astros"), ("Jeff Bagwell", "Houston Astros")]),
    ("DA-BY", [("Adrian Beltre", "Texas Rangers"), ("Michael Young", "Texas Rangers")]),
    ("DA-LD", [("Barry Larkin", "Cincinnati Reds"), ("Elly De La Cruz", "Cincinnati Reds")]),
    ("DA-MI", [("Shota Imanaga", "Chicago Cubs"), ("Greg Maddux", "Chicago Cubs")]),
    ("DA-MJ", [("Dale Murphy", "Atlanta Braves"), ("Chipper Jones", "Atlanta Braves")]),
    ("DA-MS", [("Ryne Sandberg", "Chicago Cubs"), ("Greg Maddux", "Chicago Cubs")]),
    ("DA-RS", [("Nolan Ryan", "Houston Astros"), ("Paul Skenes", "Pittsburgh Pirates")]),
    ("DA-SHA", [("Steve Carlton", "Philadelphia Phillies"), ("Mike Schmidt", "Philadelphia Phillies")]),
    ("DA-TW", [("Mike Trout", "Angels"), ("Bobby Witt Jr.", "Kansas City Royals")]),
    ("DA-YM", [("Paul Molitor", "Milwaukee Brewers"), ("Robin Yount", "Milwaukee Brewers")]),
]

# Triple On Card Autographs (5 cards) -- co_players
TA_RAW = [
    ("TA-BGJ", [("Barry Bonds", "San Francisco Giants"), ("Ken Griffey Jr.", "Seattle Mariners"), ("Aaron Judge", "New York Yankees")]),
    ("TA-BJW", [("Bo Jackson", "Kansas City Royals"), ("Bobby Witt Jr.", "Kansas City Royals"), ("George Brett", "Kansas City Royals")]),
    ("TA-KOY", [("Yoshinobu Yamamoto", "Los Angeles Dodgers"), ("Shohei Ohtani", "Los Angeles Dodgers"), ("Clayton Kershaw", "Los Angeles Dodgers")]),
    ("TA-RHH", [("Gunnar Henderson", "Baltimore Orioles"), ("Cal Ripken Jr.", "Baltimore Orioles"), ("Jackson Holliday", "Baltimore Orioles")]),
    ("TA-SUH", [("Bryce Harper", "Philadelphia Phillies"), ("Mike Schmidt", "Philadelphia Phillies"), ("Chase Utley", "Philadelphia Phillies")]),
]

# Museum Framed Autographs (95 cards)
FMA_RAW = [
    ("FMA-AB", "Adrian Beltre", "Texas Rangers"),
    ("FMA-AJ", "Aaron Judge", "New York Yankees"),
    ("FMA-AP", "Albert Pujols", "St. Louis Cardinals"),
    ("FMA-AR", "Alex Rodriguez", "New York Yankees"),
    ("FMA-ARU", "Adley Rutschman", "Baltimore Orioles"),
    ("FMA-AT", "Alan Trammell", "Detroit Tigers"),
    ("FMA-BJ", "Bo Jackson", "Kansas City Royals"),
    ("FMA-BL", "Barry Larkin", "Cincinnati Reds"),
    ("FMA-BLE", "Brooks Lee", "Minnesota Twins RC"),
    ("FMA-BP", "Buster Posey", "San Francisco Giants"),
    ("FMA-BW", "Bobby Witt Jr.", "Kansas City Royals"),
    ("FMA-CC", "Corbin Carroll", "Arizona Diamondbacks"),
    ("FMA-CF", "Carlton Fisk", "Boston Red Sox"),
    ("FMA-CJ", "Chipper Jones", "Atlanta Braves"),
    ("FMA-CK", "Clayton Kershaw", "Los Angeles Dodgers"),
    ("FMA-CM", "Coby Mayo", "Baltimore Orioles RC"),
    ("FMA-CR", "Cal Ripken Jr.", "Baltimore Orioles"),
    ("FMA-CU", "Chase Utley", "Philadelphia Phillies"),
    ("FMA-DC", "Dylan Crews", "Washington Nationals RC"),
    ("FMA-DJ", "Derek Jeter", "New York Yankees"),
    ("FMA-DM", "Dale Murphy", "Atlanta Braves"),
    ("FMA-DMA", "Don Mattingly", "New York Yankees"),
    ("FMA-DW", "David Wright", "New York Mets"),
    ("FMA-ED", "Elly De La Cruz", "Cincinnati Reds"),
    ("FMA-EM", "Eddie Murray", "Baltimore Orioles"),
    ("FMA-FH", "Felix Hernandez", "Seattle Mariners"),
    ("FMA-FL", "Francisco Lindor", "New York Mets"),
    ("FMA-FM", "Fred McGriff", "Tampa Bay Devil Rays"),
    ("FMA-FTH", "Frank Thomas", "Chicago White Sox"),
    ("FMA-GB", "George Brett", "Kansas City Royals"),
    ("FMA-GH", "Gunnar Henderson", "Baltimore Orioles"),
    ("FMA-GM", "Greg Maddux", "Chicago Cubs"),
    ("FMA-GMA", "Greg Maddux", "Atlanta Braves"),
    ("FMA-HM", "Hideki Matsui", "New York Yankees"),
    ("FMA-I", "Ichiro", "Seattle Mariners"),
    ("FMA-JA", "Jose Altuve", "Houston Astros"),
    ("FMA-JB", "Johnny Bench", "Cincinnati Reds"),
    ("FMA-JBA", "Jeff Bagwell", "Houston Astros"),
    ("FMA-JJ", "Jackson Jobe", "Detroit Tigers RC"),
    ("FMA-JM", "Jackson Merrill", "San Diego Padres"),
    ("FMA-JR", "Julio Rodriguez", "Seattle Mariners"),
    ("FMA-JRA", "Jose Ramirez", "Cleveland Guardians"),
    ("FMA-JS", "Juan Soto", "New York Mets"),
    ("FMA-JV", "Joey Votto", "Cincinnati Reds"),
    ("FMA-JW", "James Wood", "Washington Nationals RC"),
    ("FMA-JWI", "Jacob Wilson", "Oakland Athletics RC"),
    ("FMA-KA", "Kevin Alcantara", "Chicago Cubs RC"),
    ("FMA-KG", "Ken Griffey Jr.", "Seattle Mariners"),
    ("FMA-KR", "Kumar Rocker", "Texas Rangers RC"),
    ("FMA-KS", "Kyle Schwarber", "Philadelphia Phillies"),
    ("FMA-LA", "Luisangel Acuna", "New York Mets RC"),
    ("FMA-MA", "Manny Machado", "San Diego Padres"),
    ("FMA-MM", "Mark McGwire", "Oakland Athletics"),
    ("FMA-MMA", "Marcelo Mayer", "Boston Red Sox RC"),
    ("FMA-MO", "Matt Olson", "Atlanta Braves"),
    ("FMA-MP", "Mike Piazza", "New York Mets"),
    ("FMA-MR", "Mariano Rivera", "New York Yankees"),
    ("FMA-MS", "Mike Schmidt", "Philadelphia Phillies"),
    ("FMA-MT", "Mike Trout", "Angels"),
    ("FMA-NR", "Nolan Ryan", "Texas Rangers"),
    ("FMA-NRY", "Nolan Ryan", "Houston Astros"),
    ("FMA-OH", "Orel Hershiser", "Los Angeles Dodgers"),
    ("FMA-OS", "Ozzie Smith", "St. Louis Cardinals"),
    ("FMA-PA", "Pete Alonso", "New York Mets"),
    ("FMA-PG", "Paul Goldschmidt", "New York Yankees"),
    ("FMA-PS", "Paul Skenes", "Pittsburgh Pirates"),
    ("FMA-RA", "Ronald Acuna Jr.", "Atlanta Braves"),
    ("FMA-RC", "Roger Clemens", "New York Yankees"),
    ("FMA-RJ", "Randy Johnson", "Seattle Mariners"),
    ("FMA-RJA", "Reggie Jackson", "New York Yankees"),
    ("FMA-RJO", "Randy Johnson", "Arizona Diamondbacks"),
    ("FMA-ROKI", "Roki Sasaki", "Los Angeles Dodgers RC"),
    ("FMA-RS", "Ryne Sandberg", "Chicago Cubs"),
    ("FMA-RY", "Robin Yount", "Milwaukee Brewers"),
    ("FMA-SC", "Steve Carlton", "Philadelphia Phillies"),
    ("FMA-SI", "Shota Imanaga", "Chicago Cubs"),
    ("FMA-SK", "Sandy Koufax", "Los Angeles Dodgers"),
    ("FMA-SO", "Shohei Ohtani", "Los Angeles Dodgers"),
    ("FMA-SS", "Sammy Sosa", "Chicago Cubs"),
    ("FMA-TT", "Trea Turner", "Philadelphia Phillies"),
    ("FMA-VG", "Vladimir Guerrero Jr.", "Toronto Blue Jays"),
    ("FMA-WB", "Wade Boggs", "Boston Red Sox"),
    ("FMA-WC", "Will Clark", "San Francisco Giants"),
    ("FMA-YA", "Yordan Alvarez", "Houston Astros"),
    ("FMA-YM", "Yadier Molina", "St. Louis Cardinals"),
    ("FMA-YY", "Yoshinobu Yamamoto", "Los Angeles Dodgers"),
]

# Framed HOF Autographs (4 cards)
HOF_RAW = [
    ("HOF-BW", "Billy Wagner", "Houston Astros"),
    ("HOF-CC", "CC Sabathia", "New York Yankees"),
    ("HOF-IS", "Ichiro", "Seattle Mariners"),
    ("HOF-JM", "Joe Mauer", "Minnesota Twins"),
]

# Retrospective Signatures (19 cards)
RS_RAW = [
    ("RS-AD", "Andre Dawson", "Chicago Cubs"),
    ("RS-AJ", "Andruw Jones", "Atlanta Braves"),
    ("RS-BW", "Bernie Williams", "New York Yankees"),
    ("RS-CF", "Carlton Fisk", "Boston Red Sox"),
    ("RS-DM", "Don Mattingly", "New York Yankees"),
    ("RS-DP", "Dustin Pedroia", "Boston Red Sox"),
    ("RS-EM", "Edgar Martinez", "Seattle Mariners"),
    ("RS-FJ", "Fergie Jenkins", "Chicago Cubs"),
    ("RS-JB", "Jeff Bagwell", "Houston Astros"),
    ("RS-JP", "Jim Palmer", "Baltimore Orioles"),
    ("RS-JR", "Jim Rice", "Boston Red Sox"),
    ("RS-NG", "Nomar Garciaparra", "Boston Red Sox"),
    ("RS-OS", "Ozzie Smith", "St. Louis Cardinals"),
    ("RS-PM", "Paul Molitor", "Milwaukee Brewers"),
    ("RS-RS", "Ryne Sandberg", "Chicago Cubs"),
    ("RS-RY", "Robin Yount", "Milwaukee Brewers"),
    ("RS-SC", "Steve Carlton", "Philadelphia Phillies"),
    ("RS-TR", "Tim Raines", "Montreal Expos"),
    ("RS-VG", "Vladimir Guerrero", "Montreal Expos"),
]

# Museum Framed Autograph Patch Cards (44 cards)
MFAP_RAW = [
    ("MFAP-AB", "Adrian Beltre", "Texas Rangers"),
    ("MFAP-ADL", "Adley Rutschman", "Baltimore Orioles"),
    ("MFAP-AJ", "Aaron Judge", "New York Yankees"),
    ("MFAP-ALT", "Jose Altuve", "Houston Astros"),
    ("MFAP-AN", "Aaron Nola", "Philadelphia Phillies"),
    ("MFAP-AR", "Austin Riley", "Atlanta Braves"),
    ("MFAP-AV", "Anthony Volpe", "New York Yankees"),
    ("MFAP-BB", "Byron Buxton", "Minnesota Twins"),
    ("MFAP-BH", "Bryce Harper", "Philadelphia Phillies"),
    ("MFAP-BN", "Brandon Nimmo", "New York Mets"),
    ("MFAP-BP", "Buster Posey", "San Francisco Giants"),
    ("MFAP-BWJ", "Bobby Witt Jr.", "Kansas City Royals"),
    ("MFAP-CJ", "Chipper Jones", "Atlanta Braves"),
    ("MFAP-CKE", "Clayton Kershaw", "Los Angeles Dodgers"),
    ("MFAP-COR", "Corbin Carroll", "Arizona Diamondbacks"),
    ("MFAP-CY", "Christian Yelich", "Milwaukee Brewers"),
    ("MFAP-DO", "David Ortiz", "Boston Red Sox"),
    ("MFAP-DUR", "Jarren Duran", "Boston Red Sox"),
    ("MFAP-EDLC", "Elly De La Cruz", "Cincinnati Reds"),
    ("MFAP-GUN", "Gunnar Henderson", "Baltimore Orioles"),
    ("MFAP-I", "Ichiro", "Miami Marlins"),
    ("MFAP-ICH", "Ichiro", "Seattle Mariners"),
    ("MFAP-IR", "Ivan Rodriguez", "Texas Rangers"),
    ("MFAP-JAZ", "Jazz Chisholm Jr.", "New York Yankees"),
    ("MFAP-JCAM", "Junior Caminero", "Tampa Bay Rays"),
    ("MFAP-JDOM", "Jasson Dominguez", "New York Yankees"),
    ("MFAP-JRO", "Jimmy Rollins", "Philadelphia Phillies"),
    ("MFAP-JROD", "Julio Rodriguez", "Seattle Mariners"),
    ("MFAP-JV", "Joey Votto", "Cincinnati Reds"),
    ("MFAP-KS", "Kyle Schwarber", "Philadelphia Phillies"),
    ("MFAP-MAN", "Manny Machado", "San Diego Padres"),
    ("MFAP-MAT", "Hideki Matsui", "New York Yankees"),
    ("MFAP-MERR", "Jackson Merrill", "San Diego Padres"),
    ("MFAP-MH", "Michael Harris II", "Atlanta Braves"),
    ("MFAP-MO", "Matt Olson", "Atlanta Braves"),
    ("MFAP-MR", "Mariano Rivera", "New York Yankees"),
    ("MFAP-MSC", "Mike Schmidt", "Philadelphia Phillies"),
    ("MFAP-MT", "Mike Trout", "Angels"),
    ("MFAP-NH", "Nico Hoerner", "Chicago Cubs"),
    ("MFAP-NR", "Nolan Ryan", "Houston Astros"),
    ("MFAP-OZZ", "Ozzie Albies", "Atlanta Braves"),
    ("MFAP-PA", "Pete Alonso", "New York Mets"),
    ("MFAP-PIA", "Mike Piazza", "New York Mets"),
    ("MFAP-RAJ", "Ronald Acuna Jr.", "Atlanta Braves"),
    ("MFAP-TTU", "Trea Turner", "Philadelphia Phillies"),
    ("MFAP-VGJ", "Vladimir Guerrero Jr.", "Toronto Blue Jays"),
    ("MFAP-YA", "Yordan Alvarez", "Houston Astros"),
]

# Museum Framed Dual Autograph Patch Book Cards (9 cards) -- co_players
MFDAP_RAW = [
    ("MFDAP-AR", [("Ronald Acuna Jr.", "Atlanta Braves"), ("Julio Rodriguez", "Seattle Mariners")]),
    ("MFDAP-BR", [("Adrian Beltre", "Texas Rangers"), ("Ivan Rodriguez", "Texas Rangers")]),
    ("MFDAP-JA", [("Chipper Jones", "Atlanta Braves"), ("Ronald Acuna Jr.", "Atlanta Braves")]),
    ("MFDAP-LV", [("Barry Larkin", "Cincinnati Reds"), ("Joey Votto", "Cincinnati Reds")]),
    ("MFDAP-RM", [("Gunnar Henderson", "Baltimore Orioles"), ("Cal Ripken Jr.", "Baltimore Orioles")]),
    ("MFDAP-SH", [("Bryce Harper", "Philadelphia Phillies"), ("Mike Schmidt", "Philadelphia Phillies")]),
    ("MFDAP-TWJ", [("Mike Trout", "Angels"), ("Bobby Witt Jr.", "Kansas City Royals")]),
    ("MFDAP-WCR", [("James Wood", "Washington Nationals RC"), ("Dylan Crews", "Washington Nationals RC")]),
    ("MFDAP-YCH", [("Christian Yelich", "Milwaukee Brewers"), ("Jackson Chourio", "Milwaukee Brewers")]),
]

# Momentous Material Jumbo Patch Autographs (83 cards)
MMJPA_RAW = [
    ("MMJPA-AB", "Alex Bregman", "Houston Astros"),
    ("MMJPA-ABO", "Alec Bohm", "Philadelphia Phillies"),
    ("MMJPA-AG", "Adolis Garcia", "Texas Rangers"),
    ("MMJPA-AJ", "Aaron Judge", "New York Yankees"),
    ("MMJPA-AN", "Aaron Nola", "Philadelphia Phillies"),
    ("MMJPA-AP", "Albert Pujols", "Angels"),
    ("MMJPA-APE", "Andy Pettitte", "New York Yankees"),
    ("MMJPA-AR", "Austin Riley", "Atlanta Braves"),
    ("MMJPA-ARU", "Adley Rutschman", "Baltimore Orioles"),
    ("MMJPA-AV", "Anthony Volpe", "New York Yankees"),
    ("MMJPA-BB", "Byron Buxton", "Minnesota Twins"),
    ("MMJPA-BN", "Brandon Nimmo", "New York Mets"),
    ("MMJPA-BRE", "Bryan Reynolds", "Pittsburgh Pirates"),
    ("MMJPA-BW", "Bobby Witt Jr.", "Kansas City Royals"),
    ("MMJPA-CC", "Carlos Correa", "Minnesota Twins"),
    ("MMJPA-CCA", "Corbin Carroll", "Arizona Diamondbacks"),
    ("MMJPA-CJ", "Chipper Jones", "Atlanta Braves"),
    ("MMJPA-CM", "Cedric Mullins", "Baltimore Orioles"),
    ("MMJPA-CR", "Cal Ripken Jr.", "Baltimore Orioles"),
    ("MMJPA-CRA", "Cal Raleigh", "Seattle Mariners"),
    ("MMJPA-CS", "CC Sabathia", "New York Yankees"),
    ("MMJPA-CUT", "Andrew McCutchen", "Pittsburgh Pirates"),
    ("MMJPA-CY", "Christian Yelich", "Milwaukee Brewers"),
    ("MMJPA-DO", "David Ortiz", "Boston Red Sox"),
    ("MMJPA-DP", "Dustin Pedroia", "Boston Red Sox"),
    ("MMJPA-FA", "Francisco Alvarez", "New York Mets"),
    ("MMJPA-FF", "Freddie Freeman", "Los Angeles Dodgers"),
    ("MMJPA-FP", "Freddy Peralta", "Milwaukee Brewers"),
    ("MMJPA-FT", "Fernando Tatis Jr.", "San Diego Padres"),
    ("MMJPA-GC", "Gerrit Cole", "New York Yankees"),
    ("MMJPA-GSP", "George Springer", "Toronto Blue Jays"),
    ("MMJPA-I", "Ichiro", "Seattle Mariners"),
    ("MMJPA-IS", "Ichiro", "Miami Marlins"),
    ("MMJPA-JA", "Jose Altuve", "Houston Astros"),
    ("MMJPA-JC", "Junior Caminero", "Tampa Bay Rays"),
    ("MMJPA-JCO", "Jackson Chourio", "Milwaukee Brewers"),
    ("MMJPA-JH", "Jackson Holliday", "Baltimore Orioles"),
    ("MMJPA-JHL", "Jung Hoo Lee", "San Francisco Giants"),
    ("MMJPA-JM", "Jackson Merrill", "San Diego Padres"),
    ("MMJPA-JP", "Jeremy Pena", "Houston Astros"),
    ("MMJPA-JR", "Julio Rodriguez", "Seattle Mariners"),
    ("MMJPA-JRA", "Jose Ramirez", "Cleveland Guardians"),
    ("MMJPA-JRE", "J.T. Realmuto", "Philadelphia Phillies"),
    ("MMJPA-JV", "Joey Votto", "Cincinnati Reds"),
    ("MMJPA-JW", "James Wood", "Washington Nationals RC"),
    ("MMJPA-KB", "Kris Bryant", "Colorado Rockies"),
    ("MMJPA-KH", "Ke'Bryan Hayes", "Pittsburgh Pirates"),
    ("MMJPA-KT", "Kyle Tucker", "Houston Astros"),
    ("MMJPA-LB", "Lawrence Butler", "Oakland Athletics"),
    ("MMJPA-LR", "Luis Robert Jr.", "Chicago White Sox"),
    ("MMJPA-LW", "Larry Walker", "Colorado Rockies"),
    ("MMJPA-LWE", "Logan Webb", "San Francisco Giants"),
    ("MMJPA-MC", "Miguel Cabrera", "Detroit Tigers"),
    ("MMJPA-MM", "Manny Machado", "San Diego Padres"),
    ("MMJPA-MMU", "Max Muncy", "Los Angeles Dodgers"),
    ("MMJPA-MO", "Matt Olson", "Atlanta Braves"),
    ("MMJPA-MR", "Manny Ramirez", "Boston Red Sox"),
    ("MMJPA-MT", "Mike Trout", "Angels"),
    ("MMJPA-MW", "Masyn Winn", "St. Louis Cardinals"),
    ("MMJPA-MY", "Masataka Yoshida", "Boston Red Sox"),
    ("MMJPA-MYA", "Mike Yastrzemski", "San Francisco Giants"),
    ("MMJPA-NA", "Nolan Arenado", "St. Louis Cardinals"),
    ("MMJPA-NS", "Nolan Schanuel", "Angels"),
    ("MMJPA-OA", "Ozzie Albies", "Atlanta Braves"),
    ("MMJPA-PA", "Pete Alonso", "New York Mets"),
    ("MMJPA-PG", "Paul Goldschmidt", "St. Louis Cardinals"),
    ("MMJPA-PR", "Pete Rose", "Cincinnati Reds"),
    ("MMJPA-RA", "Ronald Acuna Jr.", "Atlanta Braves"),
    ("MMJPA-RAR", "Randy Arozarena", "Seattle Mariners"),
    ("MMJPA-RD", "Rafael Devers", "Boston Red Sox"),
    ("MMJPA-RG", "Riley Greene", "Detroit Tigers"),
    ("MMJPA-RL", "Royce Lewis", "Minnesota Twins"),
    ("MMJPA-SA", "Sandy Alcantara", "Miami Marlins"),
    ("MMJPA-SF", "Sal Frelick", "Milwaukee Brewers"),
    ("MMJPA-SK", "Steven Kwan", "Cleveland Guardians"),
    ("MMJPA-SL", "Shea Langeliers", "Oakland Athletics"),
    ("MMJPA-SM", "Starling Marte", "New York Mets"),
    ("MMJPA-SST", "Spencer Strider", "Atlanta Braves"),
    ("MMJPA-TG", "Tom Glavine", "New York Mets"),
    ("MMJPA-TH", "Teoscar Hernandez", "Los Angeles Dodgers"),
    ("MMJPA-TS", "Tarik Skubal", "Detroit Tigers"),
    ("MMJPA-TSO", "Tyler Soderstrom", "Oakland Athletics"),
    ("MMJPA-TT", "Trea Turner", "Philadelphia Phillies"),
    ("MMJPA-VG", "Vladimir Guerrero Jr.", "Toronto Blue Jays"),
    ("MMJPA-WC", "William Contreras", "Milwaukee Brewers"),
    ("MMJPA-WS", "Will Smith", "Los Angeles Dodgers"),
    ("MMJPA-YA", "Yordan Alvarez", "Houston Astros"),
    ("MMJPA-YD", "Yu Darvish", "San Diego Padres"),
]

# Momentous Material Dual Jumbo Patch Autograph Book Cards (48 cards) -- co_players
MMDPA_RAW = [
    ("MMDPA-AA", [("Yordan Alvarez", "Houston Astros"), ("Jose Altuve", "Houston Astros")]),
    ("MMDPA-AJO", [("Andruw Jones", "Atlanta Braves"), ("Ronald Acuna Jr.", "Atlanta Braves")]),
    ("MMDPA-AP", [("Jeremy Pena", "Houston Astros"), ("Jose Altuve", "Houston Astros")]),
    ("MMDPA-AW", [("Masyn Winn", "St. Louis Cardinals"), ("Nolan Arenado", "St. Louis Cardinals")]),
    ("MMDPA-BCO", [("Carlos Correa", "Minnesota Twins"), ("Byron Buxton", "Minnesota Twins")]),
    ("MMDPA-BR", [("Alec Bohm", "Philadelphia Phillies"), ("J.T. Realmuto", "Philadelphia Phillies")]),
    ("MMDPA-CM", [("Corbin Carroll", "Arizona Diamondbacks"), ("Gabriel Moreno", "Arizona Diamondbacks")]),
    ("MMDPA-DCJ", [("Jasson Dominguez", "New York Yankees"), ("Jazz Chisholm Jr.", "New York Yankees")]),
    ("MMDPA-DI", [("Shota Imanaga", "Chicago Cubs"), ("Yu Darvish", "San Diego Padres")]),
    ("MMDPA-GRO", [("Julio Rodriguez", "Seattle Mariners"), ("Vladimir Guerrero Jr.", "Toronto Blue Jays")]),
    ("MMDPA-HH", [("Jackson Holliday", "Baltimore Orioles"), ("Gunnar Henderson", "Baltimore Orioles")]),
    ("MMDPA-HR", [("Ryan Howard", "Philadelphia Phillies"), ("Jimmy Rollins", "Philadelphia Phillies")]),
    ("MMDPA-IJR", [("Ichiro", "Seattle Mariners"), ("Julio Rodriguez", "Seattle Mariners")]),
    ("MMDPA-JB", [("Shane Bieber", "Cleveland Guardians"), ("Jose Ramirez", "Cleveland Guardians")]),
    ("MMDPA-JT", [("Mike Trout", "Angels"), ("Aaron Judge", "New York Yankees")]),
    ("MMDPA-LA", [("Pete Alonso", "New York Mets"), ("Francisco Lindor", "New York Mets")]),
    ("MMDPA-MM", [("Justin Morneau", "Minnesota Twins"), ("Joe Mauer", "Minnesota Twins")]),
    ("MMDPA-OR", [("Austin Riley", "Atlanta Braves"), ("Matt Olson", "Atlanta Braves")]),
    ("MMDPA-PP", [("Jorge Posada", "New York Yankees"), ("Andy Pettitte", "New York Yankees")]),
    ("MMDPA-RC", [("Colton Cowser", "Baltimore Orioles"), ("Adley Rutschman", "Baltimore Orioles")]),
    ("MMDPA-SCO", [("Gerrit Cole", "New York Yankees"), ("CC Sabathia", "New York Yankees")]),
    ("MMDPA-TME", [("Fernando Tatis Jr.", "San Diego Padres"), ("Jackson Merrill", "San Diego Padres")]),
    ("MMDPA-TRO", [("Fernando Tatis Jr.", "San Diego Padres"), ("Julio Rodriguez", "Seattle Mariners")]),
    ("MMDPA-TS", [("Kyle Schwarber", "Philadelphia Phillies"), ("Trea Turner", "Philadelphia Phillies")]),
    ("MMDPA-WB", [("Kris Bryant", "Colorado Rockies"), ("Larry Walker", "Colorado Rockies")]),
    ("MMDPA-WCR", [("James Wood", "Washington Nationals RC"), ("Dylan Crews", "Washington Nationals RC")]),
    ("MMDPA-YC", [("Christian Yelich", "Milwaukee Brewers"), ("Jackson Chourio", "Milwaukee Brewers")]),
    ("MMDPA-YCH", [("Mike Yastrzemski", "San Francisco Giants"), ("Matt Chapman", "San Francisco Giants")]),
    ("MMDPA-YCO", [("Christian Yelich", "Milwaukee Brewers"), ("William Contreras", "Milwaukee Brewers")]),
]

# Single Player Signature Swatches Dual Relic Autographs (56 cards)
SPDRA_RAW = [
    ("SPDRA-AB", "Alec Burleson", "St. Louis Cardinals"),
    ("SPDRA-AD", "Andre Dawson", "Chicago Cubs"),
    ("SPDRA-AG", "Adolis Garcia", "Texas Rangers"),
    ("SPDRA-AJ", "Andruw Jones", "Atlanta Braves"),
    ("SPDRA-AS", "Alfonso Soriano", "New York Yankees"),
    ("SPDRA-AW", "Austin Wells", "New York Yankees"),
    ("SPDRA-BB", "Byron Buxton", "Minnesota Twins"),
    ("SPDRA-BM", "Bryce Miller", "Seattle Mariners"),
    ("SPDRA-BR", "Bryan Reynolds", "Pittsburgh Pirates"),
    ("SPDRA-BS", "Bryson Stott", "Philadelphia Phillies"),
    ("SPDRA-CB", "Craig Biggio", "Houston Astros"),
    ("SPDRA-CF", "Carlton Fisk", "Boston Red Sox"),
    ("SPDRA-CJ", "Chipper Jones", "Atlanta Braves"),
    ("SPDRA-CK", "Colt Keith", "Detroit Tigers"),
    ("SPDRA-CM", "Christopher Morel", "Tampa Bay Rays"),
    ("SPDRA-CR", "Cal Raleigh", "Seattle Mariners"),
    ("SPDRA-CRA", "Cole Ragans", "Kansas City Royals"),
    ("SPDRA-DG", "Dwight Gooden", "New York Yankees"),
    ("SPDRA-DJ", "David Justice", "Atlanta Braves"),
    ("SPDRA-DM", "Dale Murphy", "Atlanta Braves"),
    ("SPDRA-DP", "Dustin Pedroia", "Boston Red Sox"),
    ("SPDRA-DV", "Daulton Varsho", "Toronto Blue Jays"),
    ("SPDRA-DW", "Dontrelle Willis", "Florida Marlins"),
    ("SPDRA-EM", "Edgar Martinez", "Seattle Mariners"),
    ("SPDRA-FM", "Fred McGriff", "Chicago Cubs"),
    ("SPDRA-GM", "Gabriel Moreno", "Arizona Diamondbacks"),
    ("SPDRA-HB", "Harold Baines", "Chicago White Sox"),
    ("SPDRA-JG", "Juan Gonzalez", "Texas Rangers"),
    ("SPDRA-JM", "Justin Morneau", "Minnesota Twins"),
    ("SPDRA-JP", "Jorge Posada", "New York Yankees"),
    ("SPDRA-JPE", "Jeremy Pena", "Houston Astros"),
    ("SPDRA-JV", "Jason Varitek", "Boston Red Sox"),
    ("SPDRA-KH", "Ke'Bryan Hayes", "Pittsburgh Pirates"),
    ("SPDRA-KL", "Kenny Lofton", "Chicago Cubs"),
    ("SPDRA-KT", "Kyle Tucker", "Chicago Cubs"),
    ("SPDRA-LG", "Lourdes Gurriel Jr.", "Arizona Diamondbacks"),
    ("SPDRA-LN", "Lars Nootbaar", "St. Louis Cardinals"),
    ("SPDRA-LR", "Luis Robert Jr.", "Chicago White Sox"),
    ("SPDRA-LW", "Logan Webb", "San Francisco Giants"),
    ("SPDRA-MM", "Max Muncy", "Los Angeles Dodgers"),
    ("SPDRA-MO", "Magglio Ordonez", "Detroit Tigers"),
    ("SPDRA-MOL", "Matt Olson", "Atlanta Braves"),
    ("SPDRA-MS", "Marcus Semien", "Texas Rangers"),
    ("SPDRA-MW", "Matt Williams", "San Francisco Giants"),
    ("SPDRA-MYA", "Mike Yastrzemski", "San Francisco Giants"),
    ("SPDRA-NG", "Nolan Gorman", "St. Louis Cardinals"),
    ("SPDRA-NS", "Nolan Schanuel", "Angels"),
    ("SPDRA-PL", "Pablo Lopez", "Minnesota Twins"),
    ("SPDRA-RH", "Rhys Hoskins", "Milwaukee Brewers"),
    ("SPDRA-RM", "Ryan Mountcastle", "Baltimore Orioles"),
    ("SPDRA-SB", "Shane Bieber", "Cleveland Guardians"),
    ("SPDRA-SK", "Steven Kwan", "Cleveland Guardians"),
    ("SPDRA-TH", "Tim Hudson", "Oakland Athletics"),
    ("SPDRA-TO", "Tony Oliva", "Minnesota Twins"),
    ("SPDRA-VG", "Vladimir Guerrero Jr.", "Toronto Blue Jays"),
    ("SPDRA-ZN", "Zach Neto", "Angels"),
]

# Single Player Signature Swatches Triple Relic Autographs (31 cards)
SPTRA_RAW = [
    ("SPTRA-BL", "Brooks Lee", "Minnesota Twins RC"),
    ("SPTRA-BW", "Bernie Williams", "New York Yankees"),
    ("SPTRA-CC", "Colton Cowser", "Baltimore Orioles"),
    ("SPTRA-CM", "Coby Mayo", "Baltimore Orioles RC"),
    ("SPTRA-DCE", "Dylan Cease", "San Diego Padres"),
    ("SPTRA-DO", "David Ortiz", "Boston Red Sox"),
    ("SPTRA-DW", "David Wright", "New York Mets"),
    ("SPTRA-EC", "Evan Carter", "Texas Rangers"),
    ("SPTRA-FT", "Fernando Tatis Jr.", "San Diego Padres"),
    ("SPTRA-GS", "Gary Sheffield", "New York Yankees"),
    ("SPTRA-JB", "Jose Berrios", "Toronto Blue Jays"),
    ("SPTRA-JC", "Jazz Chisholm Jr.", "New York Yankees"),
    ("SPTRA-JCA", "Joe Carter", "Toronto Blue Jays"),
    ("SPTRA-JJ", "Josh Jung", "Texas Rangers"),
    ("SPTRA-JR", "Jim Rice", "Boston Red Sox"),
    ("SPTRA-JS", "Johan Santana", "Minnesota Twins"),
    ("SPTRA-JW", "James Wood", "Washington Nationals RC"),
    ("SPTRA-JWI", "Jacob Wilson", "Oakland Athletics RC"),
    ("SPTRA-LA", "Luisangel Acuna", "New York Mets RC"),
    ("SPTRA-LG", "Luis Gil", "New York Yankees"),
    ("SPTRA-LW", "Larry Walker", "Colorado Rockies"),
    ("SPTRA-MG", "Mark Grace", "Chicago Cubs"),
    ("SPTRA-MM", "Matt McLain", "Cincinnati Reds"),
    ("SPTRA-NG", "Nomar Garciaparra", "Boston Red Sox"),
    ("SPTRA-OM", "Orelvis Martinez", "Toronto Blue Jays RC"),
    ("SPTRA-PA", "Pete Alonso", "New York Mets"),
    ("SPTRA-PK", "Paul Konerko", "Chicago White Sox"),
    ("SPTRA-PM", "Paul Molitor", "Minnesota Twins"),
    ("SPTRA-PO", "Paul O'Neill", "New York Yankees"),
    ("SPTRA-RH", "Ryan Howard", "Philadelphia Phillies"),
    ("SPTRA-SG", "Steve Garvey", "Los Angeles Dodgers"),
    ("SPTRA-SS", "Spencer Strider", "Atlanta Braves"),
]

# Single Player Signature Swatches Quad Relic Autographs (8 cards)
SPQRA_RAW = [
    ("SPQRA-AV", "Anthony Volpe", "New York Yankees"),
    ("SPQRA-CC", "Corbin Carroll", "Arizona Diamondbacks"),
    ("SPQRA-JC", "Junior Caminero", "Tampa Bay Rays"),
    ("SPQRA-JM", "Jackson Merrill", "San Diego Padres"),
    ("SPQRA-MH", "Michael Harris II", "Atlanta Braves"),
    ("SPQRA-MW", "Masyn Winn", "St. Louis Cardinals"),
    ("SPQRA-NH", "Nico Hoerner", "Chicago Cubs"),
    ("SPQRA-WL", "Wyatt Langford", "Texas Rangers"),
]

# Autographed Jumbo Lumber Bat Relics (41 cards)
AJBR_RAW = [
    ("AJBR-AB", "Adrian Beltre", "Texas Rangers"),
    ("AJBR-AJ", "Aaron Judge", "New York Yankees"),
    ("AJBR-AP", "Albert Pujols", "St. Louis Cardinals"),
    ("AJBR-AR", "Alex Rodriguez", "New York Yankees"),
    ("AJBR-BW", "Bobby Witt Jr.", "Kansas City Royals"),
    ("AJBR-CB", "Cody Bellinger", "Chicago Cubs"),
    ("AJBR-CC", "Corbin Carroll", "Arizona Diamondbacks"),
    ("AJBR-CJ", "Chipper Jones", "Atlanta Braves"),
    ("AJBR-CR", "Cal Ripken Jr.", "Baltimore Orioles"),
    ("AJBR-CY", "Christian Yelich", "Milwaukee Brewers"),
    ("AJBR-DJ", "Derek Jeter", "New York Yankees"),
    ("AJBR-DO", "David Ortiz", "Boston Red Sox"),
    ("AJBR-FT", "Frank Thomas", "Chicago White Sox"),
    ("AJBR-FTJ", "Fernando Tatis Jr.", "San Diego Padres"),
    ("AJBR-I", "Ichiro", "Seattle Mariners"),
    ("AJBR-JA", "Jose Altuve", "Houston Astros"),
    ("AJBR-JC", "Jackson Chourio", "Milwaukee Brewers"),
    ("AJBR-JM", "Jackson Merrill", "San Diego Padres"),
    ("AJBR-JR", "J.T. Realmuto", "Philadelphia Phillies"),
    ("AJBR-JRAM", "Jose Ramirez", "Cleveland Guardians"),
    ("AJBR-JS", "Juan Soto", "New York Yankees"),
    ("AJBR-JV", "Joey Votto", "Cincinnati Reds"),
    ("AJBR-KG", "Ken Griffey Jr.", "Seattle Mariners"),
    ("AJBR-LR", "Luis Robert Jr.", "Chicago White Sox"),
    ("AJBR-MAC", "Mark McGwire", "Oakland Athletics"),
    ("AJBR-MAN", "Manny Machado", "San Diego Padres"),
    ("AJBR-MC", "Matt Chapman", "San Francisco Giants"),
    ("AJBR-MH", "Michael Harris II", "Atlanta Braves"),
    ("AJBR-MM", "Max Muncy", "Los Angeles Dodgers"),
    ("AJBR-MP", "Mike Piazza", "New York Mets"),
    ("AJBR-MS", "Mike Schmidt", "Philadelphia Phillies"),
    ("AJBR-MT", "Mike Trout", "Angels"),
    ("AJBR-NH", "Nico Hoerner", "Chicago Cubs"),
    ("AJBR-PA", "Pete Alonso", "New York Mets"),
    ("AJBR-RA", "Ronald Acuna Jr.", "Atlanta Braves"),
    ("AJBR-RIL", "Austin Riley", "Atlanta Braves"),
    ("AJBR-RIZ", "Anthony Rizzo", "New York Yankees"),
    ("AJBR-SS", "Sammy Sosa", "Chicago Cubs"),
    ("AJBR-TT", "Trea Turner", "Philadelphia Phillies"),
    ("AJBR-VG", "Vladimir Guerrero Jr.", "Toronto Blue Jays"),
    ("AJBR-YA", "Yordan Alvarez", "Houston Astros"),
]

# Dual Autographed Jumbo Lumber Bat Relics Book Cards (24 cards) -- co_players
DAJLB_RAW = [
    ("DAJLB-AJA", [("Ozzie Albies", "Atlanta Braves"), ("Ronald Acuna Jr.", "Atlanta Braves")]),
    ("DAJLB-BB", [("Craig Biggio", "Houston Astros"), ("Jeff Bagwell", "Houston Astros")]),
    ("DAJLB-FV", [("Jason Varitek", "Boston Red Sox"), ("Carlton Fisk", "Boston Red Sox")]),
    ("DAJLB-GJS", [("Vladimir Guerrero Jr.", "Toronto Blue Jays"), ("George Springer", "Toronto Blue Jays")]),
    ("DAJLB-GV", [("Jason Varitek", "Boston Red Sox"), ("Nomar Garciaparra", "Boston Red Sox")]),
    ("DAJLB-IOH", [("Ichiro", "Seattle Mariners"), ("Shohei Ohtani", "Los Angeles Dodgers")]),
    ("DAJLB-JCA", [("Matt Olson", "Atlanta Braves"), ("Austin Riley", "Atlanta Braves")]),
    ("DAJLB-JJ", [("Derek Jeter", "New York Yankees"), ("Aaron Judge", "New York Yankees")]),
    ("DAJLB-JMU", [("Chipper Jones", "Atlanta Braves"), ("Dale Murphy", "Atlanta Braves")]),
    ("DAJLB-JO", [("Andruw Jones", "Atlanta Braves"), ("Chipper Jones", "Atlanta Braves")]),
    ("DAJLB-JRJ", [("Cal Ripken Jr.", "Baltimore Orioles"), ("Derek Jeter", "New York Yankees")]),
    ("DAJLB-LV", [("Barry Larkin", "Cincinnati Reds"), ("Joey Votto", "Cincinnati Reds")]),
    ("DAJLB-PMO", [("Albert Pujols", "St. Louis Cardinals"), ("Yadier Molina", "St. Louis Cardinals")]),
    ("DAJLB-RB", [("Jim Rice", "Boston Red Sox"), ("Wade Boggs", "Boston Red Sox")]),
    ("DAJLB-RMU", [("Cal Ripken Jr.", "Baltimore Orioles"), ("Eddie Murray", "Baltimore Orioles")]),
    ("DAJLB-SHO", [("Nico Hoerner", "Chicago Cubs"), ("Dansby Swanson", "Chicago Cubs")]),
    ("DAJLB-SMU", [("Will Smith", "Los Angeles Dodgers"), ("Max Muncy", "Los Angeles Dodgers")]),
    ("DAJLB-ST", [("Kyle Schwarber", "Philadelphia Phillies"), ("Trea Turner", "Philadelphia Phillies")]),
    ("DAJLB-TRJ", [("Mike Trout", "Angels"), ("Reggie Jackson", "California Angels")]),
    ("DAJLB-TST", [("Trea Turner", "Philadelphia Phillies"), ("Bryson Stott", "Philadelphia Phillies")]),
    ("DAJLB-WA", [("Pete Alonso", "New York Mets"), ("David Wright", "New York Mets")]),
    ("DAJLB-WON", [("Anthony Volpe", "New York Yankees"), ("Anthony Rizzo", "New York Yankees")]),
    ("DAJLB-YCH", [("Christian Yelich", "Milwaukee Brewers"), ("Jackson Chourio", "Milwaukee Brewers")]),
    ("DAJLB-YMO", [("Robin Yount", "Milwaukee Brewers"), ("Paul Molitor", "Milwaukee Brewers")]),
]

# MLB Authenticated Relic Autograph Cards (18 cards)
MLBRA_RAW = [
    ("MLBRA-AN", "Aaron Nola", "Philadelphia Phillies"),
    ("MLBRA-BN", "Brandon Nimmo", "New York Mets"),
    ("MLBRA-CC", "Corbin Carroll", "Arizona Diamondbacks"),
    ("MLBRA-CY", "Christian Yelich", "Milwaukee Brewers"),
    ("MLBRA-FL", "Francisco Lindor", "New York Mets"),
    ("MLBRA-FTJ", "Fernando Tatis Jr.", "San Diego Padres"),
    ("MLBRA-ICH", "Ichiro", "Miami Marlins"),
    ("MLBRA-JA", "Jose Altuve", "Houston Astros"),
    ("MLBRA-JM", "Joe Mauer", "Minnesota Twins"),
    ("MLBRA-JRE", "J.T. Realmuto", "Philadelphia Phillies"),
    ("MLBRA-MIG", "Miguel Cabrera", "Detroit Tigers"),
    ("MLBRA-MM", "Manny Machado", "San Diego Padres"),
    ("MLBRA-NH", "Nico Hoerner", "Chicago Cubs"),
    ("MLBRA-PA", "Pete Alonso", "New York Mets"),
    ("MLBRA-VLAD", "Vladimir Guerrero Jr.", "Toronto Blue Jays"),
    ("MLBRA-VOT", "Joey Votto", "Cincinnati Reds"),
    ("MLBRA-YA", "Yordan Alvarez", "Houston Astros"),
    ("MLBRA-YD", "Yu Darvish", "San Diego Padres"),
]

# Meaningful Material Relics (80 cards)
MMR_RAW = [
    ("MMR-AB", "Alec Bohm", "Philadelphia Phillies"),
    ("MMR-ABR", "Alex Bregman", "Boston Red Sox"),
    ("MMR-AG", "Adolis Garcia", "Texas Rangers"),
    ("MMR-AJ", "Aaron Judge", "New York Yankees"),
    ("MMR-AM", "Andrew McCutchen", "Pittsburgh Pirates"),
    ("MMR-AP", "Albert Pujols", "St. Louis Cardinals"),
    ("MMR-AR", "Austin Riley", "Atlanta Braves"),
    ("MMR-ARO", "Alex Rodriguez", "New York Yankees"),
    ("MMR-ARU", "Adley Rutschman", "Baltimore Orioles"),
    ("MMR-AV", "Anthony Volpe", "New York Yankees"),
    ("MMR-BH", "Bryce Harper", "Philadelphia Phillies"),
    ("MMR-BW", "Bobby Witt Jr.", "Kansas City Royals"),
    ("MMR-CB", "Craig Biggio", "Houston Astros"),
    ("MMR-CBE", "Cody Bellinger", "New York Yankees"),
    ("MMR-CC", "Corbin Carroll", "Arizona Diamondbacks"),
    ("MMR-CCO", "Carlos Correa", "Minnesota Twins"),
    ("MMR-CJ", "Chipper Jones", "Atlanta Braves"),
    ("MMR-CR", "Cal Ripken Jr.", "Baltimore Orioles"),
    ("MMR-CS", "Chris Sale", "Atlanta Braves"),
    ("MMR-CY", "Christian Yelich", "Milwaukee Brewers"),
    ("MMR-DJ", "Derek Jeter", "New York Yankees"),
    ("MMR-DO", "David Ortiz", "Boston Red Sox"),
    ("MMR-DP", "Dustin Pedroia", "Boston Red Sox"),
    ("MMR-DS", "Dansby Swanson", "Chicago Cubs"),
    ("MMR-ED", "Elly De La Cruz", "Cincinnati Reds"),
    ("MMR-FF", "Freddie Freeman", "Los Angeles Dodgers"),
    ("MMR-FL", "Francisco Lindor", "New York Mets"),
    ("MMR-FT", "Frank Thomas", "Chicago White Sox"),
    ("MMR-FTA", "Fernando Tatis Jr.", "San Diego Padres"),
    ("MMR-GC", "Gerrit Cole", "New York Yankees"),
    ("MMR-GH", "Gunnar Henderson", "Baltimore Orioles"),
    ("MMR-I", "Ichiro", "Seattle Mariners"),
    ("MMR-JA", "Jose Altuve", "Houston Astros"),
    ("MMR-JB", "Jeff Bagwell", "Houston Astros"),
    ("MMR-JC", "Jackson Chourio", "Milwaukee Brewers"),
    ("MMR-JCA", "Junior Caminero", "Tampa Bay Rays"),
    ("MMR-JCH", "Jazz Chisholm Jr.", "New York Yankees"),
    ("MMR-JH", "Jackson Holliday", "Baltimore Orioles"),
    ("MMR-JHL", "Jung Hoo Lee", "San Francisco Giants"),
    ("MMR-JM", "Jackson Merrill", "San Diego Padres"),
    ("MMR-JR", "Jose Ramirez", "Cleveland Guardians"),
    ("MMR-JRO", "Julio Rodriguez", "Seattle Mariners"),
    ("MMR-JS", "Juan Soto", "New York Mets"),
    ("MMR-JV", "Joey Votto", "Cincinnati Reds"),
    ("MMR-JW", "James Wood", "Washington Nationals RC"),
    ("MMR-KB", "Kris Bryant", "Colorado Rockies"),
    ("MMR-KM", "Ketel Marte", "Arizona Diamondbacks"),
    ("MMR-KP", "Kirby Puckett", "Minnesota Twins"),
    ("MMR-LB", "Lawrence Butler", "Oakland Athletics"),
    ("MMR-LR", "Luis Robert Jr.", "Chicago White Sox"),
    ("MMR-MB", "Mookie Betts", "Los Angeles Dodgers"),
    ("MMR-MM", "Manny Machado", "San Diego Padres"),
    ("MMR-MO", "Matt Olson", "Atlanta Braves"),
    ("MMR-MP", "Mike Piazza", "Los Angeles Dodgers"),
    ("MMR-MR", "Manny Ramirez", "Boston Red Sox"),
    ("MMR-MT", "Mike Trout", "Angels"),
    ("MMR-MW", "Masyn Winn", "St. Louis Cardinals"),
    ("MMR-MY", "Mike Yastrzemski", "San Francisco Giants"),
    ("MMR-NA", "Nolan Arenado", "St. Louis Cardinals"),
    ("MMR-OA", "Ozzie Albies", "Atlanta Braves"),
    ("MMR-PA", "Pete Alonso", "New York Mets"),
    ("MMR-PC", "Pete Crow-Armstrong", "Chicago Cubs"),
    ("MMR-PR", "Pete Rose", "Cincinnati Reds"),
    ("MMR-RA", "Ronald Acuna Jr.", "Atlanta Braves"),
    ("MMR-RAR", "Randy Arozarena", "Seattle Mariners"),
    ("MMR-RD", "Rafael Devers", "Boston Red Sox"),
    ("MMR-RG", "Riley Greene", "Detroit Tigers"),
    ("MMR-RL", "Royce Lewis", "Minnesota Twins"),
    ("MMR-SP", "Salvador Perez", "Kansas City Royals"),
    ("MMR-SS", "Spencer Strider", "Atlanta Braves"),
    ("MMR-SSO", "Sammy Sosa", "Chicago Cubs"),
    ("MMR-SSU", "Seiya Suzuki", "Chicago Cubs"),
    ("MMR-TH", "Teoscar Hernandez", "Los Angeles Dodgers"),
    ("MMR-TT", "Trea Turner", "Philadelphia Phillies"),
    ("MMR-VG", "Vladimir Guerrero Jr.", "Toronto Blue Jays"),
    ("MMR-YA", "Yordan Alvarez", "Houston Astros"),
]

# Museum Quality Cut Signatures (16 cards)
MQCS_RAW = [
    ("MQCS-BD", "Bobby Doerr", "Boston Red Sox"),
    ("MQCS-BF", "Bob Feller", "Cleveland"),
    ("MQCS-DS", "Duke Snider", "Brooklyn Dodgers"),
    ("MQCS-EB", "Ernie Banks", "Chicago Cubs"),
    ("MQCS-GK", "George Kell", "Detroit Tigers"),
    ("MQCS-HK", "Harmon Killebrew", "Minnesota Twins"),
    ("MQCS-JM", "Johnny Mize", "New York Yankees"),
    ("MQCS-LB", "Lou Brock", "St. Louis Cardinals"),
    ("MQCS-MI", "Monte Irvin", "New York Giants"),
    ("MQCS-MM", "Mickey Mantle", "New York Yankees"),
    ("MQCS-PR", "Bob Gibson", "St. Louis Cardinals"),
    ("MQCS-SM", "Stan Musial", "St. Louis Cardinals"),
    ("MQCS-TW", "Ted Williams", "Boston Red Sox"),
    ("MQCS-WF", "Whitey Ford", "New York Yankees"),
    ("MQCS-WM", "Willie Mays", "San Francisco Giants"),
    ("MQCS-WS", "Warren Spahn", "Milwaukee Braves"),
]

# Museum Quality Cut Signature Relics (12 cards)
MCSR_RAW = [
    ("MCSR-EB", "Ernie Banks", "Chicago Cubs"),
    ("MCSR-HA", "Hank Aaron", "Atlanta Braves"),
    ("MCSR-HW", "Honus Wagner", "Pittsburgh Pirates"),
    ("MCSR-JD", "Joe DiMaggio", "New York Yankees"),
    ("MCSR-JM", "Johnny Mize", "St. Louis Cardinals"),
    ("MCSR-MM", "Mickey Mantle", "New York Yankees"),
    ("MCSR-MO", "Mel Ott", "New York Giants"),
    ("MCSR-RH", "Rogers Hornsby", "St. Louis Cardinals"),
    ("MCSR-RM", "Roger Maris", "New York Yankees"),
    ("MCSR-TS", "Tris Speaker", "Boston Red Sox"),
    ("MCSR-TW", "Ted Williams", "Boston Red Sox"),
    ("MCSR-WM", "Willie Mays", "San Francisco Giants"),
    ("MCSR-YB", "Yogi Berra", "New York Yankees"),
]

# Four Player Primary Pieces Quad Relics (10 cards) -- co_players (4 per card)
FPQR_RAW = [
    ("FPQR-AORA", [("Austin Riley", "Atlanta Braves"), ("Ozzie Albies", "Atlanta Braves"), ("Matt Olson", "Atlanta Braves"), ("Ronald Acuna Jr.", "Atlanta Braves")]),
    ("FPQR-BCLK", [("Byron Buxton", "Minnesota Twins"), ("Carlos Correa", "Minnesota Twins"), ("Royce Lewis", "Minnesota Twins"), ("Brooks Lee", "Minnesota Twins")]),
    ("FPQR-BFHO", [("Teoscar Hernandez", "Los Angeles Dodgers"), ("Shohei Ohtani", "Los Angeles Dodgers"), ("Freddie Freeman", "Los Angeles Dodgers"), ("Mookie Betts", "Los Angeles Dodgers")]),
    ("FPQR-HSTB", [("Alec Bohm", "Philadelphia Phillies"), ("Bryce Harper", "Philadelphia Phillies"), ("Kyle Schwarber", "Philadelphia Phillies"), ("Trea Turner", "Philadelphia Phillies")]),
    ("FPQR-JCDV", [("Jasson Dominguez", "New York Yankees"), ("Aaron Judge", "New York Yankees"), ("Gerrit Cole", "New York Yankees"), ("Anthony Volpe", "New York Yankees")]),
    ("FPQR-LSAN", [("Francisco Lindor", "New York Mets"), ("Juan Soto", "New York Mets"), ("Pete Alonso", "New York Mets"), ("Brandon Nimmo", "New York Mets")]),
    ("FPQR-RHHC", [("Jackson Holliday", "Baltimore Orioles"), ("Colton Cowser", "Baltimore Orioles"), ("Adley Rutschman", "Baltimore Orioles"), ("Gunnar Henderson", "Baltimore Orioles")]),
    ("FPQR-SCST", [("Seiya Suzuki", "Chicago Cubs"), ("Dansby Swanson", "Chicago Cubs"), ("Kyle Tucker", "Chicago Cubs"), ("Pete Crow-Armstrong", "Chicago Cubs")]),
    ("FPQR-TBJA", [("Mookie Betts", "Los Angeles Dodgers"), ("Aaron Judge", "New York Yankees"), ("Ronald Acuna Jr.", "Atlanta Braves"), ("Mike Trout", "Angels")]),
    ("FPQR-TMMB", [("Xander Bogaerts", "San Diego Padres"), ("Fernando Tatis Jr.", "San Diego Padres"), ("Manny Machado", "San Diego Padres"), ("Jackson Merrill", "San Diego Padres")]),
]

# Dual Player Primary Pieces Quad Relics (10 cards) -- co_players
DPQR_RAW = [
    ("DPQR-FB", [("Freddie Freeman", "Los Angeles Dodgers"), ("Mookie Betts", "Los Angeles Dodgers")]),
    ("DPQR-GR", [("Ken Griffey Jr.", "Seattle Mariners"), ("Julio Rodriguez", "Seattle Mariners")]),
    ("DPQR-GT", [("Fernando Tatis Jr.", "San Diego Padres"), ("Tony Gwynn", "San Diego Padres")]),
    ("DPQR-JA", [("Chipper Jones", "Atlanta Braves"), ("Ronald Acuna Jr.", "Atlanta Braves")]),
    ("DPQR-JJ", [("Derek Jeter", "New York Yankees"), ("Aaron Judge", "New York Yankees")]),
    ("DPQR-LD", [("Elly De La Cruz", "Cincinnati Reds"), ("Barry Larkin", "Cincinnati Reds")]),
    ("DPQR-MS", [("Paul Skenes", "Pittsburgh Pirates"), ("Andrew McCutchen", "Pittsburgh Pirates")]),
    ("DPQR-PM", [("Joe Mauer", "Minnesota Twins"), ("Kirby Puckett", "Minnesota Twins")]),
    ("DPQR-RH", [("Cal Ripken Jr.", "Baltimore Orioles"), ("Gunnar Henderson", "Baltimore Orioles")]),
    ("DPQR-UH", [("Bryce Harper", "Philadelphia Phillies"), ("Chase Utley", "Philadelphia Phillies")]),
]

# Dual Player Primary Pieces Quad Relics Legends (8 cards) -- co_players
DPQRL_RAW = [
    ("DPQRL-JH", [("Rickey Henderson", "Oakland Athletics"), ("Reggie Jackson", "Oakland Athletics")]),
    ("DPQRL-LV", [("Joey Votto", "Cincinnati Reds"), ("Barry Larkin", "Cincinnati Reds")]),
    ("DPQRL-MA", [("Hank Aaron", "Atlanta Braves"), ("Willie Mays", "San Francisco Giants")]),
    ("DPQRL-MG", [("Willie Mays", "San Francisco Giants"), ("Ken Griffey Jr.", "Seattle Mariners")]),
    ("DPQRL-MJ", [("Chipper Jones", "Atlanta Braves"), ("Dale Murphy", "Atlanta Braves")]),
    ("DPQRL-OR", [("Manny Ramirez", "Boston Red Sox"), ("David Ortiz", "Boston Red Sox")]),
    ("DPQRL-PM", [("Yadier Molina", "St. Louis Cardinals"), ("Albert Pujols", "St. Louis Cardinals")]),
    ("DPQRL-PW", [("Mike Piazza", "New York Mets"), ("David Wright", "New York Mets")]),
    ("DPQRL-SS", [("Sammy Sosa", "Chicago Cubs"), ("Ryne Sandberg", "Chicago Cubs")]),
    ("DPQRL-SU", [("Mike Schmidt", "Philadelphia Phillies"), ("Chase Utley", "Philadelphia Phillies")]),
]


# ── Build logic ───────────────────────────────────────────────────────────────

def build_single_cards(raw: list[tuple[str, str, str]]) -> list[dict]:
    """Build card dicts from (card_number, name, team) tuples."""
    cards = []
    for num, name, team in raw:
        clean_name, is_rookie = parse_rc(name)
        clean_team, _ = parse_rc(team)  # strip RC from team string like "New York Mets RC"
        cards.append({
            "card_number": num,
            "player": fix_name(clean_name),
            "team": fix_team(clean_team),
            "is_rookie": is_rookie,
            "subset": None,
        })
    return cards


def build_multi_cards(raw: list[tuple[str, list[tuple[str, str]]]]) -> list[dict]:
    """Build card dicts from multi-player (card_number, [(name, team), ...]) tuples.
    Each player gets their own card entry with the same card_number so seed.ts
    detects them as co-players."""
    cards = []
    for num, player_list in raw:
        for name, team in player_list:
            clean_name, is_rookie = parse_rc(name)
            clean_team, _ = parse_rc(team)
            cards.append({
                "card_number": num,
                "player": fix_name(clean_name),
                "team": fix_team(clean_team),
                "is_rookie": is_rookie,
                "subset": None,
            })
    return cards


# No parallels for this set
NO_PARALLELS: list[dict] = []

SECTIONS: list[tuple[str, list[dict]]] = [
    ("Base Set", build_single_cards(BASE_SET_RAW)),
    ("Canvas Collection Original Player Autographs", build_single_cards(CCOPA_RAW)),
    ("Archival Autographs", build_single_cards(AA_RAW)),
    ("Atelier Autographed Book Cards", build_single_cards(AABC_RAW)),
    ("Showpieces Autographs", build_single_cards(SA_RAW)),
    ("Dual On Card Autographs", build_multi_cards(DA_RAW)),
    ("Triple On Card Autographs", build_multi_cards(TA_RAW)),
    ("Museum Framed Autographs", build_single_cards(FMA_RAW)),
    ("Framed HOF Autographs", build_single_cards(HOF_RAW)),
    ("Retrospective Signatures", build_single_cards(RS_RAW)),
    ("Museum Framed Autograph Patch Cards", build_single_cards(MFAP_RAW)),
    ("Museum Framed Dual Autograph Patch Book Cards", build_multi_cards(MFDAP_RAW)),
    ("Momentous Material Jumbo Patch Autographs", build_single_cards(MMJPA_RAW)),
    ("Momentous Material Dual Jumbo Patch Autograph Book Cards", build_multi_cards(MMDPA_RAW)),
    ("Single Player Signature Swatches Dual Relic Autographs", build_single_cards(SPDRA_RAW)),
    ("Single Player Signature Swatches Triple Relic Autographs", build_single_cards(SPTRA_RAW)),
    ("Single Player Signature Swatches Quad Relic Autographs", build_single_cards(SPQRA_RAW)),
    ("Autographed Jumbo Lumber Bat Relics", build_single_cards(AJBR_RAW)),
    ("Dual Autographed Jumbo Lumber Bat Relics Book Cards", build_multi_cards(DAJLB_RAW)),
    ("MLB Authenticated Relic Autograph Cards", build_single_cards(MLBRA_RAW)),
    ("Meaningful Material Relics", build_single_cards(MMR_RAW)),
    ("Museum Quality Cut Signatures", build_single_cards(MQCS_RAW)),
    ("Museum Quality Cut Signature Relics", build_single_cards(MCSR_RAW)),
    ("Four Player Primary Pieces Quad Relics", build_multi_cards(FPQR_RAW)),
    ("Dual Player Primary Pieces Quad Relics", build_multi_cards(DPQR_RAW)),
    ("Dual Player Primary Pieces Quad Relics Legends", build_multi_cards(DPQRL_RAW)),
]


# ── Player aggregation ────────────────────────────────────────────────────────

def main() -> None:
    sections_out: list[dict] = []
    players_map: dict[str, dict] = {}  # keyed by player.lower()

    for section_name, cards in SECTIONS:
        sections_out.append({
            "insert_set": section_name,
            "parallels": NO_PARALLELS,
            "cards": cards,
        })

        for card in cards:
            key = card["player"].lower()
            if key not in players_map:
                players_map[key] = {
                    "player": card["player"],
                    "appearances": [],
                    "insert_sets_seen": set(),
                }
            entry = players_map[key]
            entry["appearances"].append({
                "insert_set": section_name,
                "card_number": card["card_number"],
                "team": card["team"],
                "is_rookie": card["is_rookie"],
                "subset_tag": card.get("subset"),
                "parallels": NO_PARALLELS,
            })
            entry["insert_sets_seen"].add(section_name)

    # Build player list with stats
    players_out: list[dict] = []
    for entry in sorted(players_map.values(), key=lambda e: e["player"]):
        unique_cards = len(entry["appearances"])
        total_print_run = 0  # no parallels
        one_of_ones = 0
        insert_sets = len(entry["insert_sets_seen"])

        players_out.append({
            "player": entry["player"],
            "appearances": entry["appearances"],
            "stats": {
                "unique_cards": unique_cards,
                "total_print_run": total_print_run,
                "one_of_ones": one_of_ones,
                "insert_sets": insert_sets,
            },
        })

    output = {
        "set_name": SET_NAME,
        "sport": SPORT,
        "season": SEASON,
        "league": LEAGUE,
        "sections": sections_out,
        "players": players_out,
    }

    total_cards = sum(len(s["cards"]) for s in sections_out)
    print(f"Sections: {len(sections_out)}")
    print(f"Total cards: {total_cards}")
    print(f"Unique players: {len(players_out)}")

    out_path = "museum_collection_baseball_2025_parsed.json"
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"Written to {out_path}")


if __name__ == "__main__":
    main()
