"""
Seed: 2026 Topps Finest Baseball — Full checklist (~1,122 cards).
350 base (4 tiers), 13 inserts, 8 auto subsets, 1 dual auto, 1 auto-relic.
Three-format set (Hobby + FDI + Mega). Pack odds deferred.
Usage: python3 scripts/seed_finest_baseball_2026.py
"""
import sqlite3, os, json, re, unicodedata

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "the-c-list.db")
db = sqlite3.connect(DB_PATH)
db.execute("PRAGMA journal_mode=WAL")
db.execute("PRAGMA foreign_keys=ON")

box_config = json.dumps({
    "hobby": {"cards_per_pack": 10, "packs_per_box": 6, "boxes_per_case": None, "autos_per_box": 2, "notes": "Per box: 2 autographs"},
    "first_day_issue": {"cards_per_pack": 10, "packs_per_box": 6, "boxes_per_case": None, "autos_per_box": 2, "notes": "Per box: 2 autographs"},
    "mega": {"cards_per_pack": 6, "packs_per_box": 8, "boxes_per_case": None, "notes": "Exclusive Mini Diamond parallels"},
})
pack_odds = json.dumps({"hobby": {}, "first_day_issue": {}, "mega": {}})

db.execute("""
    INSERT INTO sets (name, sport, season, tier, slug, is_visible,
                      sample_image_url, release_date, box_config, pack_odds, created_at)
    VALUES ('2026 Topps Finest Baseball', 'Baseball', '2026', 'Chrome',
            '2026-topps-finest-baseball', 1,
            '/sets/2026-topps-finest-baseball.jpg', '2026-06-08', ?, ?, '2026-06-08T12:00:00Z')
""", (box_config, pack_odds))
SET_ID = db.execute("SELECT last_insert_rowid()").fetchone()[0]
print(f"Created set ID: {SET_ID}")

def slugify(t):
    s = unicodedata.normalize('NFKD', t).encode('ascii', 'ignore').decode('ascii')
    s = s.lower().strip(); s = re.sub(r'[^\w\s-]', '', s); s = re.sub(r'[\s_]+', '-', s)
    return re.sub(r'-+', '-', s).strip('-')

_sc = {}
def goc(name, role="athlete"):
    name = name.strip()
    row = db.execute("SELECT id FROM players WHERE set_id = ? AND name = ?", (SET_ID, name)).fetchone()
    if row: return row[0]
    slug = slugify(name)
    if not _sc:
        for r in db.execute("SELECT slug FROM players WHERE set_id = ? AND slug IS NOT NULL", (SET_ID,)).fetchall():
            _sc[r[0]] = True
    c = slug; i = 2
    while c in _sc: c = f"{slug}-{i}"; i += 1
    _sc[c] = True
    db.execute("INSERT INTO players (set_id, name, slug, unique_cards, total_print_run, one_of_ones, insert_set_count, subject_role) VALUES (?, ?, ?, 0, 0, 0, 0, ?)",
               (SET_ID, name, c, role))
    return db.execute("SELECT last_insert_rowid()").fetchone()[0]

def ais(name, is_auto=False):
    db.execute("INSERT INTO insert_sets (set_id, name, is_autograph) VALUES (?, ?, ?)", (SET_ID, name, 1 if is_auto else 0))
    return db.execute("SELECT last_insert_rowid()").fetchone()[0]

def ac(is_id, cards, default_role="athlete"):
    for c in cards:
        num, name, team = c[0], c[1], c[2]
        rc = c[3] if len(c) > 3 else False
        role = c[4] if len(c) > 4 else default_role
        pid = goc(name, role)
        db.execute("INSERT INTO player_appearances (player_id, insert_set_id, card_number, is_rookie, team) VALUES (?, ?, ?, ?, ?)",
                   (pid, is_id, str(num), 1 if rc else 0, team))

def ad(is_id, cards):
    for num, n1, n2 in cards:
        p1, p2 = goc(n1), goc(n2)
        db.execute("INSERT INTO player_appearances (player_id, insert_set_id, card_number, is_rookie, team) VALUES (?, ?, ?, 0, NULL)", (p1, is_id, str(num)))
        a = db.execute("SELECT last_insert_rowid()").fetchone()[0]
        db.execute("INSERT INTO appearance_co_players (appearance_id, co_player_id) VALUES (?, ?)", (a, p2))

def ins(name, cards, is_auto=False, default_role="athlete"):
    is_id = ais(name, is_auto)
    ac(is_id, cards, default_role)
    print(f"  {name}: {len(cards)} cards")
    return is_id

R = True; F = False

# ═══ BASE COMMON (100) ══════════════════════════════════════════════════════
ins("Base Common", [
(1,"Jac Caglianone","Kansas City Royals",R),(2,"Jacob Wilson","Athletics",F),(3,"Tatsuya Imai","Houston Astros",R),(4,"Ketel Marte","Arizona Diamondbacks",F),(5,"Munetaka Murakami","Chicago White Sox",R),(6,"Konnor Griffin","Pittsburgh Pirates",R),(7,"Bobby Witt Jr.","Kansas City Royals",F),(8,"Jose Altuve","Houston Astros",F),(9,"Justin Crawford","Philadelphia Phillies",R),(10,"Paul Skenes","Pittsburgh Pirates",F),
(11,"Roki Sasaki","Los Angeles Dodgers",F),(12,"Max Fried","New York Yankees",F),(13,"Julio Rodriguez","Seattle Mariners",F),(14,"Kyle Tucker","Los Angeles Dodgers",F),(15,"JJ Wetherholt","St. Louis Cardinals",R),(16,"Samuel Basallo","Baltimore Orioles",R),(17,"Corbin Carroll","Arizona Diamondbacks",F),(18,"Juan Soto","New York Mets",F),(19,"Rafael Devers","San Francisco Giants",F),(20,"Jhostynxon Garcia","Pittsburgh Pirates",R),
(21,"Jacob deGrom","Texas Rangers",F),(22,"Ronald Acuna Jr.","Atlanta Braves",F),(23,"Christian Moore","Angels",R),(24,"Carson Williams","Tampa Bay Rays",R),(25,"Byron Buxton","Minnesota Twins",F),(26,"Yoshinobu Yamamoto","Los Angeles Dodgers",F),(27,"Fernando Tatis Jr.","San Diego Padres",F),(28,"Matt Olson","Atlanta Braves",F),(29,"Garrett Crochet","Boston Red Sox",F),(30,"Colson Montgomery","Chicago White Sox",R),
(31,"Trea Turner","Philadelphia Phillies",F),(32,"Giancarlo Stanton","New York Yankees",F),(33,"Cal Raleigh","Seattle Mariners",F),(34,"Kazuma Okamoto","Toronto Blue Jays",R),(35,"Chase DeLauter","Cleveland Guardians",R),(36,"Bo Bichette","New York Mets",F),(37,"Brandon Sproat","Milwaukee Brewers",R),(38,"Zach Neto","Angels",R),(39,"Sal Stewart","Cincinnati Reds",R),(40,"Dylan Crews","Washington Nationals",F),
(41,"Manny Machado","San Diego Padres",F),(42,"Carlos Correa","Houston Astros",F),(43,"Joe Ryan","Minnesota Twins",F),(44,"Drake Baldwin","Atlanta Braves",F),(45,"Mookie Betts","Los Angeles Dodgers",F),(46,"Oneil Cruz","Pittsburgh Pirates",F),(47,"Junior Caminero","Tampa Bay Rays",F),(48,"Justin Verlander","Detroit Tigers",F),(49,"Christian Yelich","Milwaukee Brewers",F),(50,"Shohei Ohtani","Los Angeles Dodgers",F),
(51,"Gunnar Henderson","Baltimore Orioles",F),(52,"Roman Anthony","Boston Red Sox",R),(53,"Drew Gilbert","San Francisco Giants",R),(54,"Kyle Teel","Chicago White Sox",R),(55,"Tarik Skubal","Detroit Tigers",F),(56,"Connelly Early","Boston Red Sox",R),(57,"Cole Young","Seattle Mariners",R),(58,"Mike Trout","Angels",F),(59,"Carson Benge","New York Mets",R),(60,"Alex Bregman","Chicago Cubs",F),
(61,"Jose Ramirez","Cleveland Guardians",F),(62,"Nolan McLean","New York Mets",R),(63,"Corey Seager","Texas Rangers",F),(64,"Pete Alonso","Baltimore Orioles",F),(65,"Jung Hoo Lee","San Francisco Giants",F),(66,"Jackson Chourio","Milwaukee Brewers",F),(67,"Wyatt Langford","Texas Rangers",F),(68,"Francisco Lindor","New York Mets",F),(69,"Elly De La Cruz","Cincinnati Reds",F),(70,"Jackson Merrill","San Diego Padres",F),
(71,"Pete Crow-Armstrong","Chicago Cubs",F),(72,"Jonah Tong","New York Mets",R),(73,"Bryce Harper","Philadelphia Phillies",F),(74,"Kevin McGonigle","Detroit Tigers",R),(75,"Colby Thomas","Athletics",R),(76,"Chase Burns","Cincinnati Reds",R),(77,"Nolan Arenado","Arizona Diamondbacks",F),(78,"Josh Naylor","Seattle Mariners",F),(79,"Owen Caissie","Miami Marlins",R),(80,"Brady House","Washington Nationals",R),
(81,"Sandy Alcantara","Miami Marlins",F),(82,"Jacob Misiorowski","Milwaukee Brewers",R),(83,"James Wood","Washington Nationals",F),(84,"Masyn Winn","St. Louis Cardinals",F),(85,"Dylan Beavers","Baltimore Orioles",R),(86,"Andrew Painter","Philadelphia Phillies",R),(87,"Kyle Karros","Colorado Rockies",R),(88,"Nick Kurtz","Athletics",F),(89,"Cam Schlittler","New York Yankees",R),(90,"Bubba Chandler","Pittsburgh Pirates",R),
(91,"Kyle Schwarber","Philadelphia Phillies",F),(92,"Yordan Alvarez","Houston Astros",F),(93,"Harry Ford","Washington Nationals",R),(94,"Cade Horton","Chicago Cubs",F),(95,"Salvador Perez","Kansas City Royals",F),(96,"Trey Yesavage","Toronto Blue Jays",R),(97,"George Springer","Toronto Blue Jays",F),(98,"Bryce Eldridge","San Francisco Giants",R),(99,"Aaron Judge","New York Yankees",F),(100,"Vladimir Guerrero Jr.","Toronto Blue Jays",F),
])

# ═══ BASE UNCOMMON (100) ═════════════════════════════════════════════════════
ins("Base Uncommon", [
(101,"Jac Caglianone","Kansas City Royals",R),(102,"Bryce Harper","Philadelphia Phillies",F),(103,"Jeferson Quero","Milwaukee Brewers",R),(104,"Jackson Holliday","Baltimore Orioles",F),(105,"Roman Anthony","Boston Red Sox",R),(106,"Nico Hoerner","Chicago Cubs",F),(107,"Bobby Witt Jr.","Kansas City Royals",F),(108,"Riley Greene","Detroit Tigers",F),(109,"Dylan Cease","Toronto Blue Jays",F),(110,"Paul Skenes","Pittsburgh Pirates",F),
(111,"Matt Chapman","San Francisco Giants",F),(112,"Jose Altuve","Houston Astros",F),(113,"Xander Bogaerts","San Diego Padres",F),(114,"Mike Trout","Angels",F),(115,"Nolan McLean","New York Mets",R),(116,"Carson Benge","New York Mets",R),(117,"Edgar Quero","Chicago White Sox",F),(118,"Rafael Devers","San Francisco Giants",F),(119,"Juan Soto","New York Mets",F),(120,"Yoshinobu Yamamoto","Los Angeles Dodgers",F),
(121,"Corbin Burnes","Arizona Diamondbacks",F),(122,"Salvador Perez","Kansas City Royals",F),(123,"Justin Crawford","Philadelphia Phillies",R),(124,"Carter Jensen","Kansas City Royals",R),(125,"Byron Buxton","Minnesota Twins",F),(126,"Brent Rooker","Athletics",F),(127,"JJ Wetherholt","St. Louis Cardinals",R),(128,"Ozzie Albies","Atlanta Braves",F),(129,"Mookie Betts","Los Angeles Dodgers",F),(130,"Julio Rodriguez","Seattle Mariners",F),
(131,"Luke Keaschall","Minnesota Twins",F),(132,"Steven Kwan","Cleveland Guardians",F),(133,"Denzer Guzman","Angels",R),(134,"Jonah Tong","New York Mets",R),(135,"Deyvison De Los Santos","Miami Marlins",R),(136,"Trey Yesavage","Toronto Blue Jays",R),(137,"Chris Sale","Atlanta Braves",F),(138,"Bryce Eldridge","San Francisco Giants",R),(139,"Konnor Griffin","Pittsburgh Pirates",R),(140,"Brice Matthews","Houston Astros",R),
(141,"C.J. Kayfus","Cleveland Guardians",R),(142,"Payton Tolle","Boston Red Sox",F),(143,"Jakob Marsee","Miami Marlins",R),(144,"Luis Morales","Athletics",R),(145,"Munetaka Murakami","Chicago White Sox",R),(146,"Yordan Alvarez","Houston Astros",F),(147,"Kevin McGonigle","Detroit Tigers",R),(148,"MacKenzie Gore","Texas Rangers",F),(149,"Geraldo Perdomo","Arizona Diamondbacks",F),(150,"Shohei Ohtani","Los Angeles Dodgers",F),
(151,"Bryan Reynolds","Pittsburgh Pirates",F),(152,"Ryan Ritter","Colorado Rockies",R),(153,"Corbin Carroll","Arizona Diamondbacks",F),(154,"Ian Seymour","Tampa Bay Rays",R),(155,"Hunter Goodman","Colorado Rockies",F),(156,"Randy Arozarena","Seattle Mariners",F),(157,"Fernando Tatis Jr.","San Diego Padres",F),(158,"Mason Miller","San Diego Padres",F),(159,"Francisco Lindor","New York Mets",F),(160,"Zack Wheeler","Philadelphia Phillies",F),
(161,"Cody Bellinger","New York Yankees",F),(162,"Elly De La Cruz","Cincinnati Reds",F),(163,"Freddie Freeman","Los Angeles Dodgers",F),(164,"James Wood","Washington Nationals",F),(165,"Logan Gilbert","Seattle Mariners",F),(166,"Samuel Basallo","Baltimore Orioles",R),(167,"Cal Raleigh","Seattle Mariners",F),(168,"Jo Adell","Angels",F),(169,"Hunter Greene","Cincinnati Reds",F),(170,"Colson Montgomery","Chicago White Sox",R),
(171,"CJ Abrams","Washington Nationals",F),(172,"Logan Webb","San Francisco Giants",F),(173,"Jonathan Aranda","Tampa Bay Rays",F),(174,"Masyn Winn","St. Louis Cardinals",F),(175,"Jackson Chourio","Milwaukee Brewers",F),(176,"Nick Kurtz","Athletics",F),(177,"Hunter Barco","Pittsburgh Pirates",R),(178,"Wyatt Langford","Texas Rangers",F),(179,"Sal Stewart","Cincinnati Reds",R),(180,"Tarik Skubal","Detroit Tigers",F),
(181,"Jazz Chisholm Jr.","New York Yankees",F),(182,"Bubba Chandler","Pittsburgh Pirates",R),(183,"Gunnar Henderson","Baltimore Orioles",F),(184,"Jimmy Crooks","St. Louis Cardinals",R),(185,"Freddy Peralta","New York Mets",F),(186,"Brice Turang","Milwaukee Brewers",F),(187,"Ronald Acuna Jr.","Atlanta Braves",F),(188,"Shota Imanaga","Chicago Cubs",F),(189,"Pete Crow-Armstrong","Chicago Cubs",F),(190,"Junior Caminero","Tampa Bay Rays",F),
(191,"Gerrit Cole","New York Yankees",F),(192,"Otto Kemp","Philadelphia Phillies",R),(193,"Kyle Teel","Chicago White Sox",R),(194,"Chase Burns","Cincinnati Reds",R),(195,"Jose Corniell","Texas Rangers",R),(196,"Jacob Misiorowski","Milwaukee Brewers",R),(197,"Alejandro Kirk","Toronto Blue Jays",F),(198,"Jose Ramirez","Cleveland Guardians",F),(199,"Aaron Judge","New York Yankees",F),(200,"Vladimir Guerrero Jr.","Toronto Blue Jays",F),
])

# ═══ BASE RARE (100) ═════════════════════════════════════════════════════════
ins("Base Rare", [
(201,"Jac Caglianone","Kansas City Royals",R),(202,"Ketel Marte","Arizona Diamondbacks",F),(203,"Nathan Eovaldi","Texas Rangers",F),(204,"Luis Robert Jr.","New York Mets",F),(205,"Framber Valdez","Detroit Tigers",F),(206,"Roman Anthony","Boston Red Sox",R),(207,"Bobby Witt Jr.","Kansas City Royals",F),(208,"Cal Raleigh","Seattle Mariners",F),(209,"Jose Altuve","Houston Astros",F),(210,"Paul Skenes","Pittsburgh Pirates",F),
(211,"Bryce Eldridge","San Francisco Giants",R),(212,"Carlos Rodon","New York Yankees",F),(213,"Joe Ryan","Minnesota Twins",F),(214,"Brendan Donovan","Seattle Mariners",F),(215,"Yoshinobu Yamamoto","Los Angeles Dodgers",F),(216,"Noelvi Marte","Cincinnati Reds",F),(217,"Yusei Kikuchi","Angels",F),(218,"Jacob Misiorowski","Milwaukee Brewers",R),(219,"Julio Rodriguez","Seattle Mariners",F),(220,"Francisco Lindor","New York Mets",F),
(221,"Rafael Devers","San Francisco Giants",F),(222,"Michael King","San Diego Padres",F),(223,"Jeremiah Jackson","Baltimore Orioles",R),(224,"Brandon Lowe","Pittsburgh Pirates",F),(225,"Byron Buxton","Minnesota Twins",F),(226,"Cristopher Sanchez","Philadelphia Phillies",F),(227,"Ronald Acuna Jr.","Atlanta Braves",F),(228,"Chase Dollander","Colorado Rockies",F),(229,"Freddie Freeman","Los Angeles Dodgers",F),(230,"Troy Melton","Detroit Tigers",R),
(231,"Seiya Suzuki","Chicago Cubs",F),(232,"Owen Caissie","Miami Marlins",R),(233,"Anthony Volpe","New York Yankees",F),(234,"Ezequiel Tovar","Colorado Rockies",F),(235,"Pete Crow-Armstrong","Chicago Cubs",F),(236,"George Valera","Cleveland Guardians",R),(237,"Bryan Woo","Seattle Mariners",F),(238,"Bryce Harper","Philadelphia Phillies",F),(239,"Jose Ramirez","Cleveland Guardians",F),(240,"Nolan McLean","New York Mets",R),
(241,"Wyatt Langford","Texas Rangers",F),(242,"Masyn Winn","St. Louis Cardinals",F),(243,"Tarik Skubal","Detroit Tigers",F),(244,"Vinnie Pasquantino","Kansas City Royals",F),(245,"Brady House","Washington Nationals",R),(246,"Evan Carter","Texas Rangers",F),(247,"Juan Soto","New York Mets",F),(248,"Jackson Chourio","Milwaukee Brewers",F),(249,"Adley Rutschman","Baltimore Orioles",F),(250,"Shohei Ohtani","Los Angeles Dodgers",F),
(251,"Nick Kurtz","Athletics",F),(252,"Edwin Diaz","Los Angeles Dodgers",F),(253,"James Wood","Washington Nationals",F),(254,"Gunnar Henderson","Baltimore Orioles",F),(255,"Manny Machado","San Diego Padres",F),(256,"Adolis Garcia","Philadelphia Phillies",F),(257,"Daylen Lile","Washington Nationals",F),(258,"Carson Benge","New York Mets",R),(259,"Heriberto Hernandez","Miami Marlins",R),(260,"Luis Arraez","San Francisco Giants",F),
(261,"Yordan Alvarez","Houston Astros",F),(262,"Grant Taylor","Chicago White Sox",R),(263,"Chase Burns","Cincinnati Reds",R),(264,"Samuel Basallo","Baltimore Orioles",R),(265,"Shane Bieber","Toronto Blue Jays",F),(266,"Trey Yesavage","Toronto Blue Jays",R),(267,"Kyle Teel","Chicago White Sox",R),(268,"Konnor Griffin","Pittsburgh Pirates",R),(269,"JJ Wetherholt","St. Louis Cardinals",R),(270,"Willy Adames","San Francisco Giants",F),
(271,"Andrew Abbott","Cincinnati Reds",F),(272,"Bubba Chandler","Pittsburgh Pirates",R),(273,"Elly De La Cruz","Cincinnati Reds",F),(274,"Fernando Tatis Jr.","San Diego Padres",F),(275,"Kevin McGonigle","Detroit Tigers",R),(276,"Didier Fuentes","Atlanta Braves",R),(277,"Parker Messick","Cleveland Guardians",R),(278,"Hunter Brown","Houston Astros",F),(279,"Junior Caminero","Tampa Bay Rays",F),(280,"Ranger Suarez","Boston Red Sox",F),
(281,"Dansby Swanson","Chicago Cubs",F),(282,"Carson Whisenhunt","San Francisco Giants",R),(283,"Jackson Merrill","San Diego Padres",F),(284,"Carter Jensen","Kansas City Royals",R),(285,"Austin Riley","Atlanta Braves",F),(286,"Marcelo Mayer","Boston Red Sox",F),(287,"Andrew Painter","Philadelphia Phillies",R),(288,"Carson Williams","Tampa Bay Rays",R),(289,"Rafael Flores Jr.","Pittsburgh Pirates",R),(290,"Lawrence Butler","Athletics",F),
(291,"Colson Montgomery","Chicago White Sox",R),(292,"Brandon Sproat","Milwaukee Brewers",R),(293,"Nolan Schanuel","Angels",F),(294,"Sal Frelick","Milwaukee Brewers",F),(295,"Munetaka Murakami","Chicago White Sox",R),(296,"Mike Trout","Angels",F),(297,"Corbin Carroll","Arizona Diamondbacks",F),(298,"Ben Rice","New York Yankees",F),(299,"Aaron Judge","New York Yankees",F),(300,"Vladimir Guerrero Jr.","Toronto Blue Jays",F),
])

# ═══ BASE SUPER RARE (50) ═══════════════════════════════════════════════════
ins("Base Super Rare", [
(301,"Jac Caglianone","Kansas City Royals",R),(302,"Willie Mays","San Francisco Giants",F),(303,"Pete Crow-Armstrong","Chicago Cubs",F),(304,"Tarik Skubal","Detroit Tigers",F),(305,"Juan Soto","New York Mets",F),(306,"Cal Ripken Jr.","Baltimore Orioles",F),(307,"Bobby Witt Jr.","Kansas City Royals",F),(308,"Owen Caissie","Miami Marlins",R),(309,"Aaron Judge","New York Yankees",F),(310,"Paul Skenes","Pittsburgh Pirates",F),
(311,"Bryce Harper","Philadelphia Phillies",F),(312,"Albert Pujols","St. Louis Cardinals",F),(313,"Julio Rodriguez","Seattle Mariners",F),(314,"Fernando Tatis Jr.","San Diego Padres",F),(315,"Mookie Betts","Los Angeles Dodgers",F),(316,"Jacob Misiorowski","Milwaukee Brewers",R),(317,"Vladimir Guerrero Jr.","Toronto Blue Jays",F),(318,"Tatsuya Imai","Houston Astros",R),(319,"Travis Bazzana","Cleveland Guardians",R),(320,"Manny Machado","San Diego Padres",F),
(321,"Munetaka Murakami","Chicago White Sox",R),(322,"Nolan McLean","New York Mets",R),(323,"Larry Walker","Colorado Rockies",F),(324,"Francisco Lindor","New York Mets",F),(325,"Byron Buxton","Minnesota Twins",F),(326,"Mike Trout","Angels",F),(327,"JJ Wetherholt","St. Louis Cardinals",R),(328,"Wyatt Langford","Texas Rangers",F),(329,"Junior Caminero","Tampa Bay Rays",F),(330,"Samuel Basallo","Baltimore Orioles",R),
(331,"Elly De La Cruz","Cincinnati Reds",F),(332,"Derek Jeter","New York Yankees",F),(333,"Yoshinobu Yamamoto","Los Angeles Dodgers",F),(334,"Ronald Acuna Jr.","Atlanta Braves",F),(335,"Corbin Carroll","Arizona Diamondbacks",F),(336,"Trey Yesavage","Toronto Blue Jays",R),(337,"Konnor Griffin","Pittsburgh Pirates",R),(338,"Bryce Eldridge","San Francisco Giants",R),(339,"Gunnar Henderson","Baltimore Orioles",F),(340,"Ichiro","Seattle Mariners",F),
(341,"Nick Kurtz","Athletics",F),(342,"Chase Burns","Cincinnati Reds",R),(343,"Kazuma Okamoto","Toronto Blue Jays",R),(344,"Roman Anthony","Boston Red Sox",R),(345,"Chase DeLauter","Cleveland Guardians",R),(346,"Hank Aaron","Atlanta Braves",F),(347,"James Wood","Washington Nationals",F),(348,"Colson Montgomery","Chicago White Sox",R),(349,"Kevin McGonigle","Detroit Tigers",R),(350,"Shohei Ohtani","Los Angeles Dodgers",F),
])

# ═══ INSERT SUBSETS ══════════════════════════════════════════════════════════
ins("Arrivals", [("A-1","Jac Caglianone","Kansas City Royals",R),("A-2","Roman Anthony","Boston Red Sox",R),("A-3","Samuel Basallo","Baltimore Orioles",R),("A-4","Bryce Eldridge","San Francisco Giants",R),("A-5","Chase Burns","Cincinnati Reds",R),("A-6","Bubba Chandler","Pittsburgh Pirates",R),("A-7","Nolan McLean","New York Mets",R),("A-8","Trey Yesavage","Toronto Blue Jays",R),("A-9","Kyle Teel","Chicago White Sox",R),("A-10","Colson Montgomery","Chicago White Sox",R),("A-11","Carson Williams","Tampa Bay Rays",R),("A-12","Cole Young","Seattle Mariners",R),("A-13","Christian Moore","Angels",R),("A-14","Harry Ford","Washington Nationals",R),("A-15","Brady House","Washington Nationals",R),("A-16","Owen Caissie","Miami Marlins",R),("A-17","Sal Stewart","Cincinnati Reds",R),("A-18","Jacob Misiorowski","Milwaukee Brewers",R),("A-19","Jonah Tong","New York Mets",R),("A-20","Dylan Beavers","Baltimore Orioles",R),("A-21","C.J. Kayfus","Cleveland Guardians",R),("A-22","Connelly Early","Boston Red Sox",R),("A-23","Kevin McGonigle","Detroit Tigers",R),("A-24","Chase DeLauter","Cleveland Guardians",R),("A-25","Cam Schlittler","New York Yankees",R),("A-26","Munetaka Murakami","Chicago White Sox",R),("A-27","JJ Wetherholt","St. Louis Cardinals",R),("A-28","Konnor Griffin","Pittsburgh Pirates",R),("A-29","Alex Freeland","Los Angeles Dodgers",R),("A-30","Carson Benge","New York Mets",R)])

ins("Worlds Finest", [("WF-1","Aaron Judge","USA",F),("WF-2","Paul Skenes","USA",F),("WF-3","Tarik Skubal","USA",F),("WF-4","Alex Bregman","USA",F),("WF-5","Clayton Kershaw","USA",F),("WF-6","Gunnar Henderson","USA",F),("WF-7","Kyle Schwarber","USA",F),("WF-8","Pete Crow-Armstrong","USA",F),("WF-9","Roman Anthony","USA",R),("WF-10","Cal Raleigh","USA",F),("WF-11","Bobby Witt Jr.","USA",F),("WF-12","Nolan McLean","USA",R),("WF-13","Bryce Harper","USA",F),("WF-14","Byron Buxton","USA",F),("WF-15","Julio Rodriguez","Dominican Republic",F),("WF-16","Junior Caminero","Dominican Republic",F),("WF-17","Vladimir Guerrero Jr.","Dominican Republic",F),("WF-18","Fernando Tatis Jr.","Dominican Republic",F),("WF-19","Juan Soto","Dominican Republic",F),("WF-20","Manny Machado","Dominican Republic",F),("WF-21","Ketel Marte","Dominican Republic",F),("WF-22","Shohei Ohtani","Japan",F),("WF-23","Yoshinobu Yamamoto","Japan",F),("WF-24","Munetaka Murakami","Japan",R),("WF-25","Seiya Suzuki","Japan",F),("WF-26","Jackson Chourio","Venezuela",F),("WF-27","Ronald Acuna Jr.","Venezuela",F),("WF-28","Salvador Perez","Venezuela",F),("WF-29","Nolan Arenado","Puerto Rico",F),("WF-30","Edwin Diaz","Puerto Rico",F),("WF-31","Randy Arozarena","Mexico",F),("WF-32","Jazz Chisholm Jr.","Great Britain",F),("WF-33","Jac Caglianone","Italy",R),("WF-34","Jung Hoo Lee","Korea",F),("WF-35","Josh Naylor","Canada",F)])

ins("Topps Team Finest", [("TF-1","Paul Skenes","Pittsburgh Pirates",F),("TF-2","Tarik Skubal","Detroit Tigers",F),("TF-3","Yoshinobu Yamamoto","Los Angeles Dodgers",F),("TF-4","Garrett Crochet","Boston Red Sox",F),("TF-5","Max Fried","New York Yankees",F),("TF-6","Edwin Diaz","Los Angeles Dodgers",F),("TF-7","Cal Raleigh","Seattle Mariners",F),("TF-8","Vladimir Guerrero Jr.","Toronto Blue Jays",F),("TF-9","Ketel Marte","Arizona Diamondbacks",F),("TF-10","Jose Ramirez","Cleveland Guardians",F),("TF-11","Bobby Witt Jr.","Kansas City Royals",F),("TF-12","Aaron Judge","New York Yankees",F),("TF-13","Ronald Acuna Jr.","Atlanta Braves",F),("TF-14","Juan Soto","New York Mets",F),("TF-15","Shohei Ohtani","Los Angeles Dodgers",F),("TF-16","Corbin Carroll","Arizona Diamondbacks",F),("TF-17","Julio Rodriguez","Seattle Mariners",F),("TF-18","Elly De La Cruz","Cincinnati Reds",F),("TF-19","Francisco Lindor","New York Mets",F),("TF-20","Nick Kurtz","Athletics",F),("TF-21","Jac Caglianone","Kansas City Royals",R),("TF-22","Roman Anthony","Boston Red Sox",R),("TF-23","Konnor Griffin","Pittsburgh Pirates",R),("TF-24","Jacob Misiorowski","Milwaukee Brewers",R),("TF-25","Samuel Basallo","Baltimore Orioles",R)])

ins("Finest Timelines", [("FT-21","Don Larsen","New York Yankees",F),("FT-22","Kirk Gibson","Los Angeles Dodgers",F),("FT-23","Shohei Ohtani","Los Angeles Dodgers",F),("FT-24","Rickey Henderson","Oakland Athletics",F),("FT-25","Mark McGwire","St. Louis Cardinals",F),("FT-26","Kirby Puckett","Minnesota Twins",F),("FT-27","George Springer","Toronto Blue Jays",F),("FT-28","Albert Pujols","St. Louis Cardinals",F),("FT-29","Ken Griffey Jr.","Cincinnati Reds",F),("FT-30","Kris Bryant","Chicago Cubs",F)])

ins("Smashing Through", [("S-1","Roman Anthony","Boston Red Sox",R),("S-2","Jac Caglianone","Kansas City Royals",R),("S-3","Jacob Misiorowski","Milwaukee Brewers",R),("S-4","Samuel Basallo","Baltimore Orioles",R),("S-5","Konnor Griffin","Pittsburgh Pirates",R),("S-6","Kevin McGonigle","Detroit Tigers",R),("S-7","Francisco Lindor","New York Mets",F),("S-8","Vladimir Guerrero Jr.","Toronto Blue Jays",F),("S-9","Freddie Freeman","Los Angeles Dodgers",F),("S-10","Pete Crow-Armstrong","Chicago Cubs",F),("S-11","Nick Kurtz","Athletics",F),("S-12","Fernando Tatis Jr.","San Diego Padres",F),("S-13","Jose Ramirez","Cleveland Guardians",F),("S-14","Gunnar Henderson","Baltimore Orioles",F),("S-15","Bobby Witt Jr.","Kansas City Royals",F),("S-16","Elly De La Cruz","Cincinnati Reds",F),("S-17","Yoshinobu Yamamoto","Los Angeles Dodgers",F),("S-18","Tarik Skubal","Detroit Tigers",F),("S-19","Aaron Judge","New York Yankees",F),("S-20","Cal Raleigh","Seattle Mariners",F)])

ins("The Man", [("TM-1","Aaron Judge","New York Yankees",F),("TM-2","Shohei Ohtani","Los Angeles Dodgers",F),("TM-3","Paul Skenes","Pittsburgh Pirates",F),("TM-4","Nick Kurtz","Athletics",F),("TM-5","Bobby Witt Jr.","Kansas City Royals",F),("TM-6","Juan Soto","New York Mets",F),("TM-7","Bryce Harper","Philadelphia Phillies",F),("TM-8","Mike Trout","Angels",F),("TM-9","Jac Caglianone","Kansas City Royals",R),("TM-10","Roman Anthony","Boston Red Sox",R)])

ins("Gusto", [("G-1","Roman Anthony","Boston Red Sox",R),("G-2","Jac Caglianone","Kansas City Royals",R),("G-3","Samuel Basallo","Baltimore Orioles",R),("G-4","Jacob Misiorowski","Milwaukee Brewers",R),("G-5","Bryce Eldridge","San Francisco Giants",R),("G-6","Chase Burns","Cincinnati Reds",R),("G-7","Munetaka Murakami","Chicago White Sox",R),("G-8","Nolan McLean","New York Mets",R),("G-9","Trey Yesavage","Toronto Blue Jays",R),("G-10","Nick Kurtz","Athletics",F),("G-11","Cal Raleigh","Seattle Mariners",F),("G-12","Bo Bichette","New York Mets",F),("G-13","Kyle Tucker","Los Angeles Dodgers",F),("G-14","Pete Alonso","Baltimore Orioles",F),("G-15","Corbin Carroll","Arizona Diamondbacks",F),("G-16","Tarik Skubal","Detroit Tigers",F),("G-17","Pete Crow-Armstrong","Chicago Cubs",F),("G-18","Jose Altuve","Houston Astros",F),("G-19","Ronald Acuna Jr.","Atlanta Braves",F),("G-20","Elly De La Cruz","Cincinnati Reds",F)])

ins("Nightmare Fuel", [("NF-1","Bryce Harper","Philadelphia Phillies",F),("NF-2","Aaron Judge","New York Yankees",F),("NF-3","Shohei Ohtani","Los Angeles Dodgers",F),("NF-4","Fernando Tatis Jr.","San Diego Padres",F),("NF-5","Juan Soto","New York Mets",F),("NF-6","Francisco Lindor","New York Mets",F),("NF-7","Mookie Betts","Los Angeles Dodgers",F),("NF-8","Paul Skenes","Pittsburgh Pirates",F),("NF-9","Julio Rodriguez","Seattle Mariners",F),("NF-10","Tarik Skubal","Detroit Tigers",F),("NF-11","Jose Ramirez","Cleveland Guardians",F),("NF-12","Bobby Witt Jr.","Kansas City Royals",F),("NF-13","Ronald Acuna Jr.","Atlanta Braves",F),("NF-14","Elly De La Cruz","Cincinnati Reds",F),("NF-15","Vladimir Guerrero Jr.","Toronto Blue Jays",F),("NF-16","Roman Anthony","Boston Red Sox",R),("NF-17","Jac Caglianone","Kansas City Royals",R),("NF-18","Jacob Misiorowski","Milwaukee Brewers",R),("NF-19","Samuel Basallo","Baltimore Orioles",R),("NF-20","Bryce Eldridge","San Francisco Giants",R)])

ins("Headliners", [("HL-1","Aaron Judge","New York Yankees",F),("HL-2","Shohei Ohtani","Los Angeles Dodgers",F),("HL-3","Paul Skenes","Pittsburgh Pirates",F),("HL-4","Tarik Skubal","Detroit Tigers",F),("HL-5","Cal Raleigh","Seattle Mariners",F),("HL-6","Bryce Harper","Philadelphia Phillies",F),("HL-7","Bobby Witt Jr.","Kansas City Royals",F),("HL-8","Yoshinobu Yamamoto","Los Angeles Dodgers",F),("HL-9","Vladimir Guerrero Jr.","Toronto Blue Jays",F),("HL-10","Munetaka Murakami","Chicago White Sox",R),("HL-11","Mike Trout","Angels",F),("HL-12","Juan Soto","New York Mets",F),("HL-13","Ronald Acuna Jr.","Atlanta Braves",F),("HL-14","Roman Anthony","Boston Red Sox",R),("HL-15","Jac Caglianone","Kansas City Royals",R)])

ins("Aura", [("AU-1","Aaron Judge","New York Yankees",F),("AU-2","Shohei Ohtani","Los Angeles Dodgers",F),("AU-3","Derek Jeter","New York Yankees",F),("AU-4","Ronald Acuna Jr.","Atlanta Braves",F),("AU-5","Elly De La Cruz","Cincinnati Reds",F),("AU-6","Juan Soto","New York Mets",F),("AU-7","Paul Skenes","Pittsburgh Pirates",F),("AU-8","Roman Anthony","Boston Red Sox",R),("AU-9","Jazz Chisholm Jr.","New York Yankees",F),("AU-10","Ken Griffey Jr.","Seattle Mariners",F)])

ins("Finest Forces", [("FIF-1","Freddie Freeman","Los Angeles Dodgers",F),("FIF-2","Jose Altuve","Houston Astros",F),("FIF-3","Manny Machado","San Diego Padres",F),("FIF-4","Bryce Harper","Philadelphia Phillies",F),("FIF-5","Mike Trout","Angels",F),("FIF-6","Ronald Acuna Jr.","Atlanta Braves",F),("FIF-7","Aaron Judge","New York Yankees",F),("FIF-8","Francisco Lindor","New York Mets",F),("FIF-9","Mookie Betts","Los Angeles Dodgers",F),("FIF-10","Paul Skenes","Pittsburgh Pirates",F),("FIF-11","Shohei Ohtani","Los Angeles Dodgers",F),("FIF-12","Yoshinobu Yamamoto","Los Angeles Dodgers",F),("FIF-13","Nolan Ryan","Texas Rangers",F),("FIF-14","Sandy Koufax","Los Angeles Dodgers",F),("FIF-15","Derek Jeter","New York Yankees",F),("FIF-16","Ichiro","Seattle Mariners",F),("FIF-17","Ken Griffey Jr.","Seattle Mariners",F),("FIF-18","Albert Pujols","St. Louis Cardinals",F),("FIF-19","Roberto Clemente","Pittsburgh Pirates",F),("FIF-20","Mickey Mantle","New York Yankees",F),("FIF-21","Babe Ruth","New York Yankees",F),("FIF-22","Willie Mays","San Francisco Giants",F),("FIF-23","Hank Aaron","Milwaukee Braves",F),("FIF-24","David Ortiz","Boston Red Sox",F),("FIF-25","Cal Ripken Jr.","Baltimore Orioles",F)])

ins("Finest Futures", [("FF-1","Roki Sasaki","Los Angeles Dodgers",F),("FF-2","Nick Kurtz","Athletics",F),("FF-3","James Wood","Washington Nationals",F),("FF-4","JJ Wetherholt","St. Louis Cardinals",R),("FF-5","Konnor Griffin","Pittsburgh Pirates",R),("FF-6","Jackson Merrill","San Diego Padres",F),("FF-7","Jacob Wilson","Athletics",F),("FF-8","Wyatt Langford","Texas Rangers",F),("FF-9","Junior Caminero","Tampa Bay Rays",F),("FF-10","Pete Crow-Armstrong","Chicago Cubs",F),("FF-11","Drake Baldwin","Atlanta Braves",F),("FF-12","Kevin McGonigle","Detroit Tigers",R),("FF-13","Christian Moore","Angels",R),("FF-14","Munetaka Murakami","Chicago White Sox",R),("FF-15","Jac Caglianone","Kansas City Royals",R),("FF-16","Roman Anthony","Boston Red Sox",R),("FF-17","Jacob Misiorowski","Milwaukee Brewers",R),("FF-18","Chase Burns","Cincinnati Reds",R),("FF-19","Samuel Basallo","Baltimore Orioles",R),("FF-20","Nolan McLean","New York Mets",R),("FF-21","Bryce Eldridge","San Francisco Giants",R),("FF-22","Trey Yesavage","Toronto Blue Jays",R),("FF-23","Colson Montgomery","Chicago White Sox",R),("FF-24","Bubba Chandler","Pittsburgh Pirates",R),("FF-25","Carson Benge","New York Mets",R)])

ins("Finest Phenoms", [("FP-1","Jac Caglianone","Kansas City Royals",R),("FP-2","Roman Anthony","Boston Red Sox",R),("FP-3","Samuel Basallo","Baltimore Orioles",R),("FP-4","Bryce Eldridge","San Francisco Giants",R),("FP-5","Chase Burns","Cincinnati Reds",R),("FP-6","Bubba Chandler","Pittsburgh Pirates",R),("FP-7","Nolan McLean","New York Mets",R),("FP-8","Trey Yesavage","Toronto Blue Jays",R),("FP-9","Kyle Teel","Chicago White Sox",R),("FP-10","Colson Montgomery","Chicago White Sox",R),("FP-11","Carson Williams","Tampa Bay Rays",R),("FP-12","Cole Young","Seattle Mariners",R),("FP-13","Christian Moore","Angels",R),("FP-14","Alex Freeland","Los Angeles Dodgers",R),("FP-15","Brady House","Washington Nationals",R),("FP-16","Owen Caissie","Miami Marlins",R),("FP-17","Sal Stewart","Cincinnati Reds",R),("FP-18","Jacob Misiorowski","Milwaukee Brewers",R),("FP-19","Konnor Griffin","Pittsburgh Pirates",R),("FP-20","Carson Benge","New York Mets",R),("FP-21","Kevin McGonigle","Detroit Tigers",R),("FP-22","Munetaka Murakami","Chicago White Sox",R),("FP-23","JJ Wetherholt","St. Louis Cardinals",R),("FP-24","Chase DeLauter","Cleveland Guardians",R),("FP-25","Cam Schlittler","New York Yankees",R)])

# ═══ AUTOGRAPH SUBSETS ═══════════════════════════════════════════════════════
# Due to file size, the massive FA (138), FMA-Moments (35), FI (24), GA (40), FPA (15), RCA (13), FMA-Mega (80), DRCA (20 dual), RPA (37) subsets are inserted below.
# Each is listed with full card data per the mandate.

# Finest Autographs (FA-, 138 cards) — abbreviated for file size; full data in prompt
fa_data = [
("FA-AD","Adrian Gonzalez","San Diego Padres",F),("FA-AF","Alex Freeland","Los Angeles Dodgers",R),("FA-AJ","Adam Jones","Baltimore Orioles",F),("FA-AK","Alejandro Kirk","Toronto Blue Jays",F),("FA-AP","Andrew Painter","Philadelphia Phillies",R),("FA-APA","Andy Pages","Los Angeles Dodgers",F),("FA-AR","Agustin Ramirez","Miami Marlins",F),("FA-AS","Anthony Seigler","Milwaukee Brewers",R),("FA-AX","Alex Gordon","Kansas City Royals",F),("FA-BBY","Bert Blyleven","Minnesota Twins",F),
("FA-BC","Bubba Chandler","Pittsburgh Pirates",R),("FA-BE","Bryce Eldridge","San Francisco Giants",R),("FA-BH","Brady House","Washington Nationals",R),("FA-BL","Brooks Lee","Minnesota Twins",F),("FA-BR","Ben Rice","New York Yankees",F),("FA-BRE","Bryan Reynolds","Pittsburgh Pirates",F),("FA-BRO","Brent Rooker","Athletics",F),("FA-BT","Brice Turang","Milwaukee Brewers",F),("FA-BW","Billy Wagner","Houston Astros",F),("FA-BWO","Bryan Woo","Seattle Mariners",F),
("FA-CA","CJ Abrams","Washington Nationals",F),("FA-CAD","Cam Devanney","Pittsburgh Pirates",R),("FA-CAG","Jac Caglianone","Kansas City Royals",R),("FA-CB","Chase Burns","Cincinnati Reds",R),("FA-CBL","Charlie Blackmon","Colorado Rockies",F),("FA-CC","Carlos Cortes","Athletics",R),("FA-CCA","Corbin Carroll","Arizona Diamondbacks",F),("FA-CD","Chase DeLauter","Cleveland Guardians",R),("FA-CDO","Chase Dollander","Colorado Rockies",F),("FA-CE","Connelly Early","Boston Red Sox",R),
("FA-CFR","Cody Freeman","Texas Rangers",R),("FA-CH","Cade Horton","Chicago Cubs",F),("FA-CHS","Chad Stevens","Angels",R),("FA-CJ","Carter Jensen","Kansas City Royals",R),("FA-CK","C.J. Kayfus","Cleveland Guardians",R),("FA-CL","Cliff Lee","Philadelphia Phillies",F),("FA-CM","Chase Meidroth","Chicago White Sox",F),("FA-CMA","Coby Mayo","Baltimore Orioles",F),("FA-CME","Christian Moore","Angels",R),("FA-CMO","Colson Montgomery","Chicago White Sox",R),
("FA-CN","Carlos Narvaez","Boston Red Sox",F),("FA-CP","Cesar Prieto","St. Louis Cardinals",R),("FA-CS","C.J. Stubbs","Washington Nationals",R),("FA-CSC","Cam Schlittler","New York Yankees",R),("FA-CSI","Chandler Simpson","Tampa Bay Rays",F),("FA-CT","Colby Thomas","Athletics",R),("FA-CW","Carson Williams","Tampa Bay Rays",R),("FA-CY","Cole Young","Seattle Mariners",R),("FA-DB","Drake Baldwin","Atlanta Braves",F),("FA-DBS","Dylan Beavers","Baltimore Orioles",R),
("FA-DD","Dillon Dingler","Detroit Tigers",F),("FA-DF","Didier Fuentes","Atlanta Braves",R),("FA-DGU","Denzer Guzman","Angels",R),("FA-DL","Derrek Lee","Chicago Cubs",F),("FA-DW","Dave Winfield","San Diego Padres",F),("FA-EC","Evan Carter","Texas Rangers",F),("FA-EQ","Edgar Quero","Chicago White Sox",F),("FA-FP","Freddy Peralta","Milwaukee Brewers",F),("FA-HB","Hunter Barco","Pittsburgh Pirates",R),("FA-IS","Ian Seymour","Tampa Bay Rays",R),
("FA-JA","Jonathan Aranda","Tampa Bay Rays",F),("FA-JC","Justin Crawford","Philadelphia Phillies",R),("FA-JCA","Joe Carter","Toronto Blue Jays",F),("FA-JCO","Jose Corniell","Texas Rangers",R),("FA-JCR","Jimmy Crooks","St. Louis Cardinals",R),("FA-JD","Justin Dean","Los Angeles Dodgers",R),("FA-JDA","Johnny Damon","New York Yankees",F),("FA-JDN","Jarren Duran","Boston Red Sox",F),("FA-JDU","Jhoan Duran","Philadelphia Phillies",F),("FA-JDZ","Jasson Dominguez","New York Yankees",F),
("FA-JE","Jim Edmonds","Anaheim Angels",F),("FA-JG","Jhostynxon Garcia","Boston Red Sox",R),("FA-JGO","Juan Gonzalez","Texas Rangers",F),("FA-JJ","Jackson Jobe","Detroit Tigers",F),("FA-JJU","Jace Jung","Detroit Tigers",F),("FA-JJW","JJ Wetherholt","St. Louis Cardinals",R),("FA-JM","Jakob Marsee","Miami Marlins",R),("FA-JME","Jacob Melton","Houston Astros",R),("FA-JMO","Justin Morneau","Minnesota Twins",F),("FA-JP","Jack Perkins","Athletics",R),
("FA-JPA","Jim Palmer","Baltimore Orioles",F),("FA-JR","Jose Reyes","New York Mets",F),("FA-JS","John Smoltz","Atlanta Braves",F),("FA-JT","Jonah Tong","New York Mets",R),("FA-JWI","Jack Winkler","Miami Marlins",R),("FA-KC","Kenedy Corona","Houston Astros",R),("FA-KCA","Kristian Campbell","Boston Red Sox",F),("FA-KG","Konnor Griffin","Pittsburgh Pirates",R),("FA-KK","Kyle Karros","Colorado Rockies",R),("FA-KL","Kenny Lofton","Cleveland",F),
("FA-KM","Kyle Manzardo","Cleveland Guardians",F),("FA-KMC","Kevin McGonigle","Detroit Tigers",R),("FA-KO","Kazuma Okamoto","Toronto Blue Jays",R),("FA-LA","Luisangel Acuna","New York Mets",F),("FA-LH","Logan Henderson","Milwaukee Brewers",F),("FA-LW","Logan Webb","San Francisco Giants",F),("FA-MA","Maximo Acosta","Miami Marlins",R),("FA-MAB","Mick Abel","Minnesota Twins",F),("FA-MB","Mason Barnett","Athletics",R),("FA-MBA","Moises Ballesteros","Chicago Cubs",F),
("FA-MF","Mitch Farris","Angels",R),("FA-MFR","Max Fried","New York Yankees",F),("FA-MH","Michael Harris II","Atlanta Braves",F),("FA-MIZ","Jacob Misiorowski","Milwaukee Brewers",R),("FA-MM","Mason Miller","San Diego Padres",F),("FA-MMU","Munetaka Murakami","Chicago White Sox",R),("FA-MOL","Matt Olson","Atlanta Braves",F),("FA-MW","Masyn Winn","St. Louis Cardinals",F),("FA-MY","Michael Young","Texas Rangers",F),("FA-NC","Nathan Church","St. Louis Cardinals",R),
("FA-NM","Nolan McLean","New York Mets",R),("FA-NME","Noelvi Marte","Cincinnati Reds",F),("FA-NS","Noah Schultz","Chicago White Sox",R),("FA-OA","Ozzie Albies","Atlanta Braves",F),("FA-OC","Owen Caissie","Chicago Cubs",R),("FA-OH","Orlando Hernandez","New York Yankees",F),("FA-OK","Otto Kemp","Philadelphia Phillies",R),("FA-PH","Petey Halpin","Cleveland Guardians",R),("FA-PM","Parker Messick","Cleveland Guardians",R),("FA-PMO","Paul Molitor","Toronto Blue Jays",F),
("FA-PR","Geraldo Perdomo","Arizona Diamondbacks",F),("FA-PT","Payton Tolle","Boston Red Sox",R),("FA-RA","Roman Anthony","Boston Red Sox",R),("FA-RFL","Rafael Flores","Pittsburgh Pirates",R),("FA-RH","Robert Hassell III","Washington Nationals",F),("FA-RHO","Ryan Howard","Philadelphia Phillies",F),("FA-RIZ","Anthony Rizzo","Chicago Cubs",F),("FA-RL","Rhett Lowder","Cincinnati Reds",F),("FA-RR","Ryan Ritter","Colorado Rockies",R),("FA-RZ","Ryan Zimmerman","Washington Nationals",F),
("FA-SB","Samuel Basallo","Baltimore Orioles",R),("FA-SK","Steven Kwan","Cleveland Guardians",F),("FA-SR","Scott Rolen","Cincinnati Reds",F),("FA-SS","Spencer Schwellenbach","Atlanta Braves",F),("FA-SSE","Sal Stewart","Cincinnati Reds",R),("FA-TA","Grant Taylor","Chicago White Sox",R),("FA-TE","Tristin English","Arizona Diamondbacks",R),("FA-TG","Tom Glavine","Atlanta Braves",F),("FA-TH","Trevor Hoffman","San Diego Padres",F),("FA-THA","Thomas Harrington","Pittsburgh Pirates",F),
("FA-THU","Torii Hunter","Minnesota Twins",F),("FA-TI","Tatsuya Imai","Houston Astros",R),("FA-TJO","Troy Johnston","Miami Marlins",R),("FA-TM","Troy Melton","Detroit Tigers",R),("FA-TP","Tristan Peters","Tampa Bay Rays",R),("FA-TS","Tyler Soderstrom","Athletics",F),("FA-TSA","Thomas Saggese","St. Louis Cardinals",F),("FA-TY","Trey Yesavage","Toronto Blue Jays",R),("FA-VA","George Valera","Cleveland Guardians",R),("FA-VM","Victor Martinez","Detroit Tigers",F),
("FA-WA","Wilyer Abreu","Boston Red Sox",F),("FA-WB","Will Banfield","Cincinnati Reds",R),("FA-WBE","Warming Bernabel","Colorado Rockies",R),("FA-WC","William Contreras","Milwaukee Brewers",F),("FA-WG","Wikelman Gonzalez","Chicago White Sox",R),("FA-WS","Will Smith","Los Angeles Dodgers",F),("FA-YF","Yanquiel Fernandez","Colorado Rockies",R),("FA-ZC","Zach Cole","Houston Astros",R),("FA-ZM","Zach Maxwell","Cincinnati Reds",R),
]
ins("Finest Autographs", fa_data, is_auto=True)

# Finest Moments Autographs (FMA- prefix, 36 cards)
ins("Finest Moments Autographs", [
("FMA-AM","Andrew McCutchen","Pittsburgh Pirates",F),("FMA-AT","Alan Trammell","Detroit Tigers",F),("FMA-BB","Byron Buxton","Minnesota Twins",F),("FMA-CB","Chase Burns","Cincinnati Reds",R),("FMA-CC","CC Sabathia","New York Yankees",F),("FMA-CR","Cal Raleigh","Seattle Mariners",F),("FMA-DJ","Derek Jeter","New York Yankees",F),("FMA-DW","David Wright","New York Mets",F),("FMA-FF","Freddie Freeman","Los Angeles Dodgers",F),("FMA-FL","Francisco Lindor","New York Mets",F),
("FMA-FT","Frank Thomas","Chicago White Sox",F),("FMA-HM","Hideki Matsui","New York Yankees",F),("FMA-IR","Ivan Rodriguez","Texas Rangers",F),("FMA-JC","Junior Caminero","Tampa Bay Rays",F),("FMA-JCA","Jac Caglianone","Kansas City Royals",R),("FMA-JM","Jacob Misiorowski","Milwaukee Brewers",R),("FMA-KS","Kyle Schwarber","Philadelphia Phillies",F),("FMA-MC","Miguel Cabrera","Florida Marlins",F),("FMA-MS","Mike Schmidt","Philadelphia Phillies",F),("FMA-MT","Mike Trout","Angels",F),
("FMA-NK","Nick Kurtz","Athletics",F),("FMA-NM","Nolan McLean","New York Mets",R),("FMA-OC","Owen Caissie","Miami Marlins",R),("FMA-OS","Ozzie Smith","St. Louis Cardinals",F),("FMA-PA","Pete Alonso","New York Mets",F),("FMA-PS","Paul Skenes","Pittsburgh Pirates",F),("FMA-RA","Roman Anthony","Boston Red Sox",R),("FMA-RAJ","Ronald Acuna Jr.","Atlanta Braves",F),("FMA-RJ","Reggie Jackson","Oakland Athletics",F),("FMA-RS","Roki Sasaki","Los Angeles Dodgers",F),
("FMA-SB","Samuel Basallo","Baltimore Orioles",R),("FMA-SCH","Cam Schlittler","New York Yankees",R),("FMA-SO","Shohei Ohtani","Los Angeles Dodgers",F),("FMA-SS","Sammy Sosa","Chicago Cubs",F),("FMA-TS","Tarik Skubal","Detroit Tigers",F),("FMA-TY","Trey Yesavage","Toronto Blue Jays",R),("FMA-YY","Yoshinobu Yamamoto","Los Angeles Dodgers",F),
], is_auto=True)

ins("Finest Ink", [("FI-AB","Adrian Beltre","Texas Rangers",F),("FI-AD","Andre Dawson","Montreal Expos",F),("FI-AJ","Andruw Jones","Atlanta Braves",F),("FI-BB","Barry Bonds","San Francisco Giants",F),("FI-BL","Barry Larkin","Cincinnati Reds",F),("FI-BW","Bernie Williams","New York Yankees",F),("FI-CB","Carlos Beltran","New York Mets",F),("FI-CF","Carlton Fisk","Boston Red Sox",F),("FI-CFI","Cecil Fielder","Detroit Tigers",F),("FI-DE","Dennis Eckersley","Oakland Athletics",F),("FI-DJ","Derek Jeter","New York Yankees",F),("FI-FJ","Fergie Jenkins","Chicago Cubs",F),("FI-GG","Goose Gossage","New York Yankees",F),("FI-GS","Gary Sheffield","Florida Marlins",F),("FI-JB","Johnny Bench","Cincinnati Reds",F),("FI-KG","Ken Griffey Jr.","Seattle Mariners",F),("FI-LW","Larry Walker","Colorado Rockies",F),("FI-MM","Mark McGwire","St. Louis Cardinals",F),("FI-MR","Mariano Rivera","New York Yankees",F),("FI-MS","Mike Schmidt","Philadelphia Phillies",F),("FI-RC","Roger Clemens","Houston Astros",F),("FI-RF","Rollie Fingers","Milwaukee Brewers",F),("FI-RJ","Randy Johnson","Arizona Diamondbacks",F),("FI-SK","Sandy Koufax","Los Angeles Dodgers",F)], is_auto=True)

ins("Gustographs", [("GA-AB","Alex Bregman","Boston Red Sox",F),("GA-AJ","Aaron Judge","New York Yankees",F),("GA-AP","Albert Pujols","St. Louis Cardinals",F),("GA-BC","Bubba Chandler","Pittsburgh Pirates",R),("GA-BE","Bryce Eldridge","San Francisco Giants",R),("GA-BH","Bryce Harper","Philadelphia Phillies",F),("GA-CB","Cody Bellinger","New York Yankees",F),("GA-CH","Cade Horton","Chicago Cubs",F),("GA-CJ","Chipper Jones","Atlanta Braves",F),("GA-CM","Colson Montgomery","Chicago White Sox",R),("GA-CMO","Christian Moore","Angels",R),("GA-CR","Cal Ripken Jr.","Baltimore Orioles",F),("GA-CY","Christian Yelich","Milwaukee Brewers",F),("GA-DO","David Ortiz","Boston Red Sox",F),("GA-EM","Eddie Murray","Baltimore Orioles",F),("GA-EMZ","Edgar Martinez","Seattle Mariners",F),("GA-FH","Felix Hernandez","Seattle Mariners",F),("GA-FT","Fernando Tatis Jr.","San Diego Padres",F),("GA-GB","George Brett","Kansas City Royals",F),("GA-GM","Greg Maddux","Atlanta Braves",F),
("GA-GS","Gary Sheffield","Atlanta Braves",F),("GA-JA","Jose Altuve","Houston Astros",F),("GA-JC","Jac Caglianone","Kansas City Royals",R),("GA-JCH","Jackson Chourio","Milwaukee Brewers",F),("GA-JMZ","Jacob Misiorowski","Milwaukee Brewers",R),("GA-JS","Juan Soto","New York Mets",F),("GA-JT","Jonah Tong","New York Mets",R),("GA-JVO","Joey Votto","Cincinnati Reds",F),("GA-JW","Jacob Wilson","Athletics",F),("GA-LW","Larry Walker","Colorado Rockies",F),("GA-MMU","Munetaka Murakami","Chicago White Sox",R),("GA-MP","Mike Piazza","New York Mets",F),("GA-OC","Owen Caissie","Chicago Cubs",R),("GA-OH","Orel Hershiser","Los Angeles Dodgers",F),("GA-PF","Prince Fielder","Milwaukee Brewers",F),("GA-RA","Roman Anthony","Boston Red Sox",R),("GA-RG","Riley Greene","Detroit Tigers",F),("GA-SB","Samuel Basallo","Baltimore Orioles",R),("GA-TH","Torii Hunter","Minnesota Twins",F),("GA-TT","Trea Turner","Philadelphia Phillies",F),("GA-ZW","Zack Wheeler","Philadelphia Phillies",F)], is_auto=True)

# FPA with celebrity role for broadcasters
fpa_data = [
("FPA-BO","Buster Olney","",F,"celebrity"),("FPA-BW","Brian Wilson","San Francisco Giants",F),("FPA-CR","Chris Rose","",F,"celebrity"),("FPA-DS","Dave Sims","",F,"celebrity"),("FPA-HP","Hunter Pence","San Francisco Giants",F),("FPA-JB","Joe Buck","",F,"celebrity"),("FPA-JD","Joe Davis","",F,"celebrity"),("FPA-JK","John Kruk","",F,"celebrity"),("FPA-JR","Jimmy Rollins","Philadelphia Phillies",F),("FPA-KAY","Michael Kay","",F,"celebrity"),
("FPA-KR","Ken Rosenthal","",F,"celebrity"),("FPA-LP","Lou Piniella","Seattle Mariners",F),("FPA-MD",'Christopher "Mad Dog" Russo',"",F,"celebrity"),("FPA-OG","Ozzie Guillen","Chicago White Sox",F),("FPA-RJ","Reggie Jackson","New York Yankees",F),
]
fpa_id = ais("Finest Personality Autographs", is_auto=True)
ac(fpa_id, fpa_data)
print(f"  Finest Personality Autographs: {len(fpa_data)} cards")

ins("Topps Rookie Cup Anniversary Autographs", [("RCA-AB","Alec Bohm","Philadelphia Phillies",F),("RCA-CJ","Chipper Jones","Atlanta Braves",F),("RCA-DJ","David Justice","Atlanta Braves",F),("RCA-FL","Fred Lynn","Boston Red Sox",F),("RCA-HN","Hideo Nomo","Los Angeles Dodgers",F),("RCA-JR","Jim Rice","Boston Red Sox",F),("RCA-JT","J.T. Realmuto","Miami Marlins",F),("RCA-KS","Kyle Schwarber","Chicago Cubs",F),("RCA-LW","Larry Walker","Montreal Expos",F),("RCA-OG","Ozzie Guillen","Chicago White Sox",F),("RCA-RV","Robin Ventura","Chicago White Sox",F),("RCA-SG","Shawn Green","Toronto Blue Jays",F),("RCA-TP","Tony Perez","Cincinnati Reds",F)], is_auto=True)

# Finest Mega Autographs (FMA- prefix, same as Moments but distinct subset name, 80 cards)
fma_mega = [
("FMA-AA","Adael Amador","Colorado Rockies",F),("FMA-AB","Alex Bregman","Chicago Cubs",F),("FMA-ABA","Addison Barger","Toronto Blue Jays",F),("FMA-ADC","Adrian Del Castillo","Arizona Diamondbacks",F),("FMA-AG","Adolis Garcia","Philadelphia Phillies",F),("FMA-AS","Alfonso Soriano","New York Yankees",F),("FMA-AU","Abner Uribe","Milwaukee Brewers",F),("FMA-AV","Anthony Volpe","New York Yankees",F),("FMA-BB","Bradley Blalock","Miami Marlins",F),("FMA-BBA","Brooks Baldwin","Chicago White Sox",F),
("FMA-BD","Brendan Donovan","Seattle Mariners",F),("FMA-BM","Brian McCann","Atlanta Braves",F),("FMA-BPH","Brandon Phillips","Cincinnati Reds",F),("FMA-BS","Brandon Sproat","Milwaukee Brewers",R),("FMA-BW","Ben Williamson","Tampa Bay Rays",F),("FMA-CDU","Caleb Durbin","Boston Red Sox",F),("FMA-CK","Colt Keith","Detroit Tigers",F),("FMA-CMW","Chien-Ming Wang","New York Yankees",F),("FMA-CN","Connor Norby","Miami Marlins",F),("FMA-CP","Carlos Pena","Tampa Bay Rays",F),
("FMA-DEC","David Eckstein","Anaheim Angels",F),("FMA-DS","Daniel Schneemann","Cleveland Guardians",F),("FMA-DW","Devin Williams","New York Mets",F),("FMA-DWIL","Dontrelle Willis","Florida Marlins",F),("FMA-ECH","Eric Chavez","Oakland Athletics",F),("FMA-FF","Freddie Freeman","Los Angeles Dodgers",F),("FMA-FP","Freddy Peralta","New York Mets",F),("FMA-GF","George Foster","Cincinnati Reds",F),("FMA-GH","Grant Holmes","Atlanta Braves",F),("FMA-GK","George Kirby","Seattle Mariners",F),
("FMA-GS","George Springer","Toronto Blue Jays",F),("FMA-HF","Harry Ford","Washington Nationals",R),("FMA-HW","Hurston Waldrep","Atlanta Braves",F),("FMA-IC","Isaac Collins","Kansas City Royals",F),("FMA-IP","Isaac Paredes","Houston Astros",F),("FMA-JC","Jose Caballero","New York Yankees",F),("FMA-JCAN","Jose Canseco","Oakland Athletics",F),("FMA-JE","J.C. Escarra","New York Yankees",F),("FMA-JG","Jhostynxon Garcia","Pittsburgh Pirates",R),("FMA-JGI","Jason Giambi","New York Yankees",F),
("FMA-JL","Jack Leiter","Texas Rangers",F),("FMA-JLAW","Jordan Lawlar","Arizona Diamondbacks",F),("FMA-JP","Jeremy Pena","Houston Astros",F),("FMA-JS","Javier Sanoja","Miami Marlins",F),("FMA-JT","Jonah Tong","New York Mets",R),("FMA-JWI","Jack Wilson","Pittsburgh Pirates",F),("FMA-JY","Jacob Young","Washington Nationals",F),("FMA-KA","Kevin Alcantara","Chicago Cubs",F),("FMA-KC","Kerry Carpenter","Detroit Tigers",F),("FMA-KS","Kodai Senga","New York Mets",F),
("FMA-LA","Luisangel Acuna","Chicago White Sox",F),("FMA-LP","Lou Piniella","Kansas City Royals",F),("FMA-LR","Luis Robert Jr.","New York Mets",F),("FMA-LRO","Landen Roupp","San Francisco Giants",F),("FMA-LW","Luke Weaver","New York Mets",F),("FMA-MB","Matthew Boyd","Chicago Cubs",F),("FMA-MBR","Mark Buehrle","Chicago White Sox",F),("FMA-MBU","Mike Burrows","Houston Astros",F),("FMA-MW","Matt Williams","San Francisco Giants",F),("FMA-MY","Masataka Yoshida","Boston Red Sox",F),
("FMA-NA","Norichika Aoki","Kansas City Royals",F),("FMA-NE","Nathan Eovaldi","Texas Rangers",F),("FMA-NS","Nolan Schanuel","Angels",F),("FMA-NY","Nick Yorke","Pittsburgh Pirates",F),("FMA-OC","Owen Caissie","Miami Marlins",R),("FMA-RA","Ronald Acuna Jr.","Atlanta Braves",F),("FMA-RL","Royce Lewis","Minnesota Twins",F),("FMA-RM","Ryan McMahon","New York Yankees",F),("FMA-RMO","Ryan Mountcastle","Baltimore Orioles",F),("FMA-RS","Roki Sasaki","Los Angeles Dodgers",F),
("FMA-SG","Shawn Green","Los Angeles Dodgers",F),("FMA-SI","Shota Imanaga","Chicago Cubs",F),("FMA-SL","Seth Lugo","Kansas City Royals",F),("FMA-SMS","Sung-Mun Song","San Diego Padres",R),("FMA-SS","Sal Stewart","Cincinnati Reds",R),("FMA-SW","Shay Whitcomb","Houston Astros",F),("FMA-TF","TJ Friedl","Cincinnati Reds",F),("FMA-TH","Tim Hudson","Oakland Athletics",F),("FMA-TJ","Troy Johnston","Colorado Rockies",R),("FMA-TL","Tyler Locklear","Arizona Diamondbacks",F),
("FMA-TS","Ted Simmons","St. Louis Cardinals",F),("FMA-VG","Vladimir Guerrero Jr.","Toronto Blue Jays",F),("FMA-WB","Warming Bernabel","Washington Nationals",R),("FMA-WK","Will Klein","Los Angeles Dodgers",F),("FMA-WW","Will Warren","New York Yankees",F),("FMA-ZV","Zac Veen","Colorado Rockies",F),
]
ins("Finest Mega Autographs", fma_mega, is_auto=True)

# DRCA (20 dual-subject)
drca_id = ais("Topps Rookie Cup Dual Autographs", is_auto=True)
ad(drca_id, [
("DRCA-AL","Fred Lynn","Roman Anthony"),("DRCA-AR","Jim Rice","Roman Anthony"),("DRCA-AS","Juan Soto","Ronald Acuna Jr."),("DRCA-BJ","Chipper Jones","Drake Baldwin"),("DRCA-BM","Brian McCann","Drake Baldwin"),("DRCA-CC","Isaac Collins","Jackson Chourio"),("DRCA-CS","Jackson Chourio","Gary Sheffield"),("DRCA-HC","Cade Horton","Noah Cameron"),("DRCA-HI","Cade Horton","Shota Imanaga"),("DRCA-HS","Matt Shaw","Cade Horton"),
("DRCA-HW","Kerry Wood","Cade Horton"),("DRCA-JT","Mike Trout","Aaron Judge"),("DRCA-KB","Nick Kurtz","Drake Baldwin"),("DRCA-KC","Rod Carew","Luke Keaschall"),("DRCA-KM","Luke Keaschall","Joe Mauer"),("DRCA-KW","Nick Kurtz","Jacob Wilson"),("DRCA-MR","Agustin Ramirez","Jakob Marsee"),("DRCA-NM","Nick Kurtz","Mark McGwire"),("DRCA-RR","Agustin Ramirez","Hanley Ramirez"),("DRCA-SH","Matt Shaw","Ian Happ"),
])
print(f"  Topps Rookie Cup Dual Autographs: 20 cards (dual)")

# RPA (37 cards, all rookies)
ins("Finest Rookie Patch Autograph", [("RPA-AF","Alex Freeland","Los Angeles Dodgers",R),("RPA-BC","Bubba Chandler","Pittsburgh Pirates",R),("RPA-BH","Brady House","Washington Nationals",R),("RPA-BM","Brice Matthews","Houston Astros",R),("RPA-BS","Brandon Sproat","Milwaukee Brewers",R),("RPA-CD","Chase DeLauter","Cleveland Guardians",R),("RPA-CE","Connelly Early","Boston Red Sox",R),("RPA-CHM","Christian Moore","Angels",R),("RPA-CJ","Carter Jensen","Kansas City Royals",R),("RPA-CK","C.J. Kayfus","Cleveland Guardians",R),("RPA-CM","Colson Montgomery","Chicago White Sox",R),("RPA-CS","Cam Schlittler","New York Yankees",R),("RPA-CT","Colby Thomas","Athletics",R),("RPA-CW","Carson Williams","Tampa Bay Rays",R),("RPA-DB","Dylan Beavers","Baltimore Orioles",R),("RPA-DF","Didier Fuentes","Atlanta Braves",R),("RPA-DG","Drew Gilbert","San Francisco Giants",R),("RPA-GT","Grant Taylor","Chicago White Sox",R),("RPA-HB","Hunter Barco","Pittsburgh Pirates",R),("RPA-HH","Heriberto Hernandez","Miami Marlins",R),("RPA-JC","Jac Caglianone","Kansas City Royals",R),("RPA-JG","Jhostynxon Garcia","Pittsburgh Pirates",R),("RPA-JJ","Jeremiah Jackson","Baltimore Orioles",R),("RPA-JM","Jacob Misiorowski","Milwaukee Brewers",R),("RPA-JT","Jonah Tong","New York Mets",R),("RPA-JW","JJ Wetherholt","St. Louis Cardinals",R),("RPA-KK","Kyle Karros","Colorado Rockies",R),("RPA-KT","Kyle Teel","Chicago White Sox",R),("RPA-LM","Luis Morales","Athletics",R),("RPA-MA","Maximo Acosta","Miami Marlins",R),("RPA-MM","Munetaka Murakami","Chicago White Sox",R),("RPA-NM","Nolan McLean","New York Mets",R),("RPA-PM","Parker Messick","Cleveland Guardians",R),("RPA-PT","Payton Tolle","Boston Red Sox",R),("RPA-RR","Ryan Ritter","Colorado Rockies",R),("RPA-SS","Sal Stewart","Cincinnati Reds",R),("RPA-TY","Trey Yesavage","Toronto Blue Jays",R)], is_auto=True)

# ═══ BACKFILL IMAGE IDs ═════════════════════════════════════════════════════
db.commit()
updated = db.execute("""
    UPDATE players SET mlb_player_id = (SELECT p2.mlb_player_id FROM players p2 WHERE p2.name = players.name AND p2.mlb_player_id IS NOT NULL LIMIT 1)
    WHERE set_id = ? AND mlb_player_id IS NULL AND EXISTS (SELECT 1 FROM players p2 WHERE p2.name = players.name AND p2.mlb_player_id IS NOT NULL)
""", (SET_ID,)).rowcount
print(f"\nBackfilled {updated} MLB player IDs")

# ═══ SUMMARY ════════════════════════════════════════════════════════════════
db.commit()
tp = db.execute("SELECT COUNT(*) FROM players WHERE set_id = ?", (SET_ID,)).fetchone()[0]
ta = db.execute("SELECT COUNT(*) FROM player_appearances pa JOIN insert_sets ins ON pa.insert_set_id = ins.id WHERE ins.set_id = ?", (SET_ID,)).fetchone()[0]
ts = db.execute("SELECT COUNT(*) FROM insert_sets WHERE set_id = ?", (SET_ID,)).fetchone()[0]

print(f"\n{'='*50}")
print(f"Set ID: {SET_ID}")
print(f"Total subsets: {ts}")
print(f"Total unique athletes: {tp}")
print(f"Total card appearances: {ta}")
print(f"Expected: ~1,122 cards")
db.close()
print("Done!")
