"""
Seed script: 2025 Topps Chrome Formula 1
Creates the set with box config and pack odds only (no checklist cards).
Usage: python3 scripts/seed_chrome_f1_2025.py
"""

import sqlite3
import json
import os

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "the-c-list.db")

conn = sqlite3.connect(DB_PATH)
conn.execute("PRAGMA journal_mode=WAL")
conn.execute("PRAGMA foreign_keys=ON")
cur = conn.cursor()

SET_NAME = "2025 Topps Chrome Formula 1"

cur.execute("SELECT id FROM sets WHERE name = ?", (SET_NAME,))
existing = cur.fetchone()
if existing:
    print(f"Set '{SET_NAME}' already exists with id {existing[0]}. Aborting.")
    conn.close()
    exit(1)

box_config = {
    "hobby": {
        "cards_per_pack": 4,
        "packs_per_box": 8,
        "boxes_per_case": 10,
        "autos_per_box": None,
        "parallels_or_short_prints_per_box": 4,
    },
}

pack_odds = {
    "hobby": {
        "Base Refractor Parallel": "1:5",
        "Base Checker Flag Parallel": "1:20",
        "Base B&W Lazer Refractor": "1:7",
        "Base Teal Refractor Parallel": "1:49",
        "Base Pink Refractor Parallel": "1:58",
        "Base Pink Checker Flag Parallel": "1:31",
        "Base Aqua Refractor Parallel": "1:73",
        "Base Aqua Checker Flag Parallel": "1:39",
        "Base Blue Refractor Parallel": "1:97",
        "Base Blue Checker Flag Parallel": "1:52",
        "Base Green Refractor Parallel": "1:146",
        "Base Green Checker Flag Parallel": "1:78",
        "Base F1 75th Anniversary Refractor Parallel": "1:103",
        "Base Gold Refractor Parallel": "1:289",
        "Base Gold Checker Flag Parallel": "1:155",
        "Base Orange Refractor Parallel": "1:577",
        "Base Orange Checker Flag Parallel": "1:309",
        "Base Black Refractor Parallel": "1:1,441",
        "Base Black Checker Flag Parallel": "1:1,220",
        "Base Red Refractor Parallel": "1:2,881",
        "Base Red Checker Flag Parallel": "1:1,542",
        "Base Superfractor Parallel": "1:14,403",
        "Base Printing Plates Cyan": "1:14,403",
        "Base Printing Plates Magenta": "1:14,403",
        "Base Printing Plates Yellow": "1:14,403",
        "Base Printing Plates Black": "1:14,403",
        "Base Card Image Variations": "1:2,881",
        "1975 Speed Wheels": "1:10",
        "1975 Speed Wheels Aqua Refractor Parallel": "1:1,448",
        "1975 Speed Wheels Blue Refractor Parallel": "1:1,922",
        "1975 Speed Wheels Green Refractor Parallel": "1:2,911",
        "1975 Speed Wheels F1 75th Anniversary Refractor Parallel": "1:2,056",
        "1975 Speed Wheels Gold Refractor Parallel": "1:5,768",
        "1975 Speed Wheels Orange Refractor Parallel": "1:11,583",
        "1975 Speed Wheels Black Refractor Parallel": "1:28,956",
        "1975 Speed Wheels Red Refractor Parallel": "1:59,144",
        "1975 Speed Wheels Superfractor Parallel": "1:397,110",
        "Ace of Trades": "1:10",
        "Ace of Trades Aqua Refractor Parallel": "1:1,448",
        "Ace of Trades Blue Refractor Parallel": "1:1,922",
        "Ace of Trades Green Refractor Parallel": "1:2,911",
        "Ace of Trades F1 75th Anniversary Refractor Parallel": "1:2,056",
        "Ace of Trades Gold Refractor Parallel": "1:5,768",
        "Ace of Trades Orange Refractor Parallel": "1:11,583",
        "Ace of Trades Black Refractor Parallel": "1:28,956",
        "Ace of Trades Red Refractor Parallel": "1:59,144",
        "Ace of Trades Superfractor Parallel": "1:397,110",
        "F1 Chrome Diamond Drives": "1:10",
        "Floor It": "1:10",
        "Floor It Aqua Refractor Parallel": "1:1,448",
        "Floor It Blue Refractor Parallel": "1:1,922",
        "Floor It Green Refractor Parallel": "1:2,911",
        "Floor It F1 75th Anniversary Refractor Parallel": "1:2,056",
        "Floor It Gold Refractor Parallel": "1:5,768",
        "Floor It Orange Refractor Parallel": "1:11,583",
        "Floor It Black Refractor Parallel": "1:28,956",
        "Floor It Red Refractor Parallel": "1:59,144",
        "Floor It Superfractor Parallel": "1:397,110",
        "Helmet Collection": "1:10",
        "Helmet Collection Aqua Refractor Parallel": "1:1,448",
        "Helmet Collection Blue Refractor Parallel": "1:1,922",
        "Helmet Collection Green Refractor Parallel": "1:2,911",
        "Helmet Collection F1 75th Anniversary Refractor Parallel": "1:2,056",
        "Helmet Collection Gold Refractor Parallel": "1:5,768",
        "Helmet Collection Orange Refractor Parallel": "1:11,583",
        "Helmet Collection Black Refractor Parallel": "1:28,956",
        "Helmet Collection Red Refractor Parallel": "1:59,144",
        "Helmet Collection Superfractor Parallel": "1:397,110",
        "Speed Demons": "1:10",
        "Speed Demons Aqua Refractor Parallel": "1:1,317",
        "Speed Demons Blue Refractor Parallel": "1:1,748",
        "Speed Demons Green Refractor Parallel": "1:2,648",
        "Speed Demons F1 75th Anniversary Refractor Parallel": "1:1,713",
        "Speed Demons Gold Refractor Parallel": "1:5,245",
        "Speed Demons Orange Refractor Parallel": "1:10,530",
        "Speed Demons Black Refractor Parallel": "1:26,729",
        "Speed Demons Red Refractor Parallel": "1:54,506",
        "Speed Demons Superfractor Parallel": "1:347,471",
        "Futuro": "1:240",
        "Futuro Superfractor Parallel": "1:1,389,884",
        "Helix": "1:700",
        "Helix Superfractor Parallel": "1:74,376",
        "Neon Nations": "1:240",
        "Neon Nations Superfractor Parallel": "1:463,295",
        "The Chain": "1:480",
        "The Chain Superfractor Parallel": "1:397,110",
        "The Grid": "1:2,400",
        "The Grid Superfractor Parallel": "1:148,752",
        "Ultrasonic": "1:1,200",
        "Ultrasonic Superfractor Parallel": "1:106,252",
        "Vegas At Night": "1:1,920",
        "Vegas At Night Superfractor Parallel": "1:297,504",
        "The Grail": "1:5,951",
        "1975 Speed Wheel Signatures": "1:4,985",
        "1975 Speed Wheel Signatures Orange Refractor Parallel": "1:12,082",
        "1975 Speed Wheel Signatures Red Refractor Parallel": "1:43,148",
        "1975 Speed Wheel Signatures Superfractor Parallel": "1:215,739",
        "Chrome Autographs": "1:77",
        "Chrome Autographs Green Refractor Parallel": "1:364",
        "Chrome Autographs F1 75th Anniversary Refractor Parallel": "1:380",
        "Chrome Autographs Gold Refractor Parallel": "1:504",
        "Chrome Autographs Orange Refractor Parallel": "1:930",
        "Chrome Autographs Black Refractor Parallel": "1:2,289",
        "Chrome Autographs Red Refractor Parallel": "1:4,647",
        "Chrome Autographs Superfractor Parallel": "1:23,234",
        "Circuit Masters Signatures": "1:836",
        "Circuit Masters Signatures F1 75th Anniversary Refractor Parallel": "1:2,517",
        "Circuit Masters Signatures Gold Refractor Parallel": "1:3,021",
        "Circuit Masters Signatures Orange Refractor Parallel": "1:6,041",
        "Circuit Masters Signatures Red Refractor Parallel": "1:30,204",
        "Circuit Masters Signatures Superfractor Parallel": "1:151,018",
        "Futuro Chrome Autographs": "1:4,315",
        "Futuro Chrome Autographs Orange Refractor Parallel": "1:6,041",
        "Futuro Chrome Autographs Red Refractor Parallel": "1:30,204",
        "Futuro Chrome Autographs Superfractor Parallel": "1:151,018",
        "F1 Diamond Anniversary Base Relic Cards": "1:138,989",
        "F2 Diamond Anniversary Base Relic Cards": "1:126,354",
        "F3 Diamond Anniversary Base Relic Cards": "1:92,659",
        "F1 Debut Patch Autographs": "1:743,760",
        "On-Card Chrome Autographs Red Refractor": "1:297,504",
        "On-Card Chrome Autographs Superfractor": "1:1,487,520",
        "F175 Anniversary Logo": "1:2,066",
        "F175 Anniversary Logo Black Refractor Parallel": "1:15,995",
        "F175 Anniversary Logo Red Refractor Parallel": "1:32,338",
        "F175 Anniversary Logo Superfractor Parallel": "1:148,752",
    },
    "sapphire": {
        "Base Yellow Sapphire Parallel": "1:6",
        "Base Gold Sapphire Parallel": "1:9",
        "Base Orange Sapphire Parallel": "1:17",
        "Base B&W Sapphire Parallel": "1:21",
        "Base Black Sapphire Parallel": "1:42",
        "Base Red Sapphire Parallel": "1:84",
        "Base Padparadscha Sapphire Parallel": "1:419",
        "1975 Speed Wheels Gold Sapphire Parallel": "1:168",
        "1975 Speed Wheels Orange Sapphire Parallel": "1:337",
        "1975 Speed Wheels B&W Sapphire Parallel": "1:562",
        "1975 Speed Wheels Purple Sapphire Parallel": "1:842",
        "1975 Speed Wheels Red Sapphire Parallel": "1:1,720",
        "1975 Speed Wheels Padparadscha Sapphire Parallel": "1:11,543",
        "Ace of Trades Gold Sapphire Parallel": "1:168",
        "Ace of Trades Orange Sapphire Parallel": "1:337",
        "Ace of Trades B&W Sapphire Parallel": "1:562",
        "Ace of Trades Purple Sapphire Parallel": "1:842",
        "Ace of Trades Red Sapphire Parallel": "1:1,720",
        "Ace of Trades Padparadscha Sapphire Parallel": "1:11,543",
        "Floor It Gold Sapphire Parallel": "1:168",
        "Floor It Orange Sapphire Parallel": "1:337",
        "Floor It B&W Sapphire Parallel": "1:562",
        "Floor It Purple Sapphire Parallel": "1:842",
        "Floor It Red Sapphire Parallel": "1:1,720",
        "Floor It Padparadscha Sapphire Parallel": "1:11,543",
        "Helmet Collection Gold Sapphire Parallel": "1:168",
        "Helmet Collection Orange Sapphire Parallel": "1:337",
        "Helmet Collection B&W Sapphire Parallel": "1:562",
        "Helmet Collection Purple Sapphire Parallel": "1:842",
        "Helmet Collection Red Sapphire Parallel": "1:1,720",
        "Helmet Collection Padparadscha Sapphire Parallel": "1:11,543",
        "Speed Demons Gold Sapphire Parallel": "1:153",
        "Speed Demons Orange Sapphire Parallel": "1:307",
        "Speed Demons B&W Sapphire Parallel": "1:512",
        "Speed Demons Purple Sapphire Parallel": "1:777",
        "Speed Demons Red Sapphire Parallel": "1:1,585",
        "Speed Demons Padparadscha Sapphire Parallel": "1:10,100",
        "Infinite Sapphire": "1:80",
        "Infinite Sapphire Superfractor Parallel": "1:8,080",
        "Sapphire Selections": "1:40",
        "Sapphire Selections Superfractor Parallel": "1:8,978",
        "Chrome Autographs Sapphire": "1:26",
        "Chrome Autographs Orange Sapphire Parallel": "1:62",
        "Chrome Autographs Black Sapphire Parallel": "1:125",
        "Chrome Autographs Red Sapphire Parallel": "1:249",
        "Chrome Autographs Padparadscha Sapphire Parallel": "1:1,243",
    },
    "value": {
        "Base Refractor Parallel": "1:3",
        "Base B&W Ray Wave Refractor": "1:2",
        "Base Teal Refractor Parallel": "1:48",
        "Base Pink Refractor Parallel": "1:58",
        "Base Pink RayWave Parallel": "1:22",
        "Base Aqua Refractor Parallel": "1:72",
        "Base Aqua RayWave Parallel": "1:28",
        "Base Blue Refractor Parallel": "1:96",
        "Base Blue RayWave Parallel": "1:37",
        "Base Green Refractor Parallel": "1:145",
        "Base Green RayWave Parallel": "1:56",
        "Base Forest Green RayWave Parallel": "1:39",
        "Base Gold Refractor Parallel": "1:287",
        "Base Gold RayWave Parallel": "1:110",
        "Base Orange Refractor Parallel": "1:573",
        "Base Orange RayWave Parallel": "1:219",
        "Base Black Refractor Parallel": "1:1,432",
        "Base Black RayWave Parallel": "1:546",
        "Base Red Refractor Parallel": "1:2,863",
        "Base Red RayWave Parallel": "1:1,092",
        "Base Superfractor Parallel": "1:14,313",
        "Base Printing Plates Cyan": "1:14,313",
        "Base Printing Plates Magenta": "1:14,313",
        "Base Printing Plates Yellow": "1:14,313",
        "Base Printing Plates Black": "1:14,313",
        "Base Card Image Variations": "1:2,863",
        "1975 Speed Wheels": "1:12",
        "1975 Speed Wheels Aqua Refractor Parallel": "1:1,439",
        "1975 Speed Wheels Blue Refractor Parallel": "1:1,910",
        "1975 Speed Wheels Green Refractor Parallel": "1:2,893",
        "1975 Speed Wheels Gold Refractor Parallel": "1:5,732",
        "1975 Speed Wheels Orange Refractor Parallel": "1:11,510",
        "1975 Speed Wheels Black Refractor Parallel": "1:28,775",
        "1975 Speed Wheels Red Refractor Parallel": "1:58,775",
        "1975 Speed Wheels Superfractor Parallel": "1:394,628",
        "Ace of Trades": "1:12",
        "Ace of Trades Aqua Refractor Parallel": "1:1,439",
        "Ace of Trades Blue Refractor Parallel": "1:1,910",
        "Ace of Trades Green Refractor Parallel": "1:2,893",
        "Ace of Trades Gold Refractor Parallel": "1:5,732",
        "Ace of Trades Orange Refractor Parallel": "1:11,510",
        "Ace of Trades Black Refractor Parallel": "1:28,775",
        "Ace of Trades Red Refractor Parallel": "1:58,775",
        "Ace of Trades Superfractor Parallel": "1:394,628",
        "Floor It": "1:12",
        "Floor It Aqua Refractor Parallel": "1:1,439",
        "Floor It Blue Refractor Parallel": "1:1,910",
        "Floor It Green Refractor Parallel": "1:2,893",
        "Floor It Gold Refractor Parallel": "1:5,732",
        "Floor It Orange Refractor Parallel": "1:11,510",
        "Floor It Black Refractor Parallel": "1:28,775",
        "Floor It Red Refractor Parallel": "1:58,775",
        "Floor It Superfractor Parallel": "1:394,628",
        "Four & More": "1:6",
        "Helmet Collection": "1:12",
        "Helmet Collection Aqua Refractor Parallel": "1:1,439",
        "Helmet Collection Blue Refractor Parallel": "1:1,910",
        "Helmet Collection Green Refractor Parallel": "1:2,893",
        "Helmet Collection Gold Refractor Parallel": "1:5,732",
        "Helmet Collection Orange Refractor Parallel": "1:11,510",
        "Helmet Collection Black Refractor Parallel": "1:28,775",
        "Helmet Collection Red Refractor Parallel": "1:58,775",
        "Helmet Collection Superfractor Parallel": "1:394,628",
        "Speed Demons": "1:12",
        "Speed Demons Aqua Refractor Parallel": "1:1,308",
        "Speed Demons Blue Refractor Parallel": "1:1,737",
        "Speed Demons Green Refractor Parallel": "1:2,631",
        "Speed Demons Gold Refractor Parallel": "1:5,213",
        "Speed Demons Orange Refractor Parallel": "1:10,464",
        "Speed Demons Black Refractor Parallel": "1:26,562",
        "Speed Demons Red Refractor Parallel": "1:54,165",
        "Speed Demons Superfractor Parallel": "1:345,300",
        "Top Speed": "1:6",
        "Top Speed Blue Refractor Parallel": "1:729",
        "Top Speed Green Refractor Parallel": "1:1,104",
        "Top Speed Gold Refractor Parallel": "1:2,186",
        "Top Speed Orange Refractor Parallel": "1:4,390",
        "Top Speed Black Refractor Parallel": "1:10,976",
        "Top Speed Red Refractor Parallel": "1:22,418",
        "Top Speed Superfractor Parallel": "1:150,515",
        "Futuro": "1:1,200",
        "Futuro Superfractor Parallel": "1:1,381,197",
        "Neon Nations": "1:240",
        "Neon Nations Superfractor Parallel": "1:460,399",
        "The Chain": "1:2,400",
        "The Chain Superfractor Parallel": "1:394,628",
        "Chrome Autographs Orange RayWave Parallel": "1:1,106",
        "Chrome Autographs Black RayWave Parallel": "1:2,289",
        "Chrome Autographs Red RayWave Parallel": "1:4,043",
        "F1 Diamond Anniversary Base Relic Cards": "1:138,120",
        "F2 Diamond Anniversary Base Relic Cards": "1:125,564",
        "F3 Diamond Anniversary Base Relic Cards": "1:92,080",
    },
    "logofractor": {
        "Base Yellow Logofractor Parallel": "1:2",
        "Base Gold Logofractor Parallel": "1:3",
        "Base Orange Logofractor Parallel": "1:5",
        "Base Black Logofractor Parallel": "1:11",
        "Base Red Logofractor Parallel": "1:22",
        "Base Rose Gold Logofractor Parallel": "1:106",
        "1975 Speed Wheels Logofractor": "1:6",
        "1975 Speed Wheels Yellow Logofractor Parallel": "1:29",
        "1975 Speed Wheels Gold Logofractor Parallel": "1:43",
        "1975 Speed Wheels Orange Logofractor Parallel": "1:86",
        "1975 Speed Wheels Black Logofractor Parallel": "1:213",
        "1975 Speed Wheels Red Logofractor Parallel": "1:435",
        "1975 Speed Wheels Rose Gold Logofractor Parallel": "1:2,920",
        "Ace of Trades Logofractor": "1:6",
        "Ace of Trades Yellow Logofractor Parallel": "1:29",
        "Ace of Trades Gold Logofractor Parallel": "1:43",
        "Ace of Trades Orange Logofractor Parallel": "1:86",
        "Ace of Trades Black Logofractor Parallel": "1:213",
        "Ace of Trades Red Logofractor Parallel": "1:435",
        "Ace of Trades Rose Gold Logofractor Parallel": "1:2,920",
        "Floor It Logofractor": "1:6",
        "Floor It Yellow Logofractor Parallel": "1:29",
        "Floor It Gold Logofractor Parallel": "1:43",
        "Floor It Orange Logofractor Parallel": "1:86",
        "Floor It Black Logofractor Parallel": "1:213",
        "Floor It Red Logofractor Parallel": "1:435",
        "Floor It Rose Gold Logofractor Parallel": "1:2,920",
        "Helmet Collection Logofractor": "1:6",
        "Helmet Collection Yellow Logofractor Parallel": "1:29",
        "Helmet Collection Gold Logofractor Parallel": "1:43",
        "Helmet Collection Orange Logofractor Parallel": "1:86",
        "Helmet Collection Black Logofractor Parallel": "1:213",
        "Helmet Collection Red Logofractor Parallel": "1:435",
        "Helmet Collection Rose Gold Logofractor Parallel": "1:2,920",
        "Speed Demons Logofractor": "1:6",
        "Speed Demons Yellow Logofractor Parallel": "1:26",
        "Speed Demons Gold Logofractor Parallel": "1:39",
        "Speed Demons Orange Logofractor Parallel": "1:78",
        "Speed Demons Black Logofractor Parallel": "1:197",
        "Speed Demons Red Logofractor Parallel": "1:401",
        "Speed Demons Rose Gold Logofractor Parallel": "1:2,555",
        "Chrome Autographs Black & Red Logofractor Parallel": "1:315",
    },
    "diamond_anniversary": {
        "Diamond 75th Anniversary Night Vision Mini-Diamond F1 Refractor Parallel": "1:6",
        "Diamond 75th Anniversary Purple Mini Diamond Refractor Parallel": "1:8",
        "Diamond 75th Anniversary Blue Mini Diamond Refractor Parallel": "1:11",
        "Diamond 75th Anniversary Green Mini Diamond Refractor Parallel": "1:16",
        "Diamond 75th Anniversary Gold Mini Diamond Refractor Parallel": "1:31",
        "Diamond 75th Anniversary Orange Mini Diamond Refractor Parallel": "1:62",
        "Diamond 75th Anniversary Red Mini Diamond Refractor Parallel": "1:310",
        "Diamond 75th Anniversary Superfractor Parallel": "1:1,583",
        "Diamond 75th Anniversary Autographs Superfractor Parallel": "1:3,234",
    },
}

cur.execute(
    "INSERT INTO sets (name, sport, season, league, tier, box_config, release_date, pack_odds) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
    (SET_NAME, "Racing", "2025", "F1", "Chrome", json.dumps(box_config), "2026-02-12", json.dumps(pack_odds)),
)
set_id = cur.lastrowid

# Count total odds
total = sum(len(v) for v in pack_odds.values())
print(f"Created set '{SET_NAME}' with id {set_id}")
print(f"Pack odds: {len(pack_odds)} box types, {total} total entries")

conn.commit()
conn.close()
print("Done!")
