"""
Update pack odds for 2025 Topps Chrome Deadpool (set id 46).
Usage: python3 scripts/update_chrome_deadpool_2025_odds.py
"""

import sqlite3
import json
import os

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "the-c-list.db")

conn = sqlite3.connect(DB_PATH)
conn.execute("PRAGMA journal_mode=WAL")
cur = conn.cursor()

SET_ID = 46

pack_odds = {
    "hobby": {
        "Base Cards": "1:1",
        "Base Cards Refractor": "1:2",
        "Base Cards Prism Refractor": "1:3",
        "Base Cards Yellow Wave": "1:16",
        "Base Cards Pink Shimmer": "1:20",
        "Base Cards Purple Wave": "1:22",
        "Base Cards Aqua Refractor": "1:26",
        "Base Cards Green/Aqua RayWave Refractor": "1:33",
        "Base Cards Green Lava": "1:32",
        "Base Cards Green Refractor": "1:60",
        "Base Cards Gold Lava": "1:63",
        "Base Cards Dogpool Refractor": "1:50",
        "Base Cards Gold Raywave": "1:75",
        "Base Cards TVA Takeover Refractor": "1:78",
        "Base Cards Human Torch Lava": "1:99",
        "Base Cards Orange Shimmer": "1:149",
        "Base Cards Wolverine Yellow & Blue X-Fractor": "1:270",
        "Base Cards Black Lava": "1:311",
        "Base Cards Black Refractor": "1:371",
        "Base Cards Deadpool Red & Black Wave": "1:660",
        "Base Cards Red Refractor": "1:660",
        "Base Cards Superfractor": "1:3,710",
        "Comic Book Gold": "1:3",
        "Comic Book Gold Gold Refractor": "1:264",
        "Comic Book Gold Orange Shimmer": "1:528",
        "Comic Book Gold Wolverine Yellow & Blue X-Fractor": "1:990",
        "Comic Book Gold Black Refractor": "1:1,319",
        "Comic Book Gold Deadpool Red & Black Wave": "1:3,166",
        "Comic Book Gold Red Refractor": "1:3,166",
        "Comic Book Gold Superfractor": "1:13,190",
        "Cover Stars": "1:3",
        "Cover Stars Gold Refractor": "1:264",
        "Cover Stars Orange Shimmer": "1:528",
        "Cover Stars Wolverine Yellow & Blue X-Fractor": "1:990",
        "Cover Stars Black Refractor": "1:1,319",
        "Cover Stars Deadpool Red & Black Wave": "1:3,166",
        "Cover Stars Red Refractor": "1:3,166",
        "Cover Stars Superfractor": "1:13,190",
        "Future Stars": "1:8",
        "Future Stars Gold Refractor": "1:792",
        "Future Stars Orange Shimmer": "1:1,583",
        "Future Stars Wolverine Yellow & Blue X-Fractor": "1:2,968",
        "Future Stars Black Refractor": "1:3,957",
        "Future Stars Deadpool Red & Black Wave": "1:9,497",
        "Future Stars Red Refractor": "1:9,497",
        "Future Stars Superfractor": "1:39,568",
        "Well You Got Nothing To Say Mouth": "1:8",
        "Well You Got Nothing To Say Mouth Gold Refractor": "1:792",
        "Well You Got Nothing To Say Mouth Orange Shimmer": "1:1,583",
        "Well You Got Nothing To Say Mouth Wolverine Yellow & Blue X-Fractor": "1:2,968",
        "Well You Got Nothing To Say Mouth Black Refractor": "1:3,957",
        "Well You Got Nothing To Say Mouth Deadpool Red & Black Wave": "1:9,497",
        "Well You Got Nothing To Say Mouth Red Refractor": "1:9,497",
        "Well You Got Nothing To Say Mouth Superfractor": "1:39,568",
        "10005 Fire Unnumbered Refractor": "1:1,017",
        "10005 Fire Wolverine Yellow & Blue X-Fractor": "1:2,723",
        "10005 Fire Black Refractor": "1:3,905",
        "10005 Fire Deadpool Red & Black Wave": "1:7,610",
        "10005 Fire Red Refractor": "1:7,610",
        "10005 Fire Superfractor": "1:37,095",
        "Best Bubs Unnumbered Refractor": "1:1,017",
        "Best Bubs Wolverine Yellow & Blue X-Fractor": "1:2,723",
        "Best Bubs Black Refractor": "1:3,905",
        "Best Bubs Deadpool Red & Black Wave": "1:7,610",
        "Best Bubs Red Refractor": "1:7,610",
        "Best Bubs Superfractor": "1:37,095",
        "Looking For Logan Unnumbered Refractor": "1:5,936",
        "Looking For Logan Wolverine Yellow & Blue X-Fractor": "1:4,430",
        "Looking For Logan Black Refractor": "1:6,745",
        "Looking For Logan Deadpool Red & Black Wave": "1:13,490",
        "Looking For Logan Red Refractor": "1:13,490",
        "Looking For Logan Superfractor": "1:74,190",
        "Indestructible Black Lazer": "1:6,183",
        "Indestructible Red Lazer": "1:12,365",
        "Indestructible Superfractor": "1:59,352",
        "Deadpool Reflections Unnumbered Refractor": "1:1,188",
        "Deadpool Reflections Kaleidoscope": "1:2,494",
        "Deadpool Reflections Shimmer": "1:6,183",
        "Deadpool Reflections RayWave": "1:12,365",
        "Deadpool Reflections Superfractor": "1:59,352",
        "Hidden Gems Emerald": "1:1,484",
        "Hidden Gems Citrine": "1:6,902",
        "Hidden Gems Alexandrite": "1:14,838",
        "Hidden Gems Painite": "1:74,190",
        "The Void Lava Refractor": "1:1,484",
        "The Void Wolverine Yellow & Blue X-Fractor": "1:2,076",
        "The Void Black Refractor": "1:3,124",
        "The Void Deadpool Red & Black Wave": "1:6,183",
        "The Void Red Refractor": "1:6,183",
        "The Void Superfractor": "1:29,676",
        "Deadpool Sketch Cards": "1:75",
        "Deadpool Sketch Cards Silver Foil": "1:160",
        "Deadpool Sketch Cards Gold Foil": "1:673",
        "Deadpool Sketch Cards Black Foil": "1:1,492",
        "Marvel Comic Artist Sketch Cards Black Foil": "1:3,013",
        "Topps Originals": "1:475",
        "Topps Originals Orange Shimmer": "1:1,349",
        "Topps Originals Wolverine Yellow & Blue X-Fractor": "1:2,283",
        "Topps Originals Black Refractor": "1:3,710",
        "Topps Originals Deadpool Red & Black Wave": "1:7,810",
        "Topps Originals Red Refractor": "1:8,021",
        "Topps Originals Superfractor": "1:37,095",
        "Best Bubs Autograph Refractor": "1:171",
        "Best Bubs Autograph Orange Shimmer": "1:1,331",
        "Best Bubs Autograph Wolverine Yellow & Blue X-Fractor": "1:1,879",
        "Best Bubs Autograph Black Refractor": "1:2,800",
        "Best Bubs Autograph Deadpool Red & Black Wave": "1:5,936",
        "Best Bubs Autograph Red Refractor": "1:5,936",
        "Best Bubs Autograph Superfractor": "1:26,979",
        "Chrome Autographs Refractor": "1:46",
        "Chrome Autographs Aqua Refractor": "1:130",
        "Chrome Autographs Green/Aqua RayWave Refractor": "1:138",
        "Chrome Autographs Green Refractor": "1:184",
        "Chrome Autographs Dogpool Refractor": "1:243",
        "Chrome Autographs Gold Raywave": "1:322",
        "Chrome Autographs Human Torch Lava": "1:416",
        "Chrome Autographs Orange Shimmer": "1:586",
        "Chrome Autographs Wolverine Yellow & Blue X-Fractor": "1:983",
        "Chrome Autographs Black Refractor": "1:1,470",
        "Chrome Autographs Deadpool Red & Black Wave": "1:2,968",
        "Chrome Autographs Red Refractor": "1:2,939",
        "Chrome Autographs Superfractor": "1:15,619",
        "Chrome Dual Autographs Refractor": "1:2,283",
        "Chrome Dual Autographs Gold Raywave": "1:1,492",
        "Chrome Dual Autographs Human Torch Lava": "1:931",
        "Chrome Dual Autographs Orange Shimmer": "1:1,515",
        "Chrome Dual Autographs Wolverine Yellow & Blue X-Fractor": "1:2,413",
        "Chrome Dual Autographs Black Refractor": "1:3,576",
        "Chrome Dual Autographs Deadpool Red & Black Wave": "1:7,419",
        "Chrome Dual Autographs Red Refractor": "1:7,419",
        "Chrome Dual Autographs Superfractor": "1:32,974",
        "On-Card Dual Inscriptions Book Card Refractor": "1:17,457",
        "On-Card Dual Inscriptions Book Card Black Takeover": "1:32,974",
        "On-Card Dual Inscriptions Book Card Red Takeover": "1:74,190",
        "On-Card Dual Inscriptions Book Card Superfractor": "1:296,760",
        "Marvel Comic Book Artist Autographs Refractor": "1:201",
        "Marvel Comic Book Artist Autographs Green Refractor": "1:592",
        "Marvel Comic Book Artist Autographs Gold Raywave": "1:1,202",
        "Marvel Comic Book Artist Autographs Human Torch Lava": "1:1,448",
        "Marvel Comic Book Artist Autographs Orange Shimmer": "1:2,394",
        "Marvel Comic Book Artist Autographs Wolverine Yellow & Blue X-Fractor": "1:3,710",
        "Marvel Comic Book Artist Autographs Black Refractor": "1:5,496",
        "Marvel Comic Book Artist Autographs Deadpool Red & Black Wave": "1:11,871",
        "Marvel Comic Book Artist Autographs Red Refractor": "1:11,871",
        "Marvel Comic Book Artist Autographs Superfractor": "1:49,460",
        "Deadpool Autographs": "1:990",
        "Deadpool Autographs Gold": "1:7,419",
        "Deadpool Autographs Orange": "1:14,838",
        "Deadpool Autographs Black": "1:32,974",
        "Deadpool Autographs Red": "1:74,190",
    },
    "value": {
        "Base Cards": "1:1",
        "Base Cards Refractor": "1:4",
        "Base Cards Mini Diamonds": "1:4",
        "Base Cards Yellow Wave": "1:73",
        "Base Cards Pink Shimmer": "1:108",
        "Base Cards Purple Wave": "1:148",
        "Base Cards Purple Mini Diamonds": "1:62",
        "Base Cards Blue Mini Diamonds": "1:123",
        "Base Cards Aqua Refractor": "1:195",
        "Base Cards Green/Aqua RayWave Refractor": "1:274",
        "Base Cards Green Refractor": "1:328",
        "Base Cards Dogpool Refractor": "1:1,253",
        "Base Cards Gold Raywave": "1:1,879",
        "Base Cards Human Torch Lava": "1:2,011",
        "Base Cards Orange Shimmer": "1:3,762",
        "Base Cards Wolverine Yellow & Blue X-Fractor": "1:4,384",
        "Base Cards Black Refractor": "1:9,418",
        "Base Cards Deadpool Red & Black Wave": "1:54,061",
        "Base Cards Red Refractor": "1:54,061",
        "Base Cards Superfractor": "1:97,310",
        "Comic Book Gold": "1:7",
        "Comic Book Gold Gold Refractor": "1:4,736",
        "Comic Book Gold Orange Shimmer": "1:9,471",
        "Comic Book Gold Wolverine Yellow & Blue X-Fractor": "1:11,218",
        "Comic Book Gold Black Refractor": "1:23,734",
        "Comic Book Gold Deadpool Red & Black Wave": "1:29,488",
        "Comic Book Gold Red Refractor": "1:29,488",
        "Comic Book Gold Superfractor": "1:228,964",
        "Cover Stars": "1:7",
        "Cover Stars Gold Refractor": "1:4,736",
        "Cover Stars Orange Shimmer": "1:9,471",
        "Cover Stars Wolverine Yellow & Blue X-Fractor": "1:11,218",
        "Cover Stars Black Refractor": "1:23,734",
        "Cover Stars Deadpool Red & Black Wave": "1:29,488",
        "Cover Stars Red Refractor": "1:29,488",
        "Cover Stars Superfractor": "1:228,964",
        "Future Stars": "1:19",
        "Future Stars Gold Refractor": "1:14,206",
        "Future Stars Orange Shimmer": "1:28,412",
        "Future Stars Wolverine Yellow & Blue X-Fractor": "1:33,652",
        "Future Stars Black Refractor": "1:71,202",
        "Future Stars Deadpool Red & Black Wave": "1:88,464",
        "Future Stars Red Refractor": "1:88,464",
        "Future Stars Superfractor": "1:686,890",
        "Well You Got Nothing To Say Mouth": "1:19",
        "Well You Got Nothing To Say Mouth Gold Refractor": "1:14,206",
        "Well You Got Nothing To Say Mouth Orange Shimmer": "1:28,412",
        "Well You Got Nothing To Say Mouth Wolverine Yellow & Blue X-Fractor": "1:33,652",
        "Well You Got Nothing To Say Mouth Black Refractor": "1:71,202",
        "Well You Got Nothing To Say Mouth Deadpool Red & Black Wave": "1:88,464",
        "Well You Got Nothing To Say Mouth Red Refractor": "1:88,464",
        "Well You Got Nothing To Say Mouth Superfractor": "1:686,890",
        "10005 Fire Unnumbered Refractor": "1:22,428",
        "10005 Fire Wolverine Yellow & Blue X-Fractor": "1:72,982",
        "10005 Fire Black Refractor": "1:145,964",
        "10005 Fire Deadpool Red & Black Wave": "1:291,928",
        "10005 Fire Red Refractor": "1:291,928",
        "10005 Fire Superfractor": "1:1,459,640",
        "Best Bubs Unnumbered Refractor": "1:22,428",
        "Best Bubs Wolverine Yellow & Blue X-Fractor": "1:72,982",
        "Best Bubs Black Refractor": "1:145,964",
        "Best Bubs Deadpool Red & Black Wave": "1:291,928",
        "Best Bubs Red Refractor": "1:291,928",
        "Best Bubs Superfractor": "1:1,459,640",
        "Looking For Logan Unnumbered Refractor": "1:28,782",
        "Looking For Logan Wolverine Yellow & Blue X-Fractor": "1:291,928",
        "Looking For Logan Black Refractor": "1:364,910",
        "Looking For Logan Deadpool Red & Black Wave": "1:729,820",
        "Looking For Logan Red Refractor": "1:729,820",
        "Looking For Logan Superfractor": "1:1,459,640",
        "Hidden Gems Emerald": "1:29,559",
        "Hidden Gems Citrine": "1:291,928",
        "Hidden Gems Alexandrite": "1:364,910",
        "Hidden Gems Painite": "1:1,459,640",
        "Topps Originals": "1:11,805",
        "Topps Originals Orange Shimmer": "1:78,120",
        "Topps Originals Wolverine Yellow & Blue X-Fractor": "1:140,280",
        "Topps Originals Black Refractor": "1:112,140",
        "Topps Originals Deadpool Red & Black Wave": "1:140,280",
        "Topps Originals Red Refractor": "1:156,240",
        "Topps Originals Superfractor": "1:1,093,680",
        "Deadpool Icons Refractor": "1:4",
        "Deadpool Icons Gold Refractor": "1:3,061",
        "Deadpool Icons Orange Shimmer": "1:6,082",
        "Deadpool Icons Wolverine Yellow & Blue X-Fractor": "1:10,137",
        "Deadpool Icons Black Refractor": "1:15,205",
        "Deadpool Icons Deadpool Red & Black Wave": "1:31,057",
        "Deadpool Icons Red Refractor": "1:31,057",
        "Deadpool Icons Superfractor": "1:208,520",
        "Best Bubs Autograph Refractor": "1:2,004",
        "Best Bubs Autograph Orange Shimmer": "1:15,866",
        "Best Bubs Autograph Wolverine Yellow & Blue X-Fractor": "1:45,614",
        "Best Bubs Autograph Black Refractor": "1:72,982",
        "Best Bubs Autograph Deadpool Red & Black Wave": "1:104,260",
        "Best Bubs Autograph Red Refractor": "1:104,260",
        "Best Bubs Autograph Superfractor": "1:486,547",
        "Chrome Autographs Refractor": "1:2,243",
        "Chrome Autographs Aqua Refractor": "1:1,226",
        "Chrome Autographs Green/Aqua RayWave Refractor": "1:1,632",
        "Chrome Autographs Green Refractor": "1:2,465",
        "Chrome Autographs Dogpool Refractor": "1:3,263",
        "Chrome Autographs Gold Raywave": "1:6,100",
        "Chrome Autographs Human Torch Lava": "1:7,491",
        "Chrome Autographs Orange Shimmer": "1:12,019",
        "Chrome Autographs Wolverine Yellow & Blue X-Fractor": "1:20,040",
        "Chrome Autographs Black Refractor": "1:28,782",
        "Chrome Autographs Deadpool Red & Black Wave": "1:56,070",
        "Chrome Autographs Red Refractor": "1:56,070",
        "Chrome Autographs Superfractor": "1:273,420",
        "Chrome Dual Autographs Refractor": "1:21,033",
        "Chrome Dual Autographs Gold Raywave": "1:33,946",
        "Chrome Dual Autographs Human Torch Lava": "1:69,507",
        "Chrome Dual Autographs Orange Shimmer": "1:66,348",
        "Chrome Dual Autographs Wolverine Yellow & Blue X-Fractor": "1:182,455",
        "Chrome Dual Autographs Black Refractor": "1:291,928",
        "Chrome Dual Autographs Deadpool Red & Black Wave": "1:364,910",
        "Chrome Dual Autographs Red Refractor": "1:364,910",
        "On-Card Dual Inscriptions Book Card Refractor": "1:364,560",
        "On-Card Dual Inscriptions Book Card Black Takeover": "1:1,093,680",
        "On-Card Dual Inscriptions Book Card Red Takeover": "1:1,093,680",
        "Marvel Comic Book Artist Autographs Refractor": "1:5,612",
        "Marvel Comic Book Artist Autographs Green Refractor": "1:19,462",
        "Marvel Comic Book Artist Autographs Gold Raywave": "1:35,070",
        "Marvel Comic Book Artist Autographs Human Torch Lava": "1:74,760",
        "Marvel Comic Book Artist Autographs Orange Shimmer": "1:66,348",
        "Marvel Comic Book Artist Autographs Wolverine Yellow & Blue X-Fractor": "1:182,455",
        "Marvel Comic Book Artist Autographs Black Refractor": "1:291,928",
        "Marvel Comic Book Artist Autographs Deadpool Red & Black Wave": "1:364,910",
        "Marvel Comic Book Artist Autographs Red Refractor": "1:364,910",
        "Deadpool Autographs": "1:17,535",
        "Deadpool Autographs Gold": "1:224,280",
        "Deadpool Autographs Orange": "1:364,560",
        "Deadpool Autographs Black": "1:1,093,680",
        "Deadpool Autographs Red": "1:1,093,680",
    },
}

cur.execute(
    "UPDATE sets SET pack_odds = ? WHERE id = ?",
    (json.dumps(pack_odds), SET_ID),
)
conn.commit()

total = sum(len(v) for v in pack_odds.values())
print(f"Updated pack_odds for set {SET_ID} with {len(pack_odds)} box types and {total} total odds entries.")

conn.close()
print("Done!")
