"""
Add pack odds to 2025-26 Topps Bowman Basketball (set ID 34).
Usage: python3 scripts/update_bowman_basketball_odds.py
"""
import sqlite3, json

db = sqlite3.connect('the-c-list.db')

cursor = db.execute("SELECT id FROM sets WHERE name = '2025-26 Topps Bowman Basketball'")
row = cursor.fetchone()
if not row:
    print("Set not found!")
    exit(1)

set_id = row[0]
print(f"Updating set ID: {set_id}")

# Also update box_config to add bulk
bc_row = db.execute("SELECT box_config FROM sets WHERE id = ?", (set_id,)).fetchone()
box_config = json.loads(bc_row[0]) if bc_row and bc_row[0] else {}
if 'bulk' not in box_config:
    box_config['bulk'] = {
        "cards_per_pack": 10,
        "packs_per_box": 6,
        "boxes_per_case": 40,
        "notes": "Retail bulk pack configuration"
    }
    db.execute("UPDATE sets SET box_config = ? WHERE id = ?", (json.dumps(box_config), set_id))
    print("Added bulk to box_config")

pack_odds = {
  "hobby": {
    "Base": "3:1",
    "Base Purple Border": "1:188",
    "Base Pink Border": "1:214",
    "Base Blue Border": "1:250",
    "Base Green Border": "1:533",
    "Base Green Pattern Border": "1:533",
    "Base Yellow Border": "1:499",
    "Base Gold Border": "1:748",
    "Base Black Border": "1:1,123",
    "Base Black Pattern Border": "1:1,123",
    "Base Red Border": "1:7,496",
    "Base Platinum Border": "1:38,005",
    "Base Chrome": "1:1",
    "Base Chrome Mini-Diamond Refractor": "1:30",
    "Base Chrome Reptilian Refractor": "1:10",
    "Base Chrome Refractor": "1:75",
    "Base Chrome Lava Refractor": "1:133",
    "Base Chrome Speckle Refractor": "1:126",
    "Base Chrome Purple Refractor": "1:150",
    "Base Chrome Fuchsia Refractor": "1:188",
    "Base Chrome Reptilian Fuchsia Refractor": "1:188",
    "Base Chrome Reptilian Blue Refractor": "1:250",
    "Base Chrome Blue Refractor": "1:250",
    "Base Chrome Blue Shimmer Refractor": "1:250",
    "Base Chrome Floorboard Refractor": "1:32",
    "Base Chrome Steel Metal Refractor": "1:374",
    "Base Chrome Reptilian Green Refractor": "1:533",
    "Base Chrome Green Refractor": "1:533",
    "Base Chrome Green Shimmer Refractor": "1:533",
    "Base Chrome Yellow Refractor": "1:499",
    "Base Chrome Yellow X-Fractor": "1:307",
    "Base Chrome Yellow Wave Refractor": "1:307",
    "Base Chrome Gold Refractor": "1:748",
    "Base Chrome Gold Shimmer Refractor": "1:748",
    "Base Chrome Reptilian Gold Refractor": "1:748",
    "Base Chrome Orange Refractor": "1:449",
    "Base Chrome Orange Shimmer Refractor": "1:449",
    "Base Chrome Reptilian Orange Refractor": "1:449",
    "Base Chrome Rose Gold Refractor": "1:2,167",
    "Base Chrome Rose Gold Mini-Diamond Refractor": "1:2,167",
    "Base Chrome Rose Gold X-Fractor": "1:2,167",
    "Base Chrome Black Refractor": "1:3,742",
    "Base Chrome Black X-Fractor": "1:3,742",
    "Base Chrome Red Refractor": "1:7,496",
    "Base Chrome Red Lava Refractor": "1:7,496",
    "Base Chrome Reptilian Red Refractor": "1:7,496",
    "Base Chrome Red X-Fractor": "1:795",
    "Base Chrome FireFractor": "1:12,522",
    "Base Chrome SuperFractor": "1:23,046",
    "Base Chrome Geometric": "1:3",
    "Base Chrome Green Geometric": "1:2",
    "Base Chrome Gold Geometric": "1:3",
    "Base Chrome Orange Geometric": "1:5",
    "Base Chrome Black Geometric": "1:13",
    "Base Chrome Red Geometric": "1:25",
    "Base Chrome Mojo": "1:2",
    "Base Chrome Blue Mojo": "1:78",
    "Base Chrome Green Mojo": "1:118",
    "Base Chrome Yellow Mojo": "1:156",
    "Base Chrome Gold Mojo": "1:233",
    "Base Chrome Orange Mojo": "1:466",
    "Base Chrome Red Mojo": "1:2,330",
    "Base Chrome Black Mojo": "1:1,165",
    "Base Chrome Rose Gold Mojo": "1:11,650",
    "Base Chrome Fuchsia Mojo": "1:39",
    "Base Chrome Burgundy Mojo": "1:43",
    "Base Chrome Purple Mojo": "1:47",
    "Base Chrome Pink Mojo": "1:59",
    "Base Chrome Navy Mojo": "1:67",
    "Base Chrome Aqua Mojo": "1:94",
    "Base Chrome Rookie Red RC Variation": "1:20",
    "Paper Prospect": "1:1",
    "Paper Prospect Purple Border": "1:376",
    "Paper Prospect Pink Border": "1:428",
    "Paper Prospect Blue Border": "1:499",
    "Paper Prospect Green Border": "1:1,066",
    "Paper Prospect Green Pattern Border": "1:1,066",
    "Paper Prospect Yellow Border": "1:998",
    "Paper Prospect Gold Border": "1:1,497",
    "Paper Prospect Orange Border": "1:899",
    "Paper Prospect Black Border": "1:2,245",
    "Paper Prospect Black Pattern Border": "1:2,245",
    "Paper Prospect Red Border": "1:15,044",
    "Paper Prospect Platinum Border": "1:77,366",
    "Chrome Prospect": "1:1",
    "Chrome Prospect Mini-Diamond Refractor": "1:60",
    "Chrome Prospect Reptilian Refractor": "1:20",
    "Chrome Prospect Refractor": "1:150",
    "Chrome Prospect Lava Refractor": "1:188",
    "Chrome Prospect Speckle Refractor": "1:251",
    "Chrome Prospect Purple Refractor": "1:300",
    "Chrome Prospect Fuchsia Refractor": "1:376",
    "Chrome Prospect Reptilian Blue Refractor": "1:499",
    "Chrome Prospect Blue Refractor": "1:499",
    "Chrome Prospect Aqua X-Fractor": "1:368",
    "Chrome Prospect Floorboard Refractor": "1:64",
    "Chrome Prospect Steel Metal Refractor": "1:748",
    "Chrome Prospect Reptilian Green Refractor": "1:1,066",
    "Chrome Prospect Green Refractor": "1:1,066",
    "Chrome Prospect Green Shimmer Refractor": "1:1,066",
    "Chrome Prospect Yellow Refractor": "1:998",
    "Chrome Prospect Yellow X-Fractor": "1:614",
    "Chrome Prospect Gold Refractor": "1:1,497",
    "Chrome Prospect Reptilian Gold Refractor": "1:1,497",
    "Chrome Prospect Orange Refractor": "1:899",
    "Chrome Prospect Reptilian Orange Refractor": "1:899",
    "Chrome Prospect Rose Gold Refractor": "1:4,992",
    "Chrome Prospect Rose Gold Mini-Diamond Refractor": "1:4,992",
    "Chrome Prospect Black Refractor": "1:7,496",
    "Chrome Prospect Black X-Fractor": "1:7,496",
    "Chrome Prospect Red Refractor": "1:15,044",
    "Chrome Prospect Reptilian Red Refractor": "1:15,044",
    "Chrome Prospect FireFractor": "1:25,189",
    "Chrome Prospect SuperFractor": "1:46,091",
    "Chrome Prospect Geometric": "1:5",
    "Chrome Prospect Green Geometric": "1:3",
    "Chrome Prospect Gold Geometric": "1:5",
    "Chrome Prospect Orange Geometric": "1:10",
    "Chrome Prospect Black Geometric": "1:25",
    "Chrome Prospect Red Geometric": "1:50",
    "Chrome Prospect Mojo": "1:2",
    "Chrome Prospect Blue Mojo": "1:156",
    "Chrome Prospect Green Mojo": "1:236",
    "Chrome Prospect Yellow Mojo": "1:311",
    "Chrome Prospect Gold Mojo": "1:466",
    "Chrome Prospect Orange Mojo": "1:932",
    "Chrome Prospect Red Mojo": "1:4,660",
    "Chrome Prospect Black Mojo": "1:2,330",
    "Chrome Prospect Rose Gold Mojo": "1:23,300",
    "Chrome Prospect Fuchsia Mojo": "1:78",
    "Chrome Prospect Burgundy Mojo": "1:85",
    "Chrome Prospect Purple Mojo": "1:94",
    "Chrome Prospect Pink Mojo": "1:118",
    "Chrome Prospect Navy Mojo": "1:134",
    "Chrome Prospect Aqua Mojo": "1:187",
    "Talent Tracker": "1:58",
    "Gen Next": "1:58",
    "Very Important Prospects": "1:58",
    "Bowman Verified": "1:58",
    "Talent Tracker Refractor": "1:60",
    "Gen Next Refractor": "1:60",
    "Very Important Prospects Refractor": "1:60",
    "Bowman Verified Refractor": "1:60",
    "Talent Tracker Purple Refractor": "1:1,197",
    "Gen Next Purple Refractor": "1:1,197",
    "Very Important Prospects Purple Refractor": "1:1,197",
    "Bowman Verified Purple Refractor": "1:1,197",
    "Talent Tracker Fuchsia Refractor": "1:1,504",
    "Gen Next Fuchsia Refractor": "1:1,504",
    "Very Important Prospects Fuchsia Refractor": "1:1,504",
    "Bowman Verified Fuchsia Refractor": "1:1,504",
    "Talent Tracker Mini-Diamond Refractor": "1:1,995",
    "Gen Next Mini-Diamond Refractor": "1:1,995",
    "Very Important Prospects Mini-Diamond Refractor": "1:1,995",
    "Bowman Verified Mini-Diamond Refractor": "1:1,995",
    "Talent Tracker Green Refractor": "1:4,261",
    "Gen Next Green Refractor": "1:4,261",
    "Very Important Prospects Green Refractor": "1:4,261",
    "Bowman Verified Green Refractor": "1:4,261",
    "Talent Tracker Aqua Refractor": "1:2,394",
    "Gen Next Aqua Refractor": "1:2,394",
    "Very Important Prospects Aqua Refractor": "1:2,394",
    "Bowman Verified Aqua Refractor": "1:2,394",
    "Talent Tracker Gold Refractor": "1:5,985",
    "Gen Next Gold Refractor": "1:5,985",
    "Very Important Prospects Gold Refractor": "1:5,985",
    "Bowman Verified Gold Refractor": "1:5,985",
    "Talent Tracker Orange Refractor": "1:3,593",
    "Gen Next Orange Refractor": "1:3,593",
    "Very Important Prospects Orange Refractor": "1:3,593",
    "Bowman Verified Orange Refractor": "1:3,593",
    "Talent Tracker Red Refractor": "1:60,174",
    "Gen Next Red Refractor": "1:60,174",
    "Very Important Prospects Red Refractor": "1:60,174",
    "Bowman Verified Red Refractor": "1:60,174",
    "Talent Tracker SuperFractor": "1:309,463",
    "Gen Next SuperFractor": "1:309,463",
    "Very Important Prospects SuperFractor": "1:309,463",
    "Bowman Verified SuperFractor": "1:309,463",
    "Talent Tracker Geometric": "1:73",
    "Gen Next Geometric": "1:73",
    "Very Important Prospects Geometric": "1:73",
    "Bowman Verified Geometric": "1:73",
    "Talent Tracker Gold Geometric": "1:20",
    "Gen Next Gold Geometric": "1:20",
    "Very Important Prospects Gold Geometric": "1:20",
    "Bowman Verified Gold Geometric": "1:20",
    "Talent Tracker Orange Geometric": "1:40",
    "Gen Next Orange Geometric": "1:40",
    "Very Important Prospects Orange Geometric": "1:40",
    "Bowman Verified Orange Geometric": "1:40",
    "Talent Tracker Black Geometric": "1:99",
    "Gen Next Black Geometric": "1:99",
    "Very Important Prospects Black Geometric": "1:99",
    "Bowman Verified Black Geometric": "1:99",
    "Talent Tracker Red Geometric": "1:197",
    "Gen Next Red Geometric": "1:197",
    "Very Important Prospects Red Geometric": "1:197",
    "Bowman Verified Red Geometric": "1:197",
    "ROY Favorites": "1:25",
    "Hobby Stars": "1:25",
    "Young Kings": "1:15",
    "Rockstar Rookies": "1:19",
    "Greatness Loading": "1:15",
    "ROY Favorites Refractor": "1:100",
    "Hobby Stars Refractor": "1:100",
    "Young Kings Refractor": "1:60",
    "Rockstar Rookies Refractor": "1:75",
    "Greatness Loading Refractor": "1:60",
    "ROY Favorites Purple Refractor": "1:1,995",
    "Hobby Stars Purple Refractor": "1:1,995",
    "Young Kings Purple Refractor": "1:1,197",
    "Rockstar Rookies Purple Refractor": "1:1,497",
    "Greatness Loading Purple Refractor": "1:1,197",
    "ROY Favorites Fuchsia Refractor": "1:2,508",
    "Hobby Stars Fuchsia Refractor": "1:2,508",
    "Young Kings Fuchsia Refractor": "1:1,504",
    "Rockstar Rookies Fuchsia Refractor": "1:1,879",
    "Greatness Loading Fuchsia Refractor": "1:1,504",
    "ROY Favorites Mini-Diamond Refractor": "1:3,328",
    "Hobby Stars Mini-Diamond Refractor": "1:3,328",
    "Young Kings Mini-Diamond Refractor": "1:1,995",
    "Rockstar Rookies Mini-Diamond Refractor": "1:2,493",
    "Greatness Loading Mini-Diamond Refractor": "1:1,995",
    "ROY Favorites Green Refractor": "1:7,107",
    "Hobby Stars Green Refractor": "1:7,107",
    "Young Kings Green Refractor": "1:4,261",
    "Rockstar Rookies Green Refractor": "1:5,330",
    "Greatness Loading Green Refractor": "1:4,261",
    "ROY Favorites Aqua Refractor": "1:3,990",
    "Hobby Stars Aqua Refractor": "1:3,990",
    "Young Kings Aqua Refractor": "1:2,394",
    "Rockstar Rookies Aqua Refractor": "1:2,993",
    "Greatness Loading Aqua Refractor": "1:2,394",
    "ROY Favorites Gold Refractor": "1:9,983",
    "Hobby Stars Gold Refractor": "1:9,983",
    "Young Kings Gold Refractor": "1:5,985",
    "Rockstar Rookies Gold Refractor": "1:7,496",
    "Greatness Loading Gold Refractor": "1:5,985",
    "ROY Favorites Orange Refractor": "1:6,001",
    "Hobby Stars Orange Refractor": "1:6,001",
    "Young Kings Orange Refractor": "1:3,593",
    "Rockstar Rookies Orange Refractor": "1:4,495",
    "Greatness Loading Orange Refractor": "1:3,593",
    "ROY Favorites Red Refractor": "1:103,155",
    "Hobby Stars Red Refractor": "1:103,155",
    "Young Kings Red Refractor": "1:60,174",
    "Rockstar Rookies Red Refractor": "1:77,366",
    "Greatness Loading Red Refractor": "1:60,174",
    "ROY Favorites SuperFractor": "1:541,560",
    "Hobby Stars SuperFractor": "1:541,560",
    "Young Kings SuperFractor": "1:309,463",
    "Rockstar Rookies SuperFractor": "1:433,248",
    "Greatness Loading SuperFractor": "1:309,463",
    "ROY Favorites Geometric": "1:122",
    "Hobby Stars Geometric": "1:122",
    "Young Kings Geometric": "1:73",
    "Rockstar Rookies Geometric": "1:91",
    "Greatness Loading Geometric": "1:73",
    "ROY Favorites Gold Geometric": "1:33",
    "Hobby Stars Gold Geometric": "1:33",
    "Young Kings Gold Geometric": "1:20",
    "Rockstar Rookies Gold Geometric": "1:25",
    "Greatness Loading Gold Geometric": "1:20",
    "ROY Favorites Orange Geometric": "1:66",
    "Hobby Stars Orange Geometric": "1:66",
    "Young Kings Orange Geometric": "1:40",
    "Rockstar Rookies Orange Geometric": "1:50",
    "Greatness Loading Orange Geometric": "1:40",
    "ROY Favorites Black Geometric": "1:165",
    "Hobby Stars Black Geometric": "1:165",
    "Young Kings Black Geometric": "1:99",
    "Rockstar Rookies Black Geometric": "1:123",
    "Greatness Loading Black Geometric": "1:99",
    "ROY Favorites Red Geometric": "1:329",
    "Hobby Stars Red Geometric": "1:329",
    "Young Kings Red Geometric": "1:197",
    "Rockstar Rookies Red Geometric": "1:247",
    "Greatness Loading Red Geometric": "1:197",
    "Base Chrome Etched-In Glass Variation Refractor": "1:1,733",
    "Chrome Prospect Etched-In Glass Variation Refractor": "1:3,466",
    "Base Chrome Retrofractor Refractor": "1:13,050",
    "Bowman Spotlights NBA Refractor": "1:1,733",
    "Bowman Spotlights NIL Refractor": "1:3,466",
    "Anime NBA Refractor": "1:1,663",
    "Anime NIL Refractor": "1:6,506",
    "Bowman GPK NBA Refractor": "1:13,050",
    "Bowman GPK NIL Refractor": "1:16,288",
    "Base Chrome Retrofractor Gold Refractor": "1:65,644",
    "Base Chrome Retrofractor Orange Refractor": "1:135,390",
    "Base Chrome Retrofractor Red Refractor": "1:433,248",
    "Bowman Spotlights NBA Red Refractor": "1:86,650",
    "Bowman Spotlights NIL Red Refractor": "1:144,416",
    "Anime NBA Red Refractor": "1:52,836",
    "Anime NIL Red Refractor": "1:270,780",
    "Bowman GPK NBA Red Refractor": "1:196,931",
    "Bowman GPK NIL Red Refractor": "1:270,780",
    "Base Chrome Retrofractor SuperFractor": "1:2,166,240",
    "Bowman Spotlights NBA SuperFractor": "1:361,040",
    "Bowman Spotlights NIL SuperFractor": "1:722,080",
    "Anime NBA SuperFractor": "1:196,931",
    "Anime NIL SuperFractor": "1:722,080",
    "Bowman GPK NBA SuperFractor": "1:722,080",
    "Bowman GPK NIL SuperFractor": "1:1,083,120",
    "Anime NBA Black Refractor": "1:26,100",
    "Anime NIL Black Refractor": "1:135,390",
    "Crystalized NBA": "1:1,346",
    "Crystalized NIL": "1:2,691",
    "Crystalized NBA Gold Crystal Refractor": "1:13,050",
    "Crystalized NIL Gold Crystal Refractor": "1:26,100",
    "Crystalized NBA Orange Crystal Refractor": "1:26,100",
    "Crystalized NIL Orange Crystal Refractor": "1:52,836",
    "Crystalized NBA Red Crystal Refractor": "1:135,390",
    "Crystalized NIL Red Crystal Refractor": "1:270,780",
    "Crystalized NBA SuperFractor": "1:722,080",
    "Crystalized NIL SuperFractor": "1:2,166,240",
    "Future Script": "1:1,889",
    "Buzz Factor Autographs": "1:1,417",
    "Opening Statement Signatures": "1:1,731",
    "Timeless Touch Signatures": "1:72",
    "Future Script Gold Refractor": "1:4,430",
    "Buzz Factor Autographs Gold Refractor": "1:4,080",
    "Opening Statement Signatures Gold Refractor": "1:4,240",
    "Timeless Touch Signatures Gold Refractor": "1:4,629",
    "Future Script Orange Refractor": "1:8,842",
    "Buzz Factor Autographs Orange Refractor": "1:8,144",
    "Opening Statement Signatures Orange Refractor": "1:8,144",
    "Timeless Touch Signatures Orange Refractor": "1:8,144",
    "Future Script Black Refractor": "1:20,246",
    "Buzz Factor Autographs Black Refractor": "1:20,246",
    "Opening Statement Signatures Black Refractor": "1:20,246",
    "Timeless Touch Signatures Black Refractor": "1:20,246",
    "Future Script Red Refractor": "1:40,116",
    "Buzz Factor Autographs Red Refractor": "1:40,116",
    "Opening Statement Signatures Red Refractor": "1:40,116",
    "Timeless Touch Signatures Red Refractor": "1:40,116",
    "Future Script SuperFractor": "1:196,931",
    "Buzz Factor Autographs SuperFractor": "1:196,931",
    "Opening Statement Signatures SuperFractor": "1:196,931",
    "Timeless Touch Signatures SuperFractor": "1:196,931",
    "Bowman Dual Autographs": "1:49,233",
    "Bowman Dual Autographs SuperFractor": "1:433,248",
    "Base Chrome Retrofractor Autograph Gold Refractor": "1:120,347",
    "Base Chrome Retrofractor Autograph Orange Refractor": "1:240,694",
    "Base Chrome Retrofractor Autograph Red Refractor": "1:722,080",
    "Base Chrome Retrofractor Autograph SuperFractor": "1:2,166,240",
    "Base Chrome Autograph": "1:68",
    "Base Chrome Autograph Refractor": "1:192",
    "Base Chrome Autograph Speckle Refractor": "1:342",
    "Base Chrome Autograph Purple Refractor": "1:325",
    "Base Chrome Autograph Blue Refractor": "1:416",
    "Base Chrome Autograph Blue X-Fractor": "1:621",
    "Base Chrome Autograph Mini-Diamond Refractor": "1:742",
    "Base Chrome Autograph Green Refractor": "1:695",
    "Base Chrome Autograph Green Shimmer Refractor": "1:951",
    "Base Chrome Autograph Reptilian Green Refractor": "1:872",
    "Base Chrome Autograph Yellow Refractor": "1:853",
    "Base Chrome Autograph Gold Refractor": "1:1,161",
    "Base Chrome Autograph Gold Shimmer Refractor": "1:1,346",
    "Base Chrome Autograph Reptilian Orange Refractor": "1:1,097",
    "Base Chrome Autograph Orange Refractor": "1:913",
    "Base Chrome Autograph Orange Shimmer Refractor": "1:1,032",
    "Base Chrome Autograph Black Refractor": "1:5,246",
    "Base Chrome Autograph Black X-Fractor": "1:5,443",
    "Base Chrome Autograph Red Refractor": "1:10,465",
    "Base Chrome Autograph Red Lava Refractor": "1:10,568",
    "Base Chrome Autograph FireFractor": "1:21,015",
    "Base Chrome Autograph SuperFractor": "1:50,378",
    "Base Chrome Autograph Geometric": "1:4",
    "Base Chrome Autograph Blue Geometric": "1:3",
    "Base Chrome Autograph Green Geometric": "1:4",
    "Base Chrome Autograph Gold Geometric": "1:6",
    "Base Chrome Autograph Orange Geometric": "1:11",
    "Base Chrome Autograph Black Geometric": "1:26",
    "Base Chrome Autograph Red Geometric": "1:50",
    "Base Chrome Autograph Mojo": "1:190",
    "Base Chrome Autograph Blue Mojo": "1:293",
    "Base Chrome Autograph Green Mojo": "1:321",
    "Base Chrome Autograph Yellow Mojo": "1:402",
    "Base Chrome Autograph Gold Mojo": "1:558",
    "Base Chrome Autograph Orange Mojo": "1:1,027",
    "Base Chrome Autograph Red Mojo": "1:2,523",
    "Base Chrome Autograph Black Mojo": "1:5,017",
    "Base Chrome Autograph Rose Gold Mojo": "1:25,085",
    "Chrome Prospect Autograph": "1:76",
    "Chrome Prospect Autograph Refractor": "1:100",
    "Chrome Prospect Autograph Speckle Refractor": "1:168",
    "Chrome Prospect Autograph Purple Refractor": "1:203",
    "Chrome Prospect Autograph Blue Refractor": "1:325",
    "Chrome Prospect Autograph Blue X-Fractor": "1:332",
    "Chrome Prospect Autograph Mini-Diamond Refractor": "1:476",
    "Chrome Prospect Autograph Green Refractor": "1:631",
    "Chrome Prospect Autograph Green Shimmer Refractor": "1:633",
    "Chrome Prospect Autograph Reptilian Green Refractor": "1:637",
    "Chrome Prospect Autograph Yellow Refractor": "1:701",
    "Chrome Prospect Autograph Gold Refractor": "1:1,048",
    "Chrome Prospect Autograph Gold Shimmer Refractor": "1:1,046",
    "Chrome Prospect Autograph Reptilian Orange Refractor": "1:877",
    "Chrome Prospect Autograph Orange Refractor": "1:876",
    "Chrome Prospect Autograph Orange Shimmer Refractor": "1:876",
    "Chrome Prospect Autograph Black Refractor": "1:5,171",
    "Chrome Prospect Autograph Black X-Fractor": "1:5,246",
    "Chrome Prospect Autograph Red Refractor": "1:10,267",
    "Chrome Prospect Autograph Red Lava Refractor": "1:10,267",
    "Chrome Prospect Autograph FireFractor": "1:20,719",
    "Chrome Prospect Autograph SuperFractor": "1:50,378",
    "Chrome Prospect Autograph Green Geometric": "1:4",
    "Chrome Prospect Autograph Gold Geometric": "1:5",
    "Chrome Prospect Autograph Orange Geometric": "1:10",
    "Chrome Prospect Autograph Black Geometric": "1:25",
    "Chrome Prospect Autograph Red Geometric": "1:49",
    "Chrome Prospect Autograph Mojo": "1:263",
    "Chrome Prospect Autograph Blue Mojo": "1:293",
    "Chrome Prospect Autograph Green Mojo": "1:293",
    "Chrome Prospect Autograph Yellow Mojo": "1:324",
    "Chrome Prospect Autograph Gold Mojo": "1:462",
    "Chrome Prospect Autograph Orange Mojo": "1:923",
    "Chrome Prospect Autograph Red Mojo": "1:2,306",
    "Chrome Prospect Autograph Black Mojo": "1:4,612",
    "Chrome Prospect Autograph Rose Gold Mojo": "1:23,058",
    "Base Paper Retail Autographs": "1:3,816",
    "Paper Prospect Retail Autograph": "1:778",
    "Mega Rookies": "1:13",
    "Mega Prospects": "1:13",
    "Mega Rookies Blue Mojo": "1:622",
    "Mega Prospects Blue Mojo": "1:622",
    "Mega Rookies Green Mojo": "1:942",
    "Mega Prospects Green Mojo": "1:942",
    "Mega Rookies Yellow Mojo": "1:1,243",
    "Mega Prospects Yellow Mojo": "1:1,243",
    "Mega Rookies Gold Mojo": "1:1,864",
    "Mega Prospects Gold Mojo": "1:1,864",
    "Mega Rookies Orange Mojo": "1:3,728",
    "Mega Prospects Orange Mojo": "1:3,728",
    "Mega Rookies Red Mojo": "1:18,640",
    "Mega Prospects Red Mojo": "1:18,640",
    "Mega Rookies Black Mojo": "1:9,320",
    "Mega Prospects Black Mojo": "1:9,320",
    "Mega Rookies Rose Gold Mojo": "1:93,200",
    "Mega Prospects Rose Gold Mojo": "1:93,200",
  },
  "jumbo": {
    "Base": "6:1",
    "Base Purple Border": "1:64",
    "Base Pink Border": "1:73",
    "Base Blue Border": "1:85",
    "Base Green Border": "1:72",
    "Base Green Pattern Border": "1:72",
    "Base Yellow Border": "1:138",
    "Base Gold Border": "1:190",
    "Base Red Border": "1:2,529",
    "Base Platinum Border": "1:12,772",
    "Base Chrome": "1:1",
    "Base Chrome Reptilian Refractor": "1:3",
    "Base Chrome Refractor": "1:26",
    "Base Chrome Speckle Refractor": "1:37",
    "Base Chrome Purple Refractor": "1:51",
    "Base Chrome Fuchsia Refractor": "1:64",
    "Base Chrome Reptilian Fuchsia Refractor": "1:64",
    "Base Chrome Reptilian Blue Refractor": "1:85",
    "Base Chrome Blue Refractor": "1:85",
    "Base Chrome Blue Shimmer Refractor": "1:85",
    "Base Chrome Steel Metal Refractor": "1:127",
    "Base Chrome Reptilian Green Refractor": "1:72",
    "Base Chrome Green Refractor": "1:72",
    "Base Chrome Green Shimmer Refractor": "1:72",
    "Base Chrome Yellow Refractor": "1:169",
    "Base Chrome Yellow X-Fractor": "1:104",
    "Base Chrome Yellow Wave Refractor": "1:104",
    "Base Chrome Gold Refractor": "1:253",
    "Base Chrome Gold Shimmer Refractor": "1:253",
    "Base Chrome Reptilian Gold Refractor": "1:253",
    "Base Chrome Rose Gold Refractor": "1:665",
    "Base Chrome Rose Gold Mini-Diamond Refractor": "1:665",
    "Base Chrome Rose Gold X-Fractor": "1:728",
    "Base Chrome Black Refractor": "1:1,263",
    "Base Chrome Black X-Fractor": "1:1,263",
    "Base Chrome Red Refractor": "1:2,529",
    "Base Chrome Red Lava Refractor": "1:2,529",
    "Base Chrome Reptilian Red Refractor": "1:2,529",
    "Base Chrome FireFractor": "1:4,211",
    "Base Chrome SuperFractor": "1:7,820",
    "Base Chrome Rookie Red RC Variation": "1:6",
    "Paper Prospect": "1:1",
    "Paper Prospect Purple Border": "1:127",
    "Paper Prospect Pink Border": "1:145",
    "Paper Prospect Blue Border": "1:169",
    "Paper Prospect Green Border": "1:144",
    "Paper Prospect Green Pattern Border": "1:144",
    "Paper Prospect Yellow Border": "1:337",
    "Paper Prospect Gold Border": "1:505",
    "Paper Prospect Red Border": "1:5,075",
    "Paper Prospect Platinum Border": "1:25,543",
    "Chrome Prospect": "1:1",
    "Chrome Prospect Reptilian Refractor": "1:6",
    "Chrome Prospect Refractor": "1:51",
    "Chrome Prospect Lava Refractor": "1:64",
    "Chrome Prospect Speckle Refractor": "1:85",
    "Chrome Prospect Purple Refractor": "1:101",
    "Chrome Prospect Fuchsia Refractor": "1:127",
    "Chrome Prospect Reptilian Blue Refractor": "1:169",
    "Chrome Prospect Blue Refractor": "1:169",
    "Chrome Prospect Aqua X-Fractor": "1:125",
    "Chrome Prospect Steel Metal Refractor": "1:253",
    "Chrome Prospect Reptilian Green Refractor": "1:144",
    "Chrome Prospect Green Refractor": "1:144",
    "Chrome Prospect Green Shimmer Refractor": "1:144",
    "Chrome Prospect Yellow Refractor": "1:337",
    "Chrome Prospect Yellow X-Fractor": "1:207",
    "Chrome Prospect Gold Refractor": "1:505",
    "Chrome Prospect Reptilian Gold Refractor": "1:505",
    "Chrome Prospect Rose Gold Refractor": "1:1,685",
    "Chrome Prospect Rose Gold Mini-Diamond Refractor": "1:1,685",
    "Chrome Prospect Black Refractor": "1:2,529",
    "Chrome Prospect Black X-Fractor": "1:2,529",
    "Chrome Prospect Red Refractor": "1:5,075",
    "Chrome Prospect Reptilian Red Refractor": "1:5,075",
    "Chrome Prospect FireFractor": "1:8,421",
    "Chrome Prospect SuperFractor": "1:15,639",
    "Talent Tracker": "1:8",
    "Gen Next": "1:8",
    "Very Important Prospects": "1:8",
    "Bowman Verified": "1:8",
    "Talent Tracker Refractor": "1:21",
    "Gen Next Refractor": "1:21",
    "Very Important Prospects Refractor": "1:21",
    "Bowman Verified Refractor": "1:21",
    "Talent Tracker Purple Refractor": "1:404",
    "Gen Next Purple Refractor": "1:404",
    "Very Important Prospects Purple Refractor": "1:404",
    "Bowman Verified Purple Refractor": "1:404",
    "Talent Tracker Fuchsia Refractor": "1:508",
    "Gen Next Fuchsia Refractor": "1:508",
    "Very Important Prospects Fuchsia Refractor": "1:508",
    "Bowman Verified Fuchsia Refractor": "1:508",
    "Talent Tracker Mini-Diamond Refractor": "1:673",
    "Gen Next Mini-Diamond Refractor": "1:673",
    "Very Important Prospects Mini-Diamond Refractor": "1:673",
    "Bowman Verified Mini-Diamond Refractor": "1:673",
    "Talent Tracker Green Refractor": "1:575",
    "Gen Next Green Refractor": "1:575",
    "Very Important Prospects Green Refractor": "1:575",
    "Bowman Verified Green Refractor": "1:575",
    "Talent Tracker Aqua Refractor": "1:808",
    "Gen Next Aqua Refractor": "1:808",
    "Very Important Prospects Aqua Refractor": "1:808",
    "Bowman Verified Aqua Refractor": "1:808",
    "Talent Tracker Gold Refractor": "1:2,022",
    "Gen Next Gold Refractor": "1:2,022",
    "Very Important Prospects Gold Refractor": "1:2,022",
    "Bowman Verified Gold Refractor": "1:2,022",
    "Talent Tracker Red Refractor": "1:20,711",
    "Gen Next Red Refractor": "1:20,711",
    "Very Important Prospects Red Refractor": "1:20,711",
    "Bowman Verified Red Refractor": "1:20,711",
    "Talent Tracker SuperFractor": "1:109,468",
    "Gen Next SuperFractor": "1:109,468",
    "Very Important Prospects SuperFractor": "1:109,468",
    "Bowman Verified SuperFractor": "1:109,468",
    "ROY Favorites": "1:13",
    "Hobby Stars": "1:13",
    "Young Kings": "1:8",
    "Rockstar Rookies": "1:10",
    "Greatness Loading": "1:8",
    "ROY Favorites Refractor": "1:34",
    "Hobby Stars Refractor": "1:34",
    "Young Kings Refractor": "1:21",
    "Rockstar Rookies Refractor": "1:26",
    "Greatness Loading Refractor": "1:21",
    "ROY Favorites Purple Refractor": "1:673",
    "Hobby Stars Purple Refractor": "1:673",
    "Young Kings Purple Refractor": "1:404",
    "Rockstar Rookies Purple Refractor": "1:505",
    "Greatness Loading Purple Refractor": "1:404",
    "ROY Favorites Fuchsia Refractor": "1:846",
    "Hobby Stars Fuchsia Refractor": "1:846",
    "Young Kings Fuchsia Refractor": "1:508",
    "Rockstar Rookies Fuchsia Refractor": "1:634",
    "Greatness Loading Fuchsia Refractor": "1:508",
    "ROY Favorites Mini-Diamond Refractor": "1:1,122",
    "Hobby Stars Mini-Diamond Refractor": "1:1,122",
    "Young Kings Mini-Diamond Refractor": "1:673",
    "Rockstar Rookies Mini-Diamond Refractor": "1:842",
    "Greatness Loading Mini-Diamond Refractor": "1:673",
    "ROY Favorites Green Refractor": "1:962",
    "Hobby Stars Green Refractor": "1:962",
    "Young Kings Green Refractor": "1:575",
    "Rockstar Rookies Green Refractor": "1:725",
    "Greatness Loading Green Refractor": "1:575",
    "ROY Favorites Aqua Refractor": "1:1,347",
    "Hobby Stars Aqua Refractor": "1:1,347",
    "Young Kings Aqua Refractor": "1:808",
    "Rockstar Rookies Aqua Refractor": "1:1,010",
    "Greatness Loading Aqua Refractor": "1:808",
    "ROY Favorites Gold Refractor": "1:3,376",
    "Hobby Stars Gold Refractor": "1:3,376",
    "Young Kings Gold Refractor": "1:2,022",
    "Rockstar Rookies Gold Refractor": "1:2,529",
    "Greatness Loading Gold Refractor": "1:2,022",
    "ROY Favorites Red Refractor": "1:34,831",
    "Hobby Stars Red Refractor": "1:34,831",
    "Young Kings Red Refractor": "1:20,711",
    "Rockstar Rookies Red Refractor": "1:25,543",
    "Greatness Loading Red Refractor": "1:20,711",
    "ROY Favorites SuperFractor": "1:191,568",
    "Hobby Stars SuperFractor": "1:191,568",
    "Young Kings SuperFractor": "1:109,468",
    "Rockstar Rookies SuperFractor": "1:127,712",
    "Greatness Loading SuperFractor": "1:109,468",
    "Base Chrome Etched-In Glass Variation Refractor": "1:548",
    "Chrome Prospect Etched-In Glass Variation Refractor": "1:1,095",
    "Base Chrome Retrofractor Refractor": "1:4,379",
    "Bowman Spotlights NBA Refractor": "1:548",
    "Bowman Spotlights NIL Refractor": "1:1,095",
    "Anime NBA Refractor": "1:559",
    "Anime NIL Refractor": "1:2,184",
    "Bowman GPK NBA Refractor": "1:4,379",
    "Bowman GPK NIL Refractor": "1:5,474",
    "Base Chrome Retrofractor Gold Refractor": "1:21,894",
    "Base Chrome Retrofractor Orange Refractor": "1:45,075",
    "Base Chrome Retrofractor Red Refractor": "1:255,424",
    "Bowman Spotlights NBA Red Refractor": "1:30,651",
    "Bowman Spotlights NIL Red Refractor": "1:76,628",
    "Anime NBA Red Refractor": "1:17,821",
    "Anime NIL Red Refractor": "1:95,784",
    "Bowman GPK NBA Red Refractor": "1:95,784",
    "Bowman GPK NIL Red Refractor": "1:109,468",
    "Base Chrome Retrofractor SuperFractor": "1:766,272",
    "Bowman Spotlights NBA SuperFractor": "1:191,568",
    "Bowman Spotlights NIL SuperFractor": "1:383,136",
    "Anime NBA SuperFractor": "1:95,784",
    "Anime NIL SuperFractor": "1:766,272",
    "Bowman GPK NBA SuperFractor": "1:766,272",
    "Bowman GPK NIL SuperFractor": "1:766,272",
    "Anime NBA Black Refractor": "1:8,808",
    "Anime NIL Black Refractor": "1:45,075",
    "Crystalized NBA": "1:1,474",
    "Crystalized NIL": "1:2,948",
    "Crystalized NBA Gold Crystal Refractor": "1:4,379",
    "Crystalized NIL Gold Crystal Refractor": "1:8,808",
    "Crystalized NBA Orange Crystal Refractor": "1:8,808",
    "Crystalized NIL Orange Crystal Refractor": "1:17,821",
    "Crystalized NBA Red Crystal Refractor": "1:58,944",
    "Crystalized NIL Red Crystal Refractor": "1:95,784",
    "Crystalized NBA SuperFractor": "1:255,424",
    "Crystalized NIL SuperFractor": "1:766,272",
    "Future Script": "1:636",
    "Buzz Factor Autographs": "1:477",
    "Opening Statement Signatures": "1:582",
    "Timeless Touch Signatures": "1:17",
    "Future Script Gold Refractor": "1:1,494",
    "Buzz Factor Autographs Gold Refractor": "1:1,374",
    "Opening Statement Signatures Gold Refractor": "1:1,433",
    "Timeless Touch Signatures Gold Refractor": "1:1,561",
    "Future Script Orange Refractor": "1:2,994",
    "Buzz Factor Autographs Orange Refractor": "1:2,747",
    "Opening Statement Signatures Orange Refractor": "1:2,747",
    "Timeless Touch Signatures Orange Refractor": "1:2,747",
    "Future Script Black Refractor": "1:6,904",
    "Buzz Factor Autographs Black Refractor": "1:6,904",
    "Opening Statement Signatures Black Refractor": "1:6,904",
    "Timeless Touch Signatures Black Refractor": "1:6,904",
    "Future Script Red Refractor": "1:13,933",
    "Buzz Factor Autographs Red Refractor": "1:13,933",
    "Opening Statement Signatures Red Refractor": "1:13,933",
    "Timeless Touch Signatures Red Refractor": "1:13,933",
    "Future Script SuperFractor": "1:69,662",
    "Buzz Factor Autographs SuperFractor": "1:69,662",
    "Opening Statement Signatures SuperFractor": "1:69,662",
    "Timeless Touch Signatures SuperFractor": "1:69,662",
    "Bowman Dual Autographs": "1:17,416",
    "Bowman Dual Autographs SuperFractor": "1:191,568",
    "Base Chrome Retrofractor Autograph Gold Refractor": "1:42,571",
    "Base Chrome Retrofractor Autograph Orange Refractor": "1:85,142",
    "Base Chrome Retrofractor Autograph Red Refractor": "1:766,272",
    "Base Chrome Autograph": "1:20",
    "Base Chrome Autograph Refractor": "1:65",
    "Base Chrome Autograph Speckle Refractor": "1:115",
    "Base Chrome Autograph Purple Refractor": "1:109",
    "Base Chrome Autograph Blue Refractor": "1:140",
    "Base Chrome Autograph Blue X-Fractor": "1:209",
    "Base Chrome Autograph Mini-Diamond Refractor": "1:250",
    "Base Chrome Autograph Green Refractor": "1:156",
    "Base Chrome Autograph Green Shimmer Refractor": "1:214",
    "Base Chrome Autograph Reptilian Green Refractor": "1:196",
    "Base Chrome Autograph Yellow Refractor": "1:287",
    "Base Chrome Autograph Gold Refractor": "1:391",
    "Base Chrome Autograph Gold Shimmer Refractor": "1:453",
    "Base Chrome Autograph Black Refractor": "1:1,770",
    "Base Chrome Autograph Black X-Fractor": "1:1,838",
    "Base Chrome Autograph Red Refractor": "1:3,548",
    "Base Chrome Autograph Red Lava Refractor": "1:3,598",
    "Base Chrome Autograph SuperFractor": "1:17,821",
    "Chrome Prospect Autograph": "1:16",
    "Chrome Prospect Autograph Refractor": "1:34",
    "Chrome Prospect Autograph Speckle Refractor": "1:57",
    "Chrome Prospect Autograph Purple Refractor": "1:69",
    "Chrome Prospect Autograph Blue Refractor": "1:110",
    "Chrome Prospect Autograph Blue X-Fractor": "1:112",
    "Chrome Prospect Autograph Mini-Diamond Refractor": "1:161",
    "Chrome Prospect Autograph Green Refractor": "1:142",
    "Chrome Prospect Autograph Green Shimmer Refractor": "1:143",
    "Chrome Prospect Autograph Reptilian Green Refractor": "1:143",
    "Chrome Prospect Autograph Yellow Refractor": "1:236",
    "Chrome Prospect Autograph Gold Refractor": "1:353",
    "Chrome Prospect Autograph Gold Shimmer Refractor": "1:352",
    "Chrome Prospect Autograph Black Refractor": "1:1,746",
    "Chrome Prospect Autograph Black X-Fractor": "1:1,770",
    "Chrome Prospect Autograph Red Refractor": "1:3,484",
    "Chrome Prospect Autograph Red Lava Refractor": "1:3,484",
    "Chrome Prospect Autograph SuperFractor": "1:17,821",
    "Base Paper Retail Autographs": "1:863",
    "Paper Prospect Retail Autograph": "1:175",
  },
  "breakers_delight": {
    "Base": "5:1",
    "Base Chrome Rookie Red RC Variation": "1:1",
    "Base Chrome Retrofractor Refractor": "1:43,586",
    "Bowman Spotlights NBA Refractor": "1:27",
    "Bowman Spotlights NIL Refractor": "1:53",
    "Anime NBA Refractor": "1:8,050",
    "Anime NIL Refractor": "1:21,793",
    "Bowman GPK NBA Refractor": "1:43,586",
    "Bowman GPK NIL Refractor": "1:54,483",
    "Base Chrome Retrofractor Gold Refractor": "1:217,929",
    "Base Chrome Retrofractor Orange Refractor": "1:452,622",
    "Crystalized NBA": "1:28",
    "Crystalized NIL": "1:55",
    "Future Script": "1:68",
    "Buzz Factor Autographs": "1:51",
    "Opening Statement Signatures": "1:62",
    "Timeless Touch Signatures": "1:4",
    "Future Script Gold Refractor": "1:160",
    "Buzz Factor Autographs Gold Refractor": "1:147",
    "Opening Statement Signatures Gold Refractor": "1:154",
    "Timeless Touch Signatures Gold Refractor": "1:168",
    "Future Script Orange Refractor": "1:320",
    "Buzz Factor Autographs Orange Refractor": "1:296",
    "Opening Statement Signatures Orange Refractor": "1:296",
    "Timeless Touch Signatures Orange Refractor": "1:296",
    "Future Script Black Refractor": "1:739",
    "Buzz Factor Autographs Black Refractor": "1:739",
    "Opening Statement Signatures Black Refractor": "1:739",
    "Timeless Touch Signatures Black Refractor": "1:739",
    "Future Script Red Refractor": "1:1,477",
    "Buzz Factor Autographs Red Refractor": "1:1,477",
    "Opening Statement Signatures Red Refractor": "1:1,477",
    "Timeless Touch Signatures Red Refractor": "1:1,477",
    "Future Script SuperFractor": "1:7,874",
    "Buzz Factor Autographs SuperFractor": "1:7,874",
    "Opening Statement Signatures SuperFractor": "1:7,874",
    "Timeless Touch Signatures SuperFractor": "1:7,874",
    "Bowman Dual Autographs": "1:1,969",
    "Bowman Dual Autographs SuperFractor": "1:23,622",
    "Base Chrome Autograph Refractor": "1:7",
    "Base Chrome Autograph Speckle Refractor": "1:13",
    "Base Chrome Autograph Purple Refractor": "1:12",
    "Base Chrome Autograph Blue Refractor": "1:15",
    "Base Chrome Autograph Blue X-Fractor": "1:23",
    "Base Chrome Autograph Mini-Diamond Refractor": "1:27",
    "Base Chrome Autograph Yellow Refractor": "1:31",
    "Base Chrome Autograph Gold Refractor": "1:42",
    "Base Chrome Autograph Gold Shimmer Refractor": "1:49",
    "Base Chrome Autograph Black Refractor": "1:191",
    "Base Chrome Autograph Black X-Fractor": "1:197",
    "Base Chrome Autograph Red Refractor": "1:381",
    "Base Chrome Autograph Red Lava Refractor": "1:388",
    "Base Chrome Autograph SuperFractor": "1:2,148",
    "Chrome Prospect Autograph Refractor": "1:12",
    "Chrome Prospect Autograph Speckle Refractor": "1:15",
    "Chrome Prospect Autograph Purple Refractor": "1:12",
    "Chrome Prospect Autograph Blue Refractor": "1:27",
    "Chrome Prospect Autograph Blue X-Fractor": "1:29",
    "Chrome Prospect Autograph Mini-Diamond Refractor": "1:101",
    "Chrome Prospect Autograph Yellow Refractor": "1:26",
    "Chrome Prospect Autograph Gold Refractor": "1:38",
    "Chrome Prospect Autograph Gold Shimmer Refractor": "1:38",
    "Chrome Prospect Autograph Black Refractor": "1:188",
    "Chrome Prospect Autograph Black X-Fractor": "1:189",
    "Chrome Prospect Autograph Red Refractor": "1:375",
    "Chrome Prospect Autograph Red Lava Refractor": "1:375",
    "Chrome Prospect Autograph SuperFractor": "1:1,969",
  },
  "value_se": {
    "Base": "3:1",
    "Base Purple Border": "1:123",
    "Base Pink Border": "1:140",
    "Base Blue Border": "1:163",
    "Base Yellow Border": "1:327",
    "Base Gold Border": "1:491",
    "Base Red Border": "1:5,000",
    "Base Platinum Border": "1:25,000",
    "Base Chrome": "1:1",
    "Base Chrome Reptilian Refractor": "1:8",
    "Base Chrome Refractor": "1:275",
    "Base Chrome Speckle Refractor": "1:459",
    "Base Chrome Purple Refractor": "1:548",
    "Base Chrome Fuchsia Refractor": "1:689",
    "Base Chrome Reptilian Fuchsia Refractor": "1:689",
    "Base Chrome Reptilian Blue Refractor": "1:914",
    "Base Chrome Blue Refractor": "1:914",
    "Base Chrome Blue Shimmer Refractor": "1:914",
    "Base Chrome Steel Metal Refractor": "1:1,371",
    "Base Chrome Yellow Refractor": "1:1,827",
    "Base Chrome Gold Refractor": "1:2,741",
    "Base Chrome Gold Shimmer Refractor": "1:2,741",
    "Base Chrome Reptilian Gold Refractor": "1:2,741",
    "Base Chrome Rose Gold Refractor": "1:9,137",
    "Base Chrome Rose Gold Mini-Diamond Refractor": "1:9,137",
    "Base Chrome Rose Gold X-Fractor": "1:7,265",
    "Base Chrome Black Refractor": "1:13,717",
    "Base Chrome Black X-Fractor": "1:13,717",
    "Base Chrome Red Refractor": "1:27,497",
    "Base Chrome Red Lava Refractor": "1:27,497",
    "Base Chrome Reptilian Red Refractor": "1:27,497",
    "Base Chrome FireFractor": "1:45,971",
    "Base Chrome Rookie Red RC Variation": "1:1",
    "Paper Prospect": "1:1",
    "Paper Prospect Purple Border": "1:1,377",
    "Paper Prospect Pink Border": "1:1,566",
    "Paper Prospect Blue Border": "1:1,827",
    "Paper Prospect Yellow Border": "1:3,655",
    "Paper Prospect Gold Border": "1:5,484",
    "Paper Prospect Red Border": "1:54,993",
    "Paper Prospect Platinum Border": "1:280,200",
    "Chrome Prospect": "1:1",
    "Chrome Prospect Reptilian Refractor": "1:7",
    "Chrome Prospect Refractor": "1:550",
    "Chrome Prospect Lava Refractor": "1:687",
    "Chrome Prospect Speckle Refractor": "1:917",
    "Chrome Prospect Purple Refractor": "1:1,096",
    "Chrome Prospect Fuchsia Refractor": "1:1,377",
    "Chrome Prospect Reptilian Blue Refractor": "1:1,827",
    "Chrome Prospect Blue Refractor": "1:1,827",
    "Chrome Prospect Steel Metal Refractor": "1:2,741",
    "Chrome Prospect Yellow Refractor": "1:3,655",
    "Chrome Prospect Gold Refractor": "1:5,484",
    "Chrome Prospect Reptilian Gold Refractor": "1:5,484",
    "Chrome Prospect Rose Gold Refractor": "1:18,274",
    "Chrome Prospect Rose Gold Mini-Diamond Refractor": "1:18,274",
    "Chrome Prospect Black Refractor": "1:27,497",
    "Chrome Prospect Black X-Fractor": "1:27,497",
    "Chrome Prospect Red Refractor": "1:54,993",
    "Chrome Prospect Reptilian Red Refractor": "1:54,993",
    "Chrome Prospect FireFractor": "1:91,941",
    "Talent Tracker": "1:14",
    "Gen Next": "1:14",
    "Very Important Prospects": "1:14",
    "Bowman Verified": "1:14",
    "Talent Tracker Refractor": "1:220",
    "Gen Next Refractor": "1:220",
    "Very Important Prospects Refractor": "1:220",
    "Bowman Verified Refractor": "1:220",
    "Talent Tracker Purple Refractor": "1:4,385",
    "Gen Next Purple Refractor": "1:4,385",
    "Very Important Prospects Purple Refractor": "1:4,385",
    "Bowman Verified Purple Refractor": "1:4,385",
    "Talent Tracker Fuchsia Refractor": "1:5,510",
    "Gen Next Fuchsia Refractor": "1:5,510",
    "Very Important Prospects Fuchsia Refractor": "1:5,510",
    "Bowman Verified Fuchsia Refractor": "1:5,510",
    "Talent Tracker Mini-Diamond Refractor": "1:7,310",
    "Gen Next Mini-Diamond Refractor": "1:7,310",
    "Very Important Prospects Mini-Diamond Refractor": "1:7,310",
    "Bowman Verified Mini-Diamond Refractor": "1:7,310",
    "Talent Tracker Aqua Refractor": "1:8,770",
    "Gen Next Aqua Refractor": "1:8,770",
    "Very Important Prospects Aqua Refractor": "1:8,770",
    "Bowman Verified Aqua Refractor": "1:8,770",
    "Talent Tracker Gold Refractor": "1:21,956",
    "Gen Next Gold Refractor": "1:21,956",
    "Very Important Prospects Gold Refractor": "1:21,956",
    "Bowman Verified Gold Refractor": "1:21,956",
    "Talent Tracker Red Refractor": "1:226,316",
    "Gen Next Red Refractor": "1:226,316",
    "Very Important Prospects Red Refractor": "1:226,316",
    "Bowman Verified Red Refractor": "1:226,316",
    "Talent Tracker SuperFractor": "1:1,176,840",
    "Gen Next SuperFractor": "1:1,176,840",
    "Very Important Prospects SuperFractor": "1:1,176,840",
    "Bowman Verified SuperFractor": "1:1,176,840",
    "ROY Favorites": "1:23",
    "Hobby Stars": "1:23",
    "Young Kings": "1:14",
    "Rockstar Rookies": "1:17",
    "Greatness Loading": "1:14",
    "ROY Favorites Refractor": "1:366",
    "Hobby Stars Refractor": "1:366",
    "Young Kings Refractor": "1:220",
    "Rockstar Rookies Refractor": "1:274",
    "Greatness Loading Refractor": "1:220",
    "ROY Favorites Purple Refractor": "1:7,310",
    "Hobby Stars Purple Refractor": "1:7,310",
    "Young Kings Purple Refractor": "1:4,385",
    "Rockstar Rookies Purple Refractor": "1:5,484",
    "Greatness Loading Purple Refractor": "1:4,385",
    "ROY Favorites Fuchsia Refractor": "1:9,180",
    "Hobby Stars Fuchsia Refractor": "1:9,180",
    "Young Kings Fuchsia Refractor": "1:5,510",
    "Rockstar Rookies Fuchsia Refractor": "1:6,891",
    "Greatness Loading Fuchsia Refractor": "1:5,510",
    "ROY Favorites Mini-Diamond Refractor": "1:12,183",
    "Hobby Stars Mini-Diamond Refractor": "1:12,183",
    "Young Kings Mini-Diamond Refractor": "1:7,310",
    "Rockstar Rookies Mini-Diamond Refractor": "1:9,137",
    "Greatness Loading Mini-Diamond Refractor": "1:7,310",
    "ROY Favorites Aqua Refractor": "1:14,638",
    "Hobby Stars Aqua Refractor": "1:14,638",
    "Young Kings Aqua Refractor": "1:8,770",
    "Rockstar Rookies Aqua Refractor": "1:10,978",
    "Greatness Loading Aqua Refractor": "1:8,770",
    "ROY Favorites Gold Refractor": "1:36,548",
    "Hobby Stars Gold Refractor": "1:36,548",
    "Young Kings Gold Refractor": "1:21,956",
    "Rockstar Rookies Gold Refractor": "1:27,497",
    "Greatness Loading Gold Refractor": "1:21,956",
    "ROY Favorites Red Refractor": "1:367,763",
    "Hobby Stars Red Refractor": "1:367,763",
    "Young Kings Red Refractor": "1:226,316",
    "Rockstar Rookies Red Refractor": "1:280,200",
    "Greatness Loading Red Refractor": "1:226,316",
    "ROY Favorites SuperFractor": "1:1,961,399",
    "Hobby Stars SuperFractor": "1:1,961,399",
    "Young Kings SuperFractor": "1:1,176,840",
    "Rockstar Rookies SuperFractor": "1:1,471,050",
    "Greatness Loading SuperFractor": "1:1,176,840",
    "Base Chrome Retrofractor Refractor": "1:43,586",
    "Anime NBA Refractor": "1:8,050",
    "Anime NIL Refractor": "1:21,793",
    "Bowman GPK NBA Refractor": "1:43,586",
    "Bowman GPK NIL Refractor": "1:54,483",
    "Base Chrome Retrofractor Gold Refractor": "1:217,929",
    "Base Chrome Retrofractor Orange Refractor": "1:452,622",
    "Anime NBA Red Refractor": "1:178,306",
    "Anime NBA Black Refractor": "1:87,823",
    "Anime NIL Black Refractor": "1:452,622",
    "Crystalized NBA": "1:1,346",
    "Crystalized NIL": "1:2,691",
    "Base Chrome Autograph": "1:313",
    "Base Paper Retail Autographs": "1:3,816",
    "Paper Prospect Retail Autograph": "1:778",
    "Base Paper Retail Autographs Blue Border": "1:1,771",
    "Base Paper Retail Autographs Green Border": "1:1,505",
    "Base Paper Retail Autographs Gold Border": "1:2,544",
    "Base Paper Retail Autographs Orange Border": "1:2,493",
    "Base Paper Retail Autographs Red Border": "1:12,440",
    "Base Paper Retail Autographs Platinum Border": "1:61,293",
    "Paper Prospect Retail Autograph Blue Border": "1:905",
    "Paper Prospect Retail Autograph Green Border": "1:624",
    "Paper Prospect Retail Autograph Gold Border": "1:1,222",
    "Paper Prospect Retail Autograph Orange Border": "1:2,443",
    "Paper Prospect Retail Autograph Red Border": "1:12,208",
    "Paper Prospect Retail Autograph Platinum Border": "1:60,661",
  },
  "mega_se": {
    "Base": "12:1",
    "Base Chrome Rookie Red RC Variation": "1:60",
    "Chrome Prospect Autograph": "1:1,000",
    "Base Chrome Autograph": "1:110",
    "Mega Rookies": "1:13",
    "Mega Prospects": "1:13",
    "Mega Rookies Blue Mojo": "1:622",
    "Mega Prospects Blue Mojo": "1:622",
    "Mega Rookies Green Mojo": "1:942",
    "Mega Prospects Green Mojo": "1:942",
    "Mega Rookies Yellow Mojo": "1:1,243",
    "Mega Prospects Yellow Mojo": "1:1,243",
    "Mega Rookies Gold Mojo": "1:1,864",
    "Mega Prospects Gold Mojo": "1:1,864",
    "Mega Rookies Orange Mojo": "1:3,728",
    "Mega Prospects Orange Mojo": "1:3,728",
    "Mega Rookies Red Mojo": "1:18,640",
    "Mega Prospects Red Mojo": "1:18,640",
    "Mega Rookies Black Mojo": "1:9,320",
    "Mega Prospects Black Mojo": "1:9,320",
    "Mega Rookies Rose Gold Mojo": "1:93,200",
    "Mega Prospects Rose Gold Mojo": "1:93,200",
  },
  "bulk": {
    "Base Chrome Rookie Red RC Variation": "1:10",
    "Base Chrome Retrofractor Refractor": "1:43,586",
    "Bowman Spotlights NBA Refractor": "1:27",
    "Bowman Spotlights NIL Refractor": "1:53",
    "Anime NBA Refractor": "1:532",
    "Anime NIL Refractor": "1:5,000",
    "Bowman GPK NBA Refractor": "1:10,000",
    "Bowman GPK NIL Refractor": "1:12,500",
    "Anime NBA Red Refractor": "1:50,000",
    "Anime NIL Black Refractor": "1:452,622",
    "Anime NBA Black Refractor": "1:25,000",
    "Base Chrome Retrofractor Gold Refractor": "1:50,000",
    "Base Chrome Retrofractor Orange Refractor": "1:452,622",
    "Chrome Prospect Autograph": "1:1,000",
    "Chrome Prospect FireFractor": "1:5,000",
    "Chrome Prospect Red Refractor": "1:10,000",
    "Chrome Prospect Reptilian Red Refractor": "1:10,000",
    "Chrome Prospect Black Refractor": "1:5,000",
    "Chrome Prospect Black X-Fractor": "1:5,000",
    "Chrome Prospect Rose Gold Refractor": "1:3,334",
    "Chrome Prospect Rose Gold Mini-Diamond Refractor": "1:3,334",
    "Chrome Prospect Gold Refractor": "1:981",
    "Chrome Prospect Reptilian Gold Refractor": "1:981",
    "Chrome Prospect Orange Refractor": "1:899",
    "Chrome Prospect Reptilian Orange Refractor": "1:899",
    "Chrome Prospect Yellow Refractor": "1:658",
    "Chrome Prospect Blue Refractor": "1:327",
    "Chrome Prospect Reptilian Blue Refractor": "1:327",
    "Chrome Prospect Purple Refractor": "1:196",
    "Chrome Prospect Fuchsia Refractor": "1:247",
    "Chrome Prospect Refractor": "1:98",
    "Chrome Prospect Reptilian Refractor": "1:14",
    "Paper Prospect Red Border": "1:10,000",
    "Paper Prospect Platinum Border": "1:50,000",
    "Paper Prospect Gold Border": "1:981",
    "Paper Prospect Yellow Border": "1:658",
    "Paper Prospect Blue Border": "1:327",
    "Paper Prospect Purple Border": "1:247",
    "Paper Prospect Pink Border": "1:280",
    "Base Chrome Red Refractor": "1:5,000",
    "Base Chrome Red Lava Refractor": "1:5,000",
    "Base Chrome Reptilian Red Refractor": "1:5,000",
    "Base Chrome FireFractor": "1:2,381",
    "Base Chrome Black Refractor": "1:2,500",
    "Base Chrome Black X-Fractor": "1:2,500",
    "Base Chrome Rose Gold Refractor": "1:1,667",
    "Base Chrome Rose Gold Mini-Diamond Refractor": "1:1,667",
    "Base Chrome Rose Gold X-Fractor": "1:1,667",
    "Base Chrome Gold Refractor": "1:491",
    "Base Chrome Gold Shimmer Refractor": "1:491",
    "Base Chrome Reptilian Gold Refractor": "1:491",
    "Base Chrome Yellow Refractor": "1:327",
    "Base Chrome Blue Refractor": "1:163",
    "Base Chrome Blue Shimmer Refractor": "1:163",
    "Base Chrome Reptilian Blue Refractor": "1:163",
    "Base Chrome Purple Refractor": "1:186",
    "Base Chrome Fuchsia Refractor": "1:123",
    "Base Chrome Reptilian Fuchsia Refractor": "1:123",
    "Base Chrome Refractor": "1:878",
    "Base Chrome Reptilian Refractor": "1:214",
    "Base Red Border": "1:5,000",
    "Base Platinum Border": "1:25,000",
    "Base Gold Border": "1:491",
    "Base Yellow Border": "1:327",
    "Base Blue Border": "1:163",
    "Base Pink Border": "1:140",
    "Base Purple Border": "1:123",
    "Base Paper Retail Autographs": "1:863",
    "Base Paper Retail Autographs Blue Border": "1:397",
    "Base Paper Retail Autographs Green Border": "1:338",
    "Base Paper Retail Autographs Gold Border": "1:575",
    "Base Paper Retail Autographs Orange Border": "1:562",
    "Base Paper Retail Autographs Red Border": "1:2,942",
    "Base Paper Retail Autographs Platinum Border": "1:16,667",
    "Paper Prospect Retail Autograph": "1:175",
    "Paper Prospect Retail Autograph Blue Border": "1:204",
    "Paper Prospect Retail Autograph Green Border": "1:140",
    "Paper Prospect Retail Autograph Gold Border": "1:275",
    "Paper Prospect Retail Autograph Orange Border": "1:550",
    "Paper Prospect Retail Autograph Red Border": "1:2,778",
    "Paper Prospect Retail Autograph Platinum Border": "1:16,667",
  },
}

db.execute("UPDATE sets SET pack_odds = ? WHERE id = ?", (json.dumps(pack_odds), set_id))
db.commit()

# Count entries per box type
for bt in pack_odds:
    print(f"  {bt}: {len(pack_odds[bt])} entries")
print(f"\nTotal: {sum(len(v) for v in pack_odds.values())} entries")
print(f"Pack odds updated for set ID {set_id}")
db.close()
